In [1]:
from f1_race.data_loader import DataLoader

loader = DataLoader(cache_dir="race_data")
seasons = loader.load_seasons(years=[2020,2021,2022,2023,2024,2025]) # , force_update=True
weekend = loader.load_weekend(2024, 8) # , force_update=True
race = loader.load_session(2024, 8, "Race", force_update=False)

race.telemetry["MAG"].to_pandas()

✓ FastF1 cache: race_data/.fastf1_cache
✓ DataLoader initialized: race_data
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Monaco Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Monaco Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded session from cache: Race

,RawTime,DriverAhead,DistanceToDriverAhead,RPM,Speed,nGear,Throttle,Brake,DRS,Source,...,RelativeDistance,Status,X,Y,Z,LapNumber,session_time,progress,status,TimeToDriverAhead
0,2024-05-26 13:03:11.069,,0.159444,10899.543750,0.000000,1,22.00000,False,1,interpolation,...,0.000002,OnTrack,-7364.008124,-8260.987637,503.0,1.0,0.000,0.001317,racing,-0.290301
1,2024-05-26 13:03:11.156,,0.159444,10899.000000,0.000000,1,22.00000,False,1,car,...,0.000000,OnTrack,-7364.012660,-8260.980698,503.0,1.0,0.087,0.000000,racing,NaN
2,2024-05-26 13:03:11.230,,0.159444,10804.649837,0.000000,1,22.00000,False,1,pos,...,-0.000004,OnTrack,-7364.000000,-8261.000000,503.0,1.0,0.161,-0.003475,racing,NaN
3,2024-05-26 13:03:11.356,23,0.159444,10644.000000,0.000000,1,22.00000,False,1,car,...,0.000000,OnTrack,-7363.944648,-8261.084389,503.0,1.0,0.287,0.000000,racing,NaN
4,2024-05-26 13:03:11.469,23,0.103141,10050.750336,1.059374,1,22.70625,False,1,pos,...,0.000046,OnTrack,-7364.000000,-8261.000000,503.0,1.0,0.400,0.035843,racing,0.023165
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18706,2024-05-26 13:44:07.330,55,2294.930277,0.000000,0.000000,6,104.00000,True,1,pos,...,1.000000,OnTrack,-2918.000000,-3657.000000,861.0,1.0,2456.261,773.180833,retired,2431.179153
18707,2024-05-26 13:44:07.404,55,2295.588056,0.000000,0.000000,6,104.00000,True,1,car,...,1.000000,OnTrack,-2918.000000,-3657.000000,861.0,1.0,2456.335,773.180833,retired,2431.253153
18708,2024-05-26 13:44:07.630,55,2298.036390,0.000000,0.000000,6,104.00000,True,1,pos,...,1.000000,OnTrack,-2918.000000,-3657.000000,861.0,1.0,2456.561,773.180833,retired,2431.479153
18709,2024-05-26 13:44:07.684,55,2298.621389,0.000000,0.000000,6,104.00000,True,1,car,...,1.000000,OnTrack,-2918.000000,-3657.000000,861.0,1.0,2456.615,773.180833,retired,2431.533153
18710,2024-05-26 13:44:07.708,55,2298.621389,0.000000,0.000000,6,104.00000,True,1,interpolation,...,1.000000,OnTrack,-2918.000000,-3657.000000,861.0,1.0,2456.639,773.180833,retired,2431.557153

In [1]:
from f1_race import Manager
manager = Manager()
manager.process_season(2024, force_update=True)
manager.process_season(2025, force_update=True)

✓ FastF1 cache: race_data/.fastf1_cache
✓ DataLoader initialized: race_data
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📅 Processing 2024 season (25 rounds)...
⚠️  Force updating all races from FastF1
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 0...

core           INFO 	Loading data for Bahrain Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✗ Error fetching 2024 R0 event: Cannot get testing event by round number!
  ✗  0. Pre-Season Testing: Failed to load weekend data
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 1...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 714 points, 5366m
    In-lap: 1189 points
    Out-lap: 938 points
    Clipped: 1085 points (from 2127)
  ✓ Pit lane: 1085 points, 4669m

core           INFO 	Loading data for Bahrain Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data

  ✓ Extracted rotation: 92.0°
  ✓ Extracted marshal sectors: 18 sectors
  ✓ Weekend complete: Bahrain Grand Prix
✓ Cached weekend to race_data/2024/01_Sakhir/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 1...
  → Building circuit data...

core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 714 points, 5366m
    In-lap: 1189 points
    Out-lap: 938 points
    Clipped: 1085 points (from 2127)
  ✓ Pit lane: 1085 points, 4669m

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 92.0°
  ✓ Extracted marshal sectors: 18 sectors
  ✓ Weekend complete: Bahrain Grand Prix
✓ Cached weekend to race_data/2024/01_Sakhir/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Bahrain Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R1 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 41787 raw points
    ✓ PER: 41961 raw points
    ✓ SAI: 41981 raw points
    ✓ LEC: 42085 raw points
    ✓ RUS: 42140 raw points
    ✓ NOR: 42148 raw points
    ✓ HAM: 42162 raw points
    ✓ PIA: 42207 raw points
    ✓ ALO: 42352 raw points
    ✓ STR: 42486 raw points
    ✓ ZHO: 41841 raw points
    ✓ MAG: 41854 raw points
    ✓ RIC: 41857 raw points
    ✓ TSU: 41860 raw points
    ✓ ALB: 41882 raw points
    ✓ HUL: 41923 raw points
    ✓ OCO: 42025 raw points
    ✓ GAS: 42030 raw points
    ✓ BOT: 42409 raw points
    ✓ SAR: 41944 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 37 track status, 28 messages, 157 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 11 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Saudi Arabian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/01_Sakhir/Race.pkl

  ✓  1. Bahrain Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 2...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 670 points, 6106m
    In-lap: 796 points
    Out-lap: 819 points
    Clipped: 614 points (from 1615)
  ✓ Pit lane: 614 points, 3998m

core           INFO 	Loading data for Saudi Arabian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 104.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Saudi Arabian Grand Prix
✓ Cached weekend to race_data/2024/02_Jeddah/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 2...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 670 points, 6106m
    In-lap: 796 points
    Out-lap: 819 points
    Clipped: 614 points (from 1615)
  ✓ Pit lane: 614 points, 3998m

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 104.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Saudi Arabian Grand Prix
✓ Cached weekend to race_data/2024/02_Jeddah/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Saudi Arabian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R2 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '81', '14', '63', '38', '4', '44', '27', '23', '20', '31', '2', '22', '3', '77', '24', '18', '10']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 37321 raw points
    ✓ GAS: 963 raw points
    ✓ PER: 37386 raw points
    ✓ ALO: 37599 raw points
    ✓ LEC: 37464 raw points
    ✓ STR: 4319 raw points
    ✓ SAR: 37371 raw points
    ✓ MAG: 37993 raw points
    ✓ TSU: 37361 raw points
    ✓ ALB: 38011 raw points
    ✓ ZHO: 37547 raw points
    ✓ HUL: 37924 raw points
    ✓ RIC: 37477 raw points
    ✓ OCO: 37348 raw points
    ✓ BEA: 37658 raw points
    ✓ NOR: 37681 raw points
    ✓ HAM: 37692 raw points
    ✓ RUS: 37636 raw points
    ✓ BOT: 37494 raw points
    ✓ PIA: 37571 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 18 track status, 42 messages, 146 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 21 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2024/02_Jeddah/Race.pkl

  ✓  2. Saudi Arabian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 3...

core           INFO 	Loading data for Australian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.

  ✓ Track: 590 points, 5234m
    In-lap: 1036 points
    Out-lap: 784 points
    Clipped: 755 points (from 1820)
  ✓ Pit lane: 755 points, 2026m

core           INFO 	Loading data for Australian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 44.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Australian Grand Prix
✓ Cached weekend to race_data/2024/03_Melbourne/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 3...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.
core        WARNING 	Car number 55 cannot be located on track while calculating the distancebetween cars.

  ✓ Track: 590 points, 5234m
    In-lap: 1036 points
    Out-lap: 784 points
    Clipped: 755 points (from 1820)
  ✓ Pit lane: 755 points, 2026m

core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 44.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Australian Grand Prix
✓ Cached weekend to race_data/2024/03_Melbourne/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Australian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R3 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 2727 raw points
    ✓ GAS: 37053 raw points
    ✓ PER: 37212 raw points
    ✓ ALO: 37399 raw points
    ✓ LEC: 36797 raw points
    ✓ STR: 37491 raw points
    ✓ MAG: 36810 raw points
    ✓ TSU: 37508 raw points
    ✓ ALB: 36816 raw points
    ✓ ZHO: 37116 raw points
    ✓ HUL: 37582 raw points
    ✓ RIC: 36866 raw points
    ✓ OCO: 37190 raw points
    ✓ NOR: 36826 raw points
    ✓ HAM: 10567 raw points
    ✓ SAI: 36779 raw points
    ✓ RUS: 35956 raw points
    ✓ BOT: 37102 raw points
    ✓ PIA: 37054 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...

core           INFO 	Loading data for Japanese Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  ✓ Complete telemetry: 19 drivers with all derived fields
  → Events: 60 track status, 14 messages, 144 weather samples
  → Building results with telemetry: 19 drivers, session_time=✓
  → Results: 25 fastest laps, 1 position snapshots
  ✓ Session complete: 19 drivers, 19 with telemetry
✓ Cached session to race_data/2024/03_Melbourne/Race.pkl

  ✓  3. Australian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 4...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '40', '44', '55', '63', '77', '81']

  ✓ Track: 670 points, 5776m
    In-lap: 861 points
    Out-lap: 861 points
    Clipped: 702 points (from 1722)
  ✓ Pit lane: 702 points, 4196m

core           INFO 	Loading data for Japanese Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data

  ✓ Extracted rotation: 49.0°
  ✓ Extracted marshal sectors: 22 sectors
  ✓ Weekend complete: Japanese Grand Prix
✓ Cached weekend to race_data/2024/04_Suzuka/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 4...
  → Building circuit data...

core           INFO 	Finished loading data for 20 drivers: ['1', '2', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '40', '44', '55', '63', '77', '81']

  ✓ Track: 670 points, 5776m
    In-lap: 861 points
    Out-lap: 861 points
    Clipped: 702 points (from 1722)
  ✓ Pit lane: 702 points, 4196m
  ✓ Extracted rotation: 49.0°
  ✓ Extracted marshal sectors: 22 sectors
  ✓ Weekend complete: Japanese Grand Prix
✓ Cached weekend to race_data/2024/04_Suzuka/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Japanese Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R4 R...

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '4', '14', '63', '81', '44', '22', '27', '18', '20', '77', '31', '10', '2', '24', '3', '23']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 40270 raw points
    ✓ PER: 40386 raw points
    ✓ SAI: 40490 raw points
    ✓ LEC: 40662 raw points
    ✓ NOR: 40528 raw points
    ✓ ALO: 40687 raw points
    ✓ RUS: 40839 raw points
    ✓ PIA: 40738 raw points
    ✓ HAM: 40812 raw points
    ✓ TSU: 40563 raw points
    ✓ HUL: 40570 raw points
    ✓ STR: 40733 raw points
    ✓ MAG: 40830 raw points
    ✓ BOT: 40678 raw points
    ✓ OCO: 40886 raw points
    ✓ GAS: 41015 raw points
    ✓ SAR: 41259 raw points
    ✓ ZHO: 11161 raw points
    ✓ RIC: 991 raw points
    ✓ ALB: 991 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...

core           INFO 	Loading data for Chinese Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info

  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 36 track status, 28 messages, 181 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 13 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2024/04_Suzuka/Race.pkl

  ✓  4. Japanese Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 5...
  → Building circuit data...

req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 736 points, 5399m
    In-lap: 4034 points
    Out-lap: 832 points
    Clipped: 1249 points (from 4866)
  ✓ Pit lane: 1249 points, 2130m

core           INFO 	Loading data for Chinese Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data

  ✓ Extracted rotation: 237.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Chinese Grand Prix
✓ Cached weekend to race_data/2024/05_Shanghai/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 5...
  → Building circuit data...

core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 736 points, 5399m
    In-lap: 4034 points
    Out-lap: 832 points
    Clipped: 1249 points (from 4866)
  ✓ Pit lane: 1249 points, 2130m
  ✓ Extracted rotation: 237.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Chinese Grand Prix
✓ Cached weekend to race_data/2024/05_Shanghai/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Chinese Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R5 R...

core           INFO 	Loading data for Chinese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 1 completed the race distance 00:08.313000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '16', '55', '63', '14', '81', '44', '27', '31', '23', '10', '24', '18', '20', '2', '3', '22', '77']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 46352 raw points
    ✓ GAS: 46883 raw points
    ✓ PER: 46496 raw points
    ✓ ALO: 46681 raw points
    ✓ LEC: 46534 raw points
    ✓ STR: 46991 raw points
    ✓ SAR: 47008 raw points
    ✓ MAG: 46950 raw points
    ✓ TSU: 22426 raw points
    ✓ ALB: 46853 raw points
    ✓ ZHO: 46905 raw points
    ✓ HUL: 46814 raw points
    ✓ RIC: 29028 raw points
    ✓ OCO: 46833 raw points
    ✓ NOR: 46457 raw points
    ✓ HAM: 46791 raw points
    ✓ SAI: 46616 raw points
    ✓ RUS: 46649 raw points
    ✓ BOT: 15553 raw points
    ✓ PIA: 46779 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 17 track status, 31 messages, 165 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 8 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Miami Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/05_Shanghai/Race.pkl

  ✓  5. Chinese Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 6...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 686 points, 5341m
    In-lap: 5602 points
    Out-lap: 960 points
    Clipped: 992 points (from 6562)
  ✓ Pit lane: 992 points, 2173m

core           INFO 	Loading data for Miami Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 2.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Miami Grand Prix
✓ Cached weekend to race_data/2024/06_Miami/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 6...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 686 points, 5341m
    In-lap: 5602 points
    Out-lap: 960 points
    Clipped: 992 points (from 6562)
  ✓ Pit lane: 992 points, 2173m

core           INFO 	Loading data for Miami Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 2.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Miami Grand Prix
✓ Cached weekend to race_data/2024/06_Miami/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Miami Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R6 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '11', '55', '44', '22', '63', '14', '31', '27', '10', '81', '24', '3', '77', '18', '23', '20', '2']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 41628 raw points
    ✓ GAS: 41914 raw points
    ✓ PER: 41684 raw points
    ✓ ALO: 41852 raw points
    ✓ LEC: 41644 raw points
    ✓ STR: 41917 raw points
    ✓ SAR: 19793 raw points
    ✓ MAG: 41989 raw points
    ✓ TSU: 41767 raw points
    ✓ ALB: 42151 raw points
    ✓ ZHO: 41953 raw points
    ✓ HUL: 41881 raw points
    ✓ RIC: 41959 raw points
    ✓ OCO: 41874 raw points
    ✓ NOR: 41567 raw points
    ✓ HAM: 41698 raw points
    ✓ SAI: 41656 raw points
    ✓ RUS: 41835 raw points
    ✓ BOT: 41972 raw points
    ✓ PIA: 41952 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 16 track status, 51 messages, 150 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 18 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Emilia Romagna Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/06_Miami/Race.pkl

  ✓  6. Miami Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 7...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '2'
core        WARNING 	Fixed incorrect tyre stint information for driver '3'
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '24'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '22', '23', '24', '27', '31', '44', '50', '55', '63', '77', '81']

  ✓ Track: 575 points, 4876m
    In-lap: 908 points
    Out-lap: 761 points
    Clipped: 648 points (from 1669)
  ✓ Pit lane: 648 points, 4863m

core           INFO 	Loading data for Emilia Romagna Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '2'
core        WARNING 	Fixed incorrect tyre stint information for driver '3'
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '24'
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Emilia Romagna Grand Prix
✓ Cached weekend to race_data/2024/07_Imola/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 7...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '22', '23', '24', '27', '31', '44', '50', '55', '63', '77', '81']

  ✓ Track: 575 points, 4876m
    In-lap: 908 points
    Out-lap: 761 points
    Clipped: 648 points (from 1669)
  ✓ Pit lane: 648 points, 4863m
  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Emilia Romagna Grand Prix
✓ Cached weekend to race_data/2024/07_Imola/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Emilia Romagna Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R7 R...

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '81', '55', '44', '63', '11', '18', '22', '27', '20', '3', '31', '24', '10', '2', '77', '14', '23']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 39140 raw points
    ✓ NOR: 39145 raw points
    ✓ LEC: 39201 raw points
    ✓ PIA: 39245 raw points
    ✓ SAI: 39306 raw points
    ✓ HAM: 39401 raw points
    ✓ RUS: 39479 raw points
    ✓ PER: 39532 raw points
    ✓ STR: 39713 raw points
    ✓ TSU: 39272 raw points
    ✓ HUL: 39326 raw points
    ✓ MAG: 39335 raw points
    ✓ RIC: 39342 raw points
    ✓ OCO: 39455 raw points
    ✓ ZHO: 39463 raw points
    ✓ GAS: 39496 raw points
    ✓ SAR: 39506 raw points
    ✓ BOT: 39542 raw points
    ✓ ALO: 39675 raw points
    ✓ ALB: 33533 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 78 track status, 18 messages, 143 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 10 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Monaco Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/07_Imola/Race.pkl

  ✓  7. Emilia Romagna Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 8...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 566 points, 3286m
    In-lap: 4029 points
    Out-lap: 759 points
    Clipped: 628 points (from 4788)
  ✓ Pit lane: 628 points, 1193m

core           INFO 	Loading data for Monaco Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 315.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Monaco Grand Prix
✓ Cached weekend to race_data/2024/08_Monaco/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 8...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 566 points, 3286m
    In-lap: 4029 points
    Out-lap: 759 points
    Clipped: 628 points (from 4788)
  ✓ Pit lane: 628 points, 1193m

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 315.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Monaco Grand Prix
✓ Cached weekend to race_data/2024/08_Monaco/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Monaco Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R8 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '14', '3', '77', '18', '2', '24', '31', '11', '27', '20']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ LEC: 65794 raw points
    ✓ PIA: 65866 raw points
    ✓ SAI: 65899 raw points
    ✓ NOR: 65947 raw points
    ✓ RUS: 66025 raw points
    ✓ VER: 66066 raw points
    ✓ HAM: 66110 raw points
    ✓ TSU: 66033 raw points
    ✓ ALB: 66139 raw points
    ✓ GAS: 66189 raw points
    ✓ ALO: 65765 raw points
    ✓ RIC: 65767 raw points
    ✓ BOT: 65768 raw points
    ✓ STR: 65780 raw points
    ✓ SAR: 65803 raw points
    ✓ ZHO: 66148 raw points
    ✓ OCO: 18711 raw points
    ✓ PER: 18711 raw points
    ✓ HUL: 18711 raw points
    ✓ MAG: 18711 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 97 track status, 19 messages, 200 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 30 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2024/08_Monaco/Race.pkl

  ✓  8. Monaco Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 9...
  → Building circuit data...

core           INFO 	Loading data for Canadian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '44', '55', '61', '63', '77', '81']

  ✓ Track: 661 points, 4333m
    In-lap: 2983 points
    Out-lap: 765 points
    Clipped: 714 points (from 3748)
  ✓ Pit lane: 714 points, 1769m

core           INFO 	Loading data for Canadian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data

  ✓ Extracted rotation: 62.0°
  ✓ Extracted marshal sectors: 15 sectors
  ✓ Weekend complete: Canadian Grand Prix
✓ Cached weekend to race_data/2024/09_Montréal/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 9...
  → Building circuit data...

core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '44', '55', '61', '63', '77', '81']

  ✓ Track: 661 points, 4333m
    In-lap: 2983 points
    Out-lap: 765 points
    Clipped: 714 points (from 3748)
  ✓ Pit lane: 714 points, 1769m

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 62.0°
  ✓ Extracted marshal sectors: 15 sectors
  ✓ Weekend complete: Canadian Grand Prix
✓ Cached weekend to race_data/2024/09_Montréal/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Canadian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R9 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '63', '44', '81', '14', '18', '3', '10', '31', '27', '20', '77', '22', '24', '55', '23', '11', '16', '2']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 48342 raw points
    ✓ GAS: 48559 raw points
    ✓ PER: 36610 raw points
    ✓ ALO: 48470 raw points
    ✓ LEC: 29881 raw points
    ✓ STR: 48517 raw points
    ✓ SAR: 16589 raw points
    ✓ MAG: 48571 raw points
    ✓ TSU: 48736 raw points
    ✓ ALB: 36644 raw points
    ✓ ZHO: 48742 raw points
    ✓ HUL: 48566 raw points
    ✓ RIC: 48551 raw points
    ✓ OCO: 48562 raw points
    ✓ NOR: 48374 raw points
    ✓ HAM: 48382 raw points
    ✓ SAI: 37225 raw points
    ✓ RUS: 48377 raw points
    ✓ BOT: 48641 raw points
    ✓ PIA: 48417 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 54 track status, 65 messages, 113 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 71 fastest laps, 1 position snapshots
  ✓ Extracted 3 rain event(s)
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Spanish Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/09_Montréal/Race.pkl

  ✓  9. Canadian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 10...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '31', '44', '50', '55', '63', '77', '81']

  ✓ Track: 567 points, 4624m
    In-lap: 868 points
    Out-lap: 668 points
    Clipped: 536 points (from 1536)
  ✓ Pit lane: 536 points, 3445m

core           INFO 	Loading data for Spanish Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 303.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Spanish Grand Prix
✓ Cached weekend to race_data/2024/10_Barcelona/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 10...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '31', '44', '50', '55', '63', '77', '81']

  ✓ Track: 567 points, 4624m
    In-lap: 868 points
    Out-lap: 668 points
    Clipped: 536 points (from 1536)
  ✓ Pit lane: 536 points, 3445m

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 303.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Spanish Grand Prix
✓ Cached weekend to race_data/2024/10_Barcelona/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Spanish Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R10 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '63', '16', '55', '81', '11', '10', '31', '27', '14', '24', '18', '3', '77', '20', '23', '22', '2']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 40343 raw points
    ✓ NOR: 40363 raw points
    ✓ HAM: 40476 raw points
    ✓ RUS: 40511 raw points
    ✓ LEC: 40515 raw points
    ✓ SAI: 40574 raw points
    ✓ PIA: 40596 raw points
    ✓ PER: 40791 raw points
    ✓ GAS: 40813 raw points
    ✓ OCO: 40891 raw points
    ✓ HUL: 40911 raw points
    ✓ ALO: 40415 raw points
    ✓ ZHO: 40459 raw points
    ✓ STR: 40534 raw points
    ✓ RIC: 40669 raw points
    ✓ BOT: 40741 raw points
    ✓ MAG: 40753 raw points
    ✓ ALB: 40779 raw points
    ✓ TSU: 40826 raw points
    ✓ SAR: 40377 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 65 track status, 38 messages, 154 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 16 fastest laps, 1 position snapshots
  ✓ Extracted 1 rain event(s)
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2024/10_Barcelona/Race.pkl

  ✓ 10. Spanish Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 11...

core           INFO 	Loading data for Austrian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 497 points, 4295m
    In-lap: 647 points
    Out-lap: 2273 points
    Clipped: 485 points (from 2920)
  ✓ Pit lane: 485 points, 1391m

core           INFO 	Loading data for Austrian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 1.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Austrian Grand Prix
✓ Cached weekend to race_data/2024/11_Spielberg/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 11...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 497 points, 4295m
    In-lap: 647 points

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

    Out-lap: 2273 points
    Clipped: 485 points (from 2920)
  ✓ Pit lane: 485 points, 1391m
  ✓ Extracted rotation: 1.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Austrian Grand Prix
✓ Cached weekend to race_data/2024/11_Spielberg/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Austrian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R11 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '81', '55', '44', '1', '27', '11', '20', '3', '10', '16', '31', '18', '22', '23', '77', '24', '14', '2', '4']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ RUS: 38473 raw points
    ✓ PIA: 38491 raw points
    ✓ SAI: 38511 raw points
    ✓ HAM: 38656 raw points
    ✓ VER: 38689 raw points
    ✓ HUL: 38883 raw points
    ✓ PER: 38889 raw points
    ✓ MAG: 38933 raw points
    ✓ RIC: 38939 raw points
    ✓ GAS: 38945 raw points
    ✓ LEC: 38988 raw points
    ✓ OCO: 38996 raw points
    ✓ STR: 38553 raw points
    ✓ TSU: 38578 raw points
    ✓ ALB: 38559 raw points
    ✓ BOT: 38622 raw points
    ✓ ZHO: 38821 raw points
    ✓ ALO: 38840 raw points
    ✓ SAR: 38522 raw points
    ✓ NOR: 34924 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 69 track status, 50 messages, 143 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 14 fastest laps, 1 position snapshots
  ✓ Extracted 1 rain event(s)
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for British Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/11_Spielberg/Race.pkl

  ✓ 11. Austrian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 12...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '3', '4', '14', '16', '18', '22', '23', '24', '27', '31', '37', '44', '45', '50', '55', '61', '63', '77', '81']

  ✓ Track: 647 points, 5819m
    In-lap: 3475 points
    Out-lap: 816 points
    Clipped: 987 points (from 4291)
  ✓ Pit lane: 987 points, 2316m

core           INFO 	Loading data for British Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 92.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: British Grand Prix
✓ Cached weekend to race_data/2024/12_Silverstone/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 12...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '3', '4', '14', '16', '18', '22', '23', '24', '27', '31', '37', '44', '45', '50', '55', '61', '63', '77', '81']

  ✓ Track: 647 points, 5819m
    In-lap: 3475 points
    Out-lap: 816 points
    Clipped: 987 points (from 4291)
  ✓ Pit lane: 987 points, 2316m

core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 92.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: British Grand Prix
✓ Cached weekend to race_data/2024/12_Silverstone/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: British Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R12 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '1', '4', '81', '55', '27', '18', '14', '23', '22', '2', '20', '3', '16', '77', '31', '11', '24', '63', '10']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ HAM: 37880 raw points
    ✓ VER: 37891 raw points
    ✓ NOR: 37935 raw points
    ✓ PIA: 37971 raw points
    ✓ SAI: 38234 raw points
    ✓ HUL: 38294 raw points
    ✓ STR: 38301 raw points
    ✓ ALO: 38354 raw points
    ✓ ALB: 38390 raw points
    ✓ TSU: 38469 raw points
    ✓ SAR: 38535 raw points
    ✓ MAG: 38544 raw points
    ✓ RIC: 37948 raw points
    ✓ LEC: 38182 raw points
    ✓ BOT: 38194 raw points
    ✓ OCO: 37953 raw points
    ✓ PER: 38006 raw points
    ✓ ZHO: 38280 raw points
    ✓ RUS: 24337 raw points
    ✓ GAS: 726 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 72 track status, 30 messages, 147 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 19 fastest laps, 1 position snapshots
  ✓ Extracted 4 rain event(s)
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2024/12_Silverstone/Race.pkl

  ✓ 12. British Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 13...

core           INFO 	Loading data for Hungarian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '31', '44', '50', '55', '63', '77', '81']

  ✓ Track: 609 points, 4336m
    In-lap: 1054 points
    Out-lap: 977 points
    Clipped: 958 points (from 2031)
  ✓ Pit lane: 958 points, 3626m

core           INFO 	Loading data for Hungarian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 40.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Hungarian Grand Prix
✓ Cached weekend to race_data/2024/13_Budapest/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 13...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '31', '44', '50', '55', '63', '77', '81']

  ✓ Track: 609 points, 4336m
    In-lap: 1054 points
    Out-lap: 977 points
    Clipped: 958 points (from 2031)
  ✓ Pit lane: 958 points, 3626m

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 40.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Hungarian Grand Prix
✓ Cached weekend to race_data/2024/13_Budapest/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Hungarian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R13 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '44', '16', '1', '55', '11', '63', '22', '18', '14', '3', '27', '23', '20', '77', '2', '31', '24', '10']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ PIA: 44755 raw points
    ✓ NOR: 44769 raw points
    ✓ HAM: 44863 raw points
    ✓ LEC: 44902 raw points
    ✓ VER: 44915 raw points
    ✓ SAI: 44928 raw points
    ✓ PER: 45052 raw points
    ✓ RUS: 45075 raw points
    ✓ TSU: 45340 raw points
    ✓ STR: 45346 raw points
    ✓ ALO: 45381 raw points
    ✓ RIC: 44886 raw points
    ✓ HUL: 45001 raw points
    ✓ ALB: 45028 raw points
    ✓ MAG: 45096 raw points
    ✓ BOT: 45096 raw points
    ✓ SAR: 45153 raw points
    ✓ OCO: 45214 raw points
    ✓ ZHO: 45233 raw points
    ✓ GAS: 21694 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 57 track status, 16 messages, 155 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 19 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Belgian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/13_Budapest/Race.pkl

  ✓ 13. Hungarian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 14...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 793 points, 6944m
    In-lap: 1021 points
    Out-lap: 1054 points
    Clipped: 1045 points (from 2075)
  ✓ Pit lane: 1045 points, 4075m

core           INFO 	Loading data for Belgian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data

  ✓ Extracted rotation: 91.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Belgian Grand Prix
✓ Cached weekend to race_data/2024/14_Spa_Francorchamps/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 14...
  → Building circuit data...

core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '77', '81']

  ✓ Track: 793 points, 6944m
    In-lap: 1021 points
    Out-lap: 1054 points
    Clipped: 1045 points (from 2075)
  ✓ Pit lane: 1045 points, 4075m

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '3'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'

  ✓ Extracted rotation: 91.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Belgian Grand Prix
✓ Cached weekend to race_data/2024/14_Spa_Francorchamps/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Belgian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R14 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '81', '16', '1', '4', '55', '11', '14', '31', '3', '18', '23', '10', '20', '77', '22', '2', '27', '24', '63']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ HAM: 36469 raw points
    ✓ PIA: 36474 raw points
    ✓ LEC: 36523 raw points
    ✓ VER: 36528 raw points
    ✓ NOR: 36532 raw points
    ✓ SAI: 36601 raw points
    ✓ PER: 36779 raw points
    ✓ ALO: 36829 raw points
    ✓ OCO: 36846 raw points
    ✓ RIC: 36863 raw points
    ✓ STR: 36922 raw points
    ✓ ALB: 36927 raw points
    ✓ GAS: 36932 raw points
    ✓ MAG: 36950 raw points
    ✓ BOT: 36980 raw points
    ✓ TSU: 37024 raw points
    ✓ SAR: 37094 raw points
    ✓ HUL: 37114 raw points
    ✓ ZHO: 5004 raw points
    ✓ RUS: 36467 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 5 track status, 14 messages, 137 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 18 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2024/14_Spa_Francorchamps/Race.pkl

  ✓ 14. Belgian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 15...

core           INFO 	Loading data for Dutch Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '81', '97']

  ✓ Track: 552 points, 4229m
    In-lap: 836 points
    Out-lap: 695 points
    Clipped: 508 points (from 1531)
  ✓ Pit lane: 508 points, 2571m

core           INFO 	Loading data for Dutch Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data

  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Dutch Grand Prix
✓ Cached weekend to race_data/2024/15_Zandvoort/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 15...
  → Building circuit data...

core           INFO 	Finished loading data for 20 drivers: ['1', '2', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '44', '55', '63', '81', '97']

  ✓ Track: 552 points, 4229m
    In-lap: 836 points
    Out-lap: 695 points
    Clipped: 508 points (from 1531)
  ✓ Pit lane: 508 points, 2571m

core           INFO 	Loading data for Dutch Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Dutch Grand Prix
✓ Cached weekend to race_data/2024/15_Zandvoort/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Dutch Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R15 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '81', '55', '11', '63', '44', '10', '14', '27', '3', '18', '23', '31', '2', '22', '20', '77', '24']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ NOR: 41548 raw points
    ✓ VER: 41719 raw points
    ✓ LEC: 41739 raw points
    ✓ PIA: 41754 raw points
    ✓ SAI: 41796 raw points
    ✓ PER: 41854 raw points
    ✓ RUS: 41892 raw points
    ✓ HAM: 41926 raw points
    ✓ GAS: 41612 raw points
    ✓ ALO: 41650 raw points
    ✓ HUL: 41689 raw points
    ✓ RIC: 41704 raw points
    ✓ STR: 41701 raw points
    ✓ ALB: 41859 raw points
    ✓ OCO: 41906 raw points
    ✓ SAR: 42041 raw points
    ✓ TSU: 42045 raw points
    ✓ MAG: 42050 raw points
    ✓ BOT: 41568 raw points
    ✓ ZHO: 41822 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 67 track status, 13 messages, 153 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 17 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Italian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/15_Zandvoort/Race.pkl

  ✓ 15. Dutch Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 16...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '3', '4', '10', '11', '12', '14', '16', '18', '20', '22', '23', '24', '27', '31', '43', '44', '55', '77', '81']

  ✓ Track: 635 points, 5752m
    In-lap: 6636 points
    Out-lap: 1086 points
    Clipped: 1502 points (from 7722)
  ✓ Pit lane: 1502 points, 2293m

core           INFO 	Loading data for Italian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 95.0°
  ✓ Extracted marshal sectors: 17 sectors
  ✓ Weekend complete: Italian Grand Prix
✓ Cached weekend to race_data/2024/16_Monza/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 16...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '3', '4', '10', '11', '12', '14', '16', '18', '20', '22', '23', '24', '27', '31', '43', '44', '55', '77', '81']

  ✓ Track: 635 points, 5752m
    In-lap: 6636 points
    Out-lap: 1086 points
    Clipped: 1502 points (from 7722)
  ✓ Pit lane: 1502 points, 2293m

core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 95.0°
  ✓ Extracted marshal sectors: 17 sectors
  ✓ Weekend complete: Italian Grand Prix
✓ Cached weekend to race_data/2024/16_Monza/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Italian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R16 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ LEC: 34113 raw points
    ✓ PIA: 34132 raw points
    ✓ NOR: 34155 raw points
    ✓ SAI: 34224 raw points
    ✓ HAM: 34279 raw points
    ✓ VER: 34393 raw points
    ✓ RUS: 34406 raw points
    ✓ PER: 34515 raw points
    ✓ ALB: 34615 raw points
    ✓ MAG: 34546 raw points
    ✓ ALO: 34624 raw points
    ✓ COL: 34714 raw points
    ✓ RIC: 34696 raw points
    ✓ OCO: 34200 raw points
    ✓ GAS: 34243 raw points
    ✓ BOT: 34312 raw points
    ✓ HUL: 34336 raw points
    ✓ ZHO: 34409 raw points
    ✓ STR: 34434 raw points
    ✓ TSU: 4908 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 29 track status, 28 messages, 133 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 31 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2024/16_Monza/Race.pkl

  ✓ 16. Italian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 17...

core           INFO 	Loading data for Azerbaijan Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '3', '4', '10', '11', '14', '16', '18', '22', '23', '24', '27', '31', '43', '44', '50', '55', '63', '77', '81']

  ✓ Track: 823 points, 5941m
    In-lap: 1076 points
    Out-lap: 1076 points
    Clipped: 1140 points (from 2152)
  ✓ Pit lane: 1140 points, 4214m

core           INFO 	Loading data for Azerbaijan Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 357.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Azerbaijan Grand Prix
✓ Cached weekend to race_data/2024/17_Baku/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 17...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '3', '4', '10', '11', '14', '16', '18', '22', '23', '24', '27', '31', '43', '44', '50', '55', '63', '77', '81']

  ✓ Track: 823 points, 5941m
    In-lap: 1076 points
    Out-lap: 1076 points
    Clipped: 1140 points (from 2152)
  ✓ Pit lane: 1140 points, 4214m
  ✓ Extracted rotation: 357.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Azerbaijan Grand Prix
✓ Cached weekend to race_data/2024/17_Baku/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Azerbaijan Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R17 R...

core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '16', '63', '4', '1', '14', '23', '43', '44', '50', '27', '10', '3', '24', '31', '77', '11', '55', '18', '22']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 43045 raw points
    ✓ GAS: 43354 raw points
    ✓ PER: 40634 raw points
    ✓ ALO: 43103 raw points
    ✓ LEC: 42529 raw points
    ✓ STR: 38095 raw points
    ✓ TSU: 12332 raw points
    ✓ ALB: 43119 raw points
    ✓ ZHO: 43599 raw points
    ✓ HUL: 43168 raw points
    ✓ RIC: 43580 raw points
    ✓ OCO: 42611 raw points
    ✓ NOR: 42723 raw points
    ✓ COL: 43136 raw points
    ✓ HAM: 43157 raw points
    ✓ BEA: 43165 raw points
    ✓ SAI: 40661 raw points
    ✓ RUS: 42686 raw points
    ✓ BOT: 42641 raw points
    ✓ PIA: 42445 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 76 track status, 36 messages, 152 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 15 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Singapore Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/17_Baku/Race.pkl

  ✓ 17. Azerbaijan Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 18...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '43', '44', '55', '63', '77', '81']

  ✓ Track: 700 points, 4878m
    In-lap: 901 points
    Out-lap: 982 points
    Clipped: 864 points (from 1883)
  ✓ Pit lane: 864 points, 3286m

core           INFO 	Loading data for Singapore Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data

  ✓ Extracted rotation: 335.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Singapore Grand Prix
✓ Cached weekend to race_data/2024/18_Marina_Bay/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 18...
  → Building circuit data...

core           INFO 	Finished loading data for 20 drivers: ['1', '3', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '31', '43', '44', '55', '63', '77', '81']

  ✓ Track: 700 points, 4878m
    In-lap: 901 points
    Out-lap: 982 points
    Clipped: 864 points (from 1883)
  ✓ Pit lane: 864 points, 3286m

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 335.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Singapore Grand Prix
✓ Cached weekend to race_data/2024/18_Marina_Bay/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Singapore Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R18 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '81', '63', '16', '44', '55', '14', '27', '11', '43', '22', '31', '18', '24', '77', '10', '3', '20', '23']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ NOR: 46206 raw points
    ✓ VER: 46365 raw points
    ✓ PIA: 46534 raw points
    ✓ RUS: 46674 raw points
    ✓ LEC: 46682 raw points
    ✓ HAM: 46848 raw points
    ✓ SAI: 46921 raw points
    ✓ ALO: 46211 raw points
    ✓ HUL: 46226 raw points
    ✓ PER: 46239 raw points
    ✓ COL: 46253 raw points
    ✓ TSU: 46272 raw points
    ✓ OCO: 46548 raw points
    ✓ STR: 46575 raw points
    ✓ ZHO: 46644 raw points
    ✓ BOT: 46652 raw points
    ✓ GAS: 46658 raw points
    ✓ RIC: 46879 raw points
    ✓ MAG: 44389 raw points
    ✓ ALB: 11891 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 35 track status, 24 messages, 160 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 24 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for United States Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/18_Marina_Bay/Race.pkl

  ✓ 18. Singapore Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 19...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '30', '31', '43', '44', '55', '63', '77', '81']

  ✓ Track: 685 points, 5442m
    In-lap: 1083 points
    Out-lap: 1094 points
    Clipped: 1154 points (from 2177)
  ✓ Pit lane: 1154 points, 4633m
  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: United States Grand Prix
✓ Cached weekend to race_data/2024/19_Austin/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 19...
  → Building circuit data...

core           INFO 	Loading data for United States Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '30', '31', '43', '44', '55', '63', '77', '81']

  ✓ Track: 685 points, 5442m
    In-lap: 1083 points
    Out-lap: 1094 points
    Clipped: 1154 points (from 2177)
  ✓ Pit lane: 1154 points, 4633m

core           INFO 	Loading data for United States Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: United States Grand Prix
✓ Cached weekend to race_data/2024/19_Austin/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: United States Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R19 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '1', '4', '81', '63', '11', '27', '30', '43', '20', '10', '14', '22', '18', '23', '77', '31', '24', '44']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 43937 raw points
    ✓ GAS: 44429 raw points
    ✓ PER: 44235 raw points
    ✓ ALO: 43809 raw points
    ✓ LEC: 43799 raw points
    ✓ STR: 43916 raw points
    ✓ MAG: 44384 raw points
    ✓ TSU: 43822 raw points
    ✓ ALB: 43925 raw points
    ✓ ZHO: 44161 raw points
    ✓ HUL: 44263 raw points
    ✓ LAW: 44316 raw points
    ✓ OCO: 44103 raw points
    ✓ NOR: 43904 raw points
    ✓ COL: 44325 raw points
    ✓ HAM: 1545 raw points
    ✓ SAI: 43856 raw points
    ✓ RUS: 44213 raw points
    ✓ BOT: 44050 raw points
    ✓ PIA: 43954 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 42 track status, 72 messages, 155 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 17 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Mexico City Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/19_Austin/Race.pkl

  ✓ 19. United States Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 20...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '10', '11', '12', '18', '20', '22', '23', '27', '29', '30', '31', '34', '38', '43', '55', '63', '77', '81', '97']

  ✓ Track: 604 points, 4243m
    In-lap: 6210 points
    Out-lap: 733 points
    Clipped: 678 points (from 6943)
  ✓ Pit lane: 678 points, 1602m

core           INFO 	Loading data for Mexico City Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 36.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Mexico City Grand Prix
✓ Cached weekend to race_data/2024/20_Mexico_City/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 20...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '10', '11', '12', '18', '20', '22', '23', '27', '29', '30', '31', '34', '38', '43', '55', '63', '77', '81', '97']

  ✓ Track: 604 points, 4243m
    In-lap: 6210 points
    Out-lap: 733 points
    Clipped: 678 points (from 6943)
  ✓ Pit lane: 678 points, 1602m

core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 36.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Mexico City Grand Prix
✓ Cached weekend to race_data/2024/20_Mexico_City/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Mexico City Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R20 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '4', '16', '44', '63', '1', '20', '81', '27', '10', '18', '43', '31', '77', '24', '30', '11', '14', '23', '22']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ SAI: 46145 raw points
    ✓ NOR: 46175 raw points
    ✓ LEC: 46401 raw points
    ✓ HAM: 46477 raw points
    ✓ RUS: 46503 raw points
    ✓ VER: 46585 raw points
    ✓ MAG: 46620 raw points
    ✓ PIA: 46629 raw points
    ✓ HUL: 46166 raw points
    ✓ GAS: 46280 raw points
    ✓ STR: 46330 raw points
    ✓ COL: 46346 raw points
    ✓ OCO: 46438 raw points
    ✓ BOT: 46457 raw points
    ✓ ZHO: 46602 raw points
    ✓ LAW: 46623 raw points
    ✓ PER: 46688 raw points
    ✓ ALO: 11616 raw points
    ✓ ALB: 808 raw points
    ✓ TSU: 808 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 72 track status, 43 messages, 159 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 20 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for São Paulo Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/20_Mexico_City/Race.pkl

  ✓ 20. Mexico City Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 21...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '10', '11', '14', '16', '18', '22', '23', '24', '27', '30', '31', '43', '44', '50', '55', '63', '77', '81']

  ✓ Track: 542 points, 4234m
    In-lap: 926 points
    Out-lap: 690 points
    Clipped: 586 points (from 1616)
  ✓ Pit lane: 586 points, 3694m
  ✓ Extracted rotation: 258.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: São Paulo Grand Prix
✓ Cached weekend to race_data/2024/21_São_Paulo/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 21...

core           INFO 	Loading data for São Paulo Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '10', '11', '14', '16', '18', '22', '23', '24', '27', '30', '31', '43', '44', '50', '55', '63', '77', '81']

  ✓ Track: 542 points, 4234m
    In-lap: 926 points
    Out-lap: 690 points
    Clipped: 586 points (from 1616)
  ✓ Pit lane: 586 points, 3694m

core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 23

  ✓ Extracted rotation: 258.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: São Paulo Grand Prix
✓ Cached weekend to race_data/2024/21_São_Paulo/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: São Paulo Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R21 R...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '31', '10', '63', '16', '4', '22', '81', '30', '44', '11', '50', '77', '14', '24', '55', '43', '23', '18', '27']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 47414 raw points
    ✓ GAS: 47635 raw points
    ✓ PER: 48119 raw points
    ✓ ALO: 48187 raw points
    ✓ LEC: 47769 raw points
    ✓ STR: 695 raw points
    ✓ TSU: 47847 raw points
    ✓ ZHO: 58580 raw points
    ✓ HUL: 22582 raw points
    ✓ LAW: 47990 raw points
    ✓ OCO: 47545 raw points
    ✓ NOR: 47707 raw points
    ✓ COL: 20676 raw points
    ✓ HAM: 48014 raw points
    ✓ BEA: 48188 raw points
    ✓ SAI: 27692 raw points
    ✓ RUS: 47690 raw points
    ✓ BOT: 48153 raw points
    ✓ PIA: 47832 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 19 drivers with all derived fields
  → Events: 43 track status, 58 messages, 201 weather samples
  → Building results with telemetry: 19 drivers, session_time=✓
  → Results: 32 fastest laps, 1 position snapshots
  ✓ Extracted 6 rain event(s)
  ✓ Session complete: 19 drivers, 19 with telemetry

core           INFO 	Loading data for Las Vegas Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/21_São_Paulo/Race.pkl

  ✓ 21. São Paulo Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 22...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '20'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '27'
core        WARNING 	Fixed incorrect tyre stint information for driver '81'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '30', '31', '43', '44', '55', '63', '77', '81']

  ✓ Track: 731 points, 6139m
    In-lap: 837 points
    Out-lap: 862 points
    Clipped: 679 points (from 1699)
  ✓ Pit lane: 679 points, 3812m

core           INFO 	Loading data for Las Vegas Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '20'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '27'
core        WARNING 	Fixed incorrect tyre stint information for driver '81'
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 90.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Las Vegas Grand Prix
✓ Cached weekend to race_data/2024/22_Las_Vegas/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 22...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '30', '31', '43', '44', '55', '63', '77', '81']

  ✓ Track: 731 points, 6139m
    In-lap: 837 points
    Out-lap: 862 points
    Clipped: 679 points (from 1699)
  ✓ Pit lane: 679 points, 3812m

core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 63: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 44: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 55: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 16: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver  1: Lap timing integrity check failed for 1 lap(s)

  ✓ Extracted rotation: 90.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Las Vegas Grand Prix
✓ Cached weekend to race_data/2024/22_Las_Vegas/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Las Vegas Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R22 R...

core        WARNING 	Driver  4: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 81: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 30: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 77: Lap timing integrity check failed for 2 lap(s)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 63 completed the race distance 00:00.427000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '1', '4', '81', '27', '22', '11', '14', '20', '24', '43', '18', '30', '31', '77', '23', '10']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ RUS: 37514 raw points
    ✓ HAM: 37566 raw points
    ✓ SAI: 37605 raw points
    ✓ LEC: 37621 raw points
    ✓ VER: 37641 raw points
    ✓ NOR: 37850 raw points
    ✓ PIA: 37914 raw points
    ✓ HUL: 37969 raw points
    ✓ TSU: 37996 raw points
    ✓ PER: 37998 raw points
    ✓ ALO: 38047 raw points
    ✓ MAG: 38052 raw points
    ✓ ZHO: 38085 raw points
    ✓ COL: 38091 raw points
    ✓ STR: 38162 raw points
    ✓ LAW: 38220 raw points
    ✓ OCO: 37529 raw points
    ✓ BOT: 37597 raw points
    ✓ ALB: 19250 raw points
    ✓ GAS: 11712 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 10 track status, 23 messages, 143 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 27 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2024/22_Las_Vegas/Race.pkl

  ✓ 22. Las Vegas Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 23...

core           INFO 	Loading data for Qatar Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '30', '31', '43', '44', '55', '63', '77', '81']

  ✓ Track: 632 points, 5380m
    In-lap: 952 points
    Out-lap: 755 points
    Clipped: 707 points (from 1707)
  ✓ Pit lane: 707 points, 4636m

core           INFO 	Loading data for Qatar Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 61.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Qatar Grand Prix
✓ Cached weekend to race_data/2024/23_Lusail/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 23...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '10', '11', '14', '16', '18', '20', '22', '23', '24', '27', '30', '31', '43', '44', '55', '63', '77', '81']

  ✓ Track: 632 points, 5380m
    In-lap: 952 points
    Out-lap: 755 points
    Clipped: 707 points (from 1707)
  ✓ Pit lane: 707 points, 4636m

core           INFO 	Loading data for Qatar Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '43'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'

  ✓ Extracted rotation: 61.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Qatar Grand Prix
✓ Cached weekend to race_data/2024/23_Lusail/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Qatar Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R23 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '81', '63', '10', '55', '14', '24', '20', '4', '77', '44', '22', '30', '23', '27', '11', '18', '43', '31']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 41688 raw points
    ✓ GAS: 41824 raw points
    ✓ PER: 29617 raw points
    ✓ ALO: 41848 raw points
    ✓ LEC: 41735 raw points
    ✓ STR: 7420 raw points
    ✓ MAG: 41939 raw points
    ✓ TSU: 42160 raw points
    ✓ ALB: 41792 raw points
    ✓ ZHO: 41891 raw points
    ✓ HUL: 29725 raw points
    ✓ LAW: 42170 raw points
    ✓ OCO: 838 raw points
    ✓ NOR: 41965 raw points
    ✓ COL: 838 raw points
    ✓ HAM: 42122 raw points
    ✓ SAI: 41830 raw points
    ✓ RUS: 41761 raw points
    ✓ BOT: 42075 raw points
    ✓ PIA: 41744 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 30 track status, 72 messages, 151 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 34 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Abu Dhabi Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/23_Lusail/Race.pkl

  ✓ 23. Qatar Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 24...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['4', '10', '11', '14', '16', '20', '24', '27', '28', '30', '34', '37', '39', '40', '43', '44', '46', '61', '63', '77']

  ✓ Track: 665 points, 5222m
    In-lap: 1019 points
    Out-lap: 932 points
    Clipped: 945 points (from 1951)
  ✓ Pit lane: 945 points, 3923m

core           INFO 	Loading data for Abu Dhabi Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 280.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Abu Dhabi Grand Prix
✓ Cached weekend to race_data/2024/24_Yas_Island/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2024 Round 24...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['4', '10', '11', '14', '16', '20', '24', '27', '28', '30', '34', '37', '39', '40', '43', '44', '46', '61', '63', '77']

  ✓ Track: 665 points, 5222m
    In-lap: 1019 points
    Out-lap: 932 points
    Clipped: 945 points (from 1951)
  ✓ Pit lane: 945 points, 3923m

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 280.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Abu Dhabi Grand Prix
✓ Cached weekend to race_data/2024/24_Yas_Island/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Abu Dhabi Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2024 R24 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '55', '16', '44', '63', '1', '10', '27', '14', '81', '23', '22', '24', '18', '61', '20', '30', '77', '43', '11']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 40001 raw points
    ✓ GAS: 40176 raw points
    ✓ PER: 698 raw points
    ✓ ALO: 40253 raw points
    ✓ LEC: 39863 raw points
    ✓ STR: 39719 raw points
    ✓ MAG: 40212 raw points
    ✓ TSU: 39731 raw points
    ✓ ALB: 39704 raw points
    ✓ ZHO: 39746 raw points
    ✓ HUL: 40199 raw points
    ✓ LAW: 39084 raw points
    ✓ NOR: 39623 raw points
    ✓ COL: 18726 raw points
    ✓ HAM: 39899 raw points
    ✓ SAI: 39666 raw points
    ✓ DOO: 39822 raw points
    ✓ RUS: 39909 raw points
    ✓ BOT: 21638 raw points
    ✓ PIA: 40266 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 63 track status, 63 messages, 148 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 14 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Australian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2024/24_Yas_Island/Race.pkl

  ✓ 24. Abu Dhabi Grand Prix

✓ Processed 24/25 races successfully
⚠️  1 races failed to process

📅 Processing 2025 season (25 rounds)...
⚠️  Force updating all races from FastF1
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 0...
✗ Error fetching 2025 R0 event: Cannot get testing event by round number!
  ✗  0. Pre-Season Testing: Failed to load weekend data
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 1...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']

  ✓ Track: 587 points, 5229m
    In-lap: 6599 points
    Out-lap: 809 points
    Clipped: 739 points (from 7408)
  ✓ Pit lane: 739 points, 2059m

core           INFO 	Loading data for Australian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 44.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Australian Grand Prix
✓ Cached weekend to race_data/2025/01_Melbourne/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 1...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']

  ✓ Track: 587 points, 5229m
    In-lap: 6599 points
    Out-lap: 809 points
    Clipped: 739 points (from 7408)
  ✓ Pit lane: 739 points, 2059m

core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'

  ✓ Extracted rotation: 44.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Australian Grand Prix
✓ Cached weekend to race_data/2025/01_Melbourne/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Australian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R1 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 46237 raw points
    ✓ GAS: 46422 raw points
    ✓ ANT: 46301 raw points
    ✓ ALO: 25574 raw points
    ✓ LEC: 46369 raw points
    ✓ STR: 46354 raw points
    ✓ TSU: 46449 raw points
    ✓ ALB: 46321 raw points
    ✓ HUL: 46359 raw points
    ✓ LAW: 37338 raw points
    ✓ OCO: 46475 raw points
    ✓ NOR: 46229 raw points
    ✓ HAM: 46390 raw points
    ✓ BOR: 37276 raw points
    ✓ SAI: 862 raw points
    ✓ HAD: 862 raw points
    ✓ RUS: 46288 raw points
    ✓ DOO: 862 raw points
    ✓ PIA: 46375 raw points
    ✓ BEA: 46529 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 57 track status, 45 messages, 178 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 37 fastest laps, 1 position snapshots
  ✓ Extracted 9 rain event(s)
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/01_Melbourne/Race.pkl

  ✓  1. Australian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 2...
  → Building circuit data...

core           INFO 	Loading data for Chinese Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']

  ✓ Track: 689 points, 5399m
    In-lap: 889 points
    Out-lap: 1000 points
    Clipped: 879 points (from 1889)
  ✓ Pit lane: 879 points, 4059m

core           INFO 	Loading data for Chinese Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 237.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Chinese Grand Prix
✓ Cached weekend to race_data/2025/02_Shanghai/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 2...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']

  ✓ Track: 689 points, 5399m
    In-lap: 889 points
    Out-lap: 1000 points
    Clipped: 879 points (from 1889)
  ✓ Pit lane: 879 points, 4059m

core           INFO 	Loading data for Chinese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 237.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Chinese Grand Prix
✓ Cached weekend to race_data/2025/02_Shanghai/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Chinese Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R2 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ PIA: 40955 raw points
    ✓ NOR: 41029 raw points
    ✓ RUS: 41040 raw points
    ✓ VER: 41081 raw points
    ✓ OCO: 41342 raw points
    ✓ ANT: 41368 raw points
    ✓ ALB: 41387 raw points
    ✓ BEA: 41426 raw points
    ✓ STR: 41492 raw points
    ✓ SAI: 41532 raw points
    ✓ HAD: 41551 raw points
    ✓ LAW: 41568 raw points
    ✓ DOO: 41547 raw points
    ✓ BOR: 41036 raw points
    ✓ HUL: 41108 raw points
    ✓ TSU: 41134 raw points
    ✓ ALO: 3351 raw points
    ✓ LEC: 41133 raw points
    ✓ HAM: 41150 raw points
    ✓ GAS: 41472 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 31 track status, 23 messages, 154 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 11 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Japanese Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2025/02_Shanghai/Race.pkl

  ✓  2. Chinese Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 3...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '62', '63', '81', '87']

  ✓ Track: 665 points, 5775m
    In-lap: 1162 points
    Out-lap: 997 points
    Clipped: 1108 points (from 2159)
  ✓ Pit lane: 1108 points, 4188m

core           INFO 	Loading data for Japanese Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 49.0°
  ✓ Extracted marshal sectors: 22 sectors
  ✓ Weekend complete: Japanese Grand Prix
✓ Cached weekend to race_data/2025/03_Suzuka/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 3...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '62', '63', '81', '87']

  ✓ Track: 665 points, 5775m
    In-lap: 1162 points
    Out-lap: 997 points
    Clipped: 1108 points (from 2159)
  ✓ Pit lane: 1108 points, 4188m

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 49.0°
  ✓ Extracted marshal sectors: 22 sectors
  ✓ Weekend complete: Japanese Grand Prix
✓ Cached weekend to race_data/2025/03_Suzuka/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Japanese Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R3 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '44', '6', '23', '87', '14', '22', '10', '55', '7', '27', '30', '31', '5', '18']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 37156 raw points
    ✓ NOR: 37167 raw points
    ✓ PIA: 37172 raw points
    ✓ LEC: 37274 raw points
    ✓ RUS: 37283 raw points
    ✓ ANT: 37295 raw points
    ✓ HAM: 37366 raw points
    ✓ HAD: 37426 raw points
    ✓ ALB: 37450 raw points
    ✓ BEA: 37552 raw points
    ✓ ALO: 37574 raw points
    ✓ TSU: 37582 raw points
    ✓ GAS: 37612 raw points
    ✓ SAI: 37701 raw points
    ✓ DOO: 37757 raw points
    ✓ HUL: 37761 raw points
    ✓ LAW: 37765 raw points
    ✓ OCO: 37771 raw points
    ✓ BOR: 37776 raw points
    ✓ STR: 37246 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 5 track status, 16 messages, 140 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 26 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/03_Suzuka/Race.pkl

  ✓  3. Japanese Grand Prix

core           INFO 	Loading data for Bahrain Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 4...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['4', '5', '6', '7', '10', '12', '18', '22', '23', '27', '30', '31', '34', '37', '38', '44', '46', '50', '72', '81']

  ✓ Track: 698 points, 5359m
    In-lap: 970 points
    Out-lap: 1262 points
    Clipped: 1073 points (from 2232)
  ✓ Pit lane: 1073 points, 4313m

core           INFO 	Loading data for Bahrain Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 92.0°
  ✓ Extracted marshal sectors: 18 sectors
  ✓ Weekend complete: Bahrain Grand Prix
✓ Cached weekend to race_data/2025/04_Sakhir/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 4...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['4', '5', '6', '7', '10', '12', '18', '22', '23', '27', '30', '31', '34', '37', '38', '44', '46', '50', '72', '81']

  ✓ Track: 698 points, 5359m
    In-lap: 970 points
    Out-lap: 1262 points
    Clipped: 1073 points (from 2232)
  ✓ Pit lane: 1073 points, 4313m

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 92.0°
  ✓ Extracted marshal sectors: 18 sectors
  ✓ Weekend complete: Bahrain Grand Prix
✓ Cached weekend to race_data/2025/04_Sakhir/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Bahrain Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R4 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '16', '44', '1', '10', '31', '22', '87', '12', '23', '6', '7', '14', '30', '18', '5', '55', '27']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ PIA: 43331 raw points
    ✓ RUS: 43444 raw points
    ✓ NOR: 43449 raw points
    ✓ LEC: 43473 raw points
    ✓ HAM: 43536 raw points
    ✓ VER: 43581 raw points
    ✓ GAS: 43594 raw points
    ✓ OCO: 43650 raw points
    ✓ TSU: 43654 raw points
    ✓ BEA: 43672 raw points
    ✓ ANT: 43676 raw points
    ✓ ALB: 43681 raw points
    ✓ HAD: 43728 raw points
    ✓ DOO: 43702 raw points
    ✓ ALO: 43757 raw points
    ✓ LAW: 43681 raw points
    ✓ STR: 43795 raw points
    ✓ BOR: 43806 raw points
    ✓ SAI: 35194 raw points
    ✓ HUL: 43708 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 17 track status, 69 messages, 158 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 10 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Saudi Arabian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2025/04_Sakhir/Race.pkl

  ✓  4. Bahrain Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 5...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']

  ✓ Track: 659 points, 6110m
    In-lap: 859 points
    Out-lap: 1079 points
    Clipped: 840 points (from 1938)
  ✓ Pit lane: 840 points, 23925m

core           INFO 	Loading data for Saudi Arabian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 104.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Saudi Arabian Grand Prix
✓ Cached weekend to race_data/2025/05_Jeddah/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 5...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']

  ✓ Track: 659 points, 6110m
    In-lap: 859 points
    Out-lap: 1079 points
    Clipped: 840 points (from 1938)
  ✓ Pit lane: 840 points, 23925m

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 104.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Saudi Arabian Grand Prix
✓ Cached weekend to race_data/2025/05_Jeddah/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Saudi Arabian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R5 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '16', '4', '63', '12', '44', '55', '23', '6', '14', '30', '87', '31', '27', '18', '7', '5', '22', '10']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ PIA: 36802 raw points
    ✓ VER: 36825 raw points
    ✓ LEC: 36865 raw points
    ✓ NOR: 36874 raw points
    ✓ RUS: 37016 raw points
    ✓ ANT: 37073 raw points
    ✓ HAM: 37106 raw points
    ✓ SAI: 37296 raw points
    ✓ ALB: 37311 raw points
    ✓ HAD: 37314 raw points
    ✓ ALO: 37383 raw points
    ✓ LAW: 37324 raw points
    ✓ BEA: 37407 raw points
    ✓ OCO: 37561 raw points
    ✓ HUL: 36838 raw points
    ✓ STR: 36844 raw points
    ✓ DOO: 36954 raw points
    ✓ BOR: 36954 raw points
    ✓ TSU: 1269 raw points
    ✓ GAS: 940 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...

core           INFO 	Loading data for Miami Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 31 track status, 30 messages, 142 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 15 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/05_Jeddah/Race.pkl

  ✓  5. Saudi Arabian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 6...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']

  ✓ Track: 675 points, 5341m
    In-lap: 1181 points
    Out-lap: 931 points
    Clipped: 1038 points (from 2112)
  ✓ Pit lane: 1038 points, 3463m

core           INFO 	Loading data for Miami Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 2.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Miami Grand Prix
✓ Cached weekend to race_data/2025/06_Miami_Gardens/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 6...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']

  ✓ Track: 675 points, 5341m
    In-lap: 1181 points
    Out-lap: 931 points
    Clipped: 1038 points (from 2112)
  ✓ Pit lane: 1038 points, 3463m

core           INFO 	Loading data for Miami Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '6'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'

  ✓ Extracted rotation: 2.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Miami Grand Prix
✓ Cached weekend to race_data/2025/06_Miami_Gardens/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Miami Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R6 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 81 completed the race distance 00:00.036000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '23', '12', '16', '44', '55', '22', '6', '31', '10', '27', '14', '18', '30', '5', '87', '7']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 40553 raw points
    ✓ GAS: 40928 raw points
    ✓ ANT: 40669 raw points
    ✓ ALO: 40413 raw points
    ✓ LEC: 40681 raw points
    ✓ STR: 40441 raw points
    ✓ TSU: 40769 raw points
    ✓ ALB: 40615 raw points
    ✓ HUL: 40258 raw points
    ✓ LAW: 26732 raw points
    ✓ OCO: 40862 raw points
    ✓ NOR: 40288 raw points
    ✓ HAM: 40704 raw points
    ✓ BOR: 22970 raw points
    ✓ SAI: 40706 raw points
    ✓ HAD: 40807 raw points
    ✓ RUS: 40536 raw points
    ✓ DOO: 725 raw points
    ✓ PIA: 40253 raw points
    ✓ BEA: 20059 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 40 track status, 27 messages, 149 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 20 fastest laps, 1 position snapshots
  ✓ Extracted 2 rain event(s)
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/06_Miami_Gardens/Race.pkl

  ✓  6. Miami Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 7...
  → Building circuit data...

core           INFO 	Loading data for Emilia Romagna Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 585 points, 4879m
    In-lap: 1014 points
    Out-lap: 1042 points
    Clipped: 1046 points (from 2056)
  ✓ Pit lane: 1046 points, 4803m

core           INFO 	Loading data for Emilia Romagna Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Emilia Romagna Grand Prix
✓ Cached weekend to race_data/2025/07_Imola/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 7...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 585 points, 4879m
    In-lap: 1014 points
    Out-lap: 1042 points
    Clipped: 1046 points (from 2056)
  ✓ Pit lane: 1046 points, 4803m

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Emilia Romagna Grand Prix
✓ Cached weekend to race_data/2025/07_Imola/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Emilia Romagna Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R7 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '44', '23', '16', '63', '55', '6', '22', '14', '27', '10', '30', '18', '43', '87', '5', '12', '31']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 41325 raw points
    ✓ GAS: 41568 raw points
    ✓ ANT: 28136 raw points
    ✓ ALO: 41539 raw points
    ✓ LEC: 41486 raw points
    ✓ STR: 41579 raw points
    ✓ TSU: 41533 raw points
    ✓ ALB: 41467 raw points
    ✓ HUL: 41562 raw points
    ✓ LAW: 41575 raw points
    ✓ OCO: 17356 raw points
    ✓ NOR: 41371 raw points
    ✓ COL: 41582 raw points
    ✓ HAM: 41438 raw points
    ✓ BOR: 41619 raw points
    ✓ SAI: 41503 raw points
    ✓ HAD: 41510 raw points
    ✓ RUS: 41496 raw points
    ✓ PIA: 41427 raw points
    ✓ BEA: 41586 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 20 track status, 16 messages, 150 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 17 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Monaco Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2025/07_Imola/Race.pkl

  ✓  7. Emilia Romagna Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 8...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 548 points, 3285m
    In-lap: 3129 points
    Out-lap: 771 points
    Clipped: 737 points (from 3900)
  ✓ Pit lane: 737 points, 1281m

core           INFO 	Loading data for Monaco Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 315.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Monaco Grand Prix
✓ Cached weekend to race_data/2025/08_Monaco/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 8...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 548 points, 3285m
    In-lap: 3129 points
    Out-lap: 771 points
    Clipped: 737 points (from 3900)
  ✓ Pit lane: 737 points, 1281m

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 315.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Monaco Grand Prix
✓ Cached weekend to race_data/2025/08_Monaco/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Monaco Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R8 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 45499 raw points
    ✓ GAS: 5649 raw points
    ✓ ANT: 45398 raw points
    ✓ ALO: 22348 raw points
    ✓ LEC: 45366 raw points
    ✓ STR: 45873 raw points
    ✓ TSU: 45884 raw points
    ✓ ALB: 45432 raw points
    ✓ HUL: 45883 raw points
    ✓ LAW: 45849 raw points
    ✓ OCO: 45842 raw points
    ✓ NOR: 45343 raw points
    ✓ COL: 45775 raw points
    ✓ HAM: 45734 raw points
    ✓ BOR: 45859 raw points
    ✓ SAI: 45454 raw points
    ✓ HAD: 45836 raw points
    ✓ RUS: 45595 raw points
    ✓ PIA: 45364 raw points
    ✓ BEA: 45755 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 162 track status, 30 messages, 160 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 15 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/08_Monaco/Race.pkl

  ✓  8. Monaco Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 9...

core           INFO 	Loading data for Spanish Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '27', '30', '43', '44', '45', '50', '55', '63', '81', '87']

  ✓ Track: 551 points, 4625m
    In-lap: 1077 points
    Out-lap: 715 points
    Clipped: 789 points (from 1792)
  ✓ Pit lane: 789 points, 3569m

core           INFO 	Loading data for Spanish Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 303.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Spanish Grand Prix
✓ Cached weekend to race_data/2025/09_Barcelona/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 9...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '27', '30', '43', '44', '45', '50', '55', '63', '81', '87']

  ✓ Track: 551 points, 4625m
    In-lap: 1077 points
    Out-lap: 715 points
    Clipped: 789 points (from 1792)
  ✓ Pit lane: 789 points, 3569m

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 303.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Spanish Grand Prix
✓ Cached weekend to race_data/2025/09_Barcelona/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Spanish Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R9 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['81', '4', '16', '63', '27', '44', '6', '10', '14', '1', '30', '5', '22', '55', '43', '31', '87', '12', '23']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 42230 raw points
    ✓ GAS: 42283 raw points
    ✓ ANT: 33364 raw points
    ✓ ALO: 42305 raw points
    ✓ LEC: 42221 raw points
    ✓ TSU: 42363 raw points
    ✓ ALB: 17378 raw points
    ✓ HUL: 42247 raw points
    ✓ LAW: 42340 raw points
    ✓ OCO: 42389 raw points
    ✓ NOR: 42158 raw points
    ✓ COL: 42383 raw points
    ✓ HAM: 42263 raw points
    ✓ BOR: 42342 raw points
    ✓ SAI: 42366 raw points
    ✓ HAD: 42266 raw points
    ✓ RUS: 42228 raw points
    ✓ PIA: 42140 raw points
    ✓ BEA: 42350 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 19 drivers with all derived fields
  → Events: 53 track status, 42 messages, 155 weather samples
  → Building results with telemetry: 19 drivers, session_time=✓
  → Results: 11 fastest laps, 1 position snapshots
  ✓ Session complete: 19 drivers, 19 with telemetry

core           INFO 	Loading data for Canadian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2025/09_Barcelona/Race.pkl

  ✓  9. Spanish Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 10...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 557 points, 4325m
    In-lap: 4902 points
    Out-lap: 722 points
    Clipped: 667 points (from 5624)
  ✓ Pit lane: 667 points, 1282m

core           INFO 	Loading data for Canadian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 62.0°
  ✓ Extracted marshal sectors: 15 sectors
  ✓ Weekend complete: Canadian Grand Prix
✓ Cached weekend to race_data/2025/10_Montréal/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 10...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 557 points, 4325m
    In-lap: 4902 points
    Out-lap: 722 points
    Clipped: 667 points (from 5624)
  ✓ Pit lane: 667 points, 1282m

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 62.0°
  ✓ Extracted marshal sectors: 15 sectors
  ✓ Weekend complete: Canadian Grand Prix
✓ Cached weekend to race_data/2025/10_Montréal/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Canadian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R10 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '12', '81', '16', '44', '14', '27', '31', '55', '87', '22', '43', '5', '10', '6', '18', '4', '30', '23']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 41520 raw points
    ✓ GAS: 41570 raw points
    ✓ ANT: 41522 raw points
    ✓ ALO: 41596 raw points
    ✓ LEC: 41540 raw points
    ✓ STR: 41579 raw points
    ✓ TSU: 41555 raw points
    ✓ ALB: 27665 raw points
    ✓ HUL: 41630 raw points
    ✓ LAW: 31921 raw points
    ✓ OCO: 41524 raw points
    ✓ NOR: 37977 raw points
    ✓ COL: 41566 raw points
    ✓ HAM: 41594 raw points
    ✓ BOR: 41572 raw points
    ✓ SAI: 41527 raw points
    ✓ HAD: 41576 raw points
    ✓ RUS: 41519 raw points
    ✓ PIA: 41531 raw points
    ✓ BEA: 41541 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 59 track status, 35 messages, 167 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 23 fastest laps, 1 position snapshots
  ✓ Extracted 1 rain event(s)
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/10_Montréal/Race.pkl

  ✓ 10. Canadian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 11...
  → Building circuit data...

core           INFO 	Loading data for Austrian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '5', '6', '10', '12', '14', '18', '22', '23', '27', '30', '31', '38', '43', '44', '55', '63', '81', '87', '89']

  ✓ Track: 494 points, 4296m
    In-lap: 811 points
    Out-lap: 863 points
    Clipped: 640 points (from 1674)
  ✓ Pit lane: 640 points, 3251m

core           INFO 	Loading data for Austrian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 1.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Austrian Grand Prix
✓ Cached weekend to race_data/2025/11_Spielberg/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 11...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '5', '6', '10', '12', '14', '18', '22', '23', '27', '30', '31', '38', '43', '44', '55', '63', '81', '87', '89']

  ✓ Track: 494 points, 4296m
    In-lap: 811 points
    Out-lap: 863 points
    Clipped: 640 points (from 1674)
  ✓ Pit lane: 640 points, 3251m

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 1.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Austrian Grand Prix
✓ Cached weekend to race_data/2025/11_Spielberg/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Austrian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R11 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '16', '44', '63', '30', '14', '5', '27', '31', '87', '6', '10', '18', '43', '22', '23', '1', '12', '55']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ NOR: 38173 raw points
    ✓ PIA: 38191 raw points
    ✓ LEC: 38315 raw points
    ✓ HAM: 38385 raw points
    ✓ RUS: 38642 raw points
    ✓ LAW: 38679 raw points
    ✓ ALO: 38179 raw points
    ✓ BOR: 38183 raw points
    ✓ HUL: 38227 raw points
    ✓ OCO: 38245 raw points
    ✓ BEA: 38352 raw points
    ✓ HAD: 38375 raw points
    ✓ GAS: 38417 raw points
    ✓ STR: 38427 raw points
    ✓ COL: 38451 raw points
    ✓ TSU: 38188 raw points
    ✓ ALB: 9092 raw points
    ✓ VER: 659 raw points
    ✓ ANT: 659 raw points
    ✓ SAI: 659 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 67 track status, 46 messages, 161 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 16 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/11_Spielberg/Race.pkl

  ✓ 11. Austrian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 12...
  → Building circuit data...

core           INFO 	Loading data for British Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '23', '30', '31', '36', '43', '44', '55', '63', '81', '87', '97']

  ✓ Track: 662 points, 5818m
    In-lap: 852 points
    Out-lap: 909 points
    Clipped: 754 points (from 1761)
  ✓ Pit lane: 754 points, 4317m

core           INFO 	Loading data for British Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 92.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: British Grand Prix
✓ Cached weekend to race_data/2025/12_Silverstone/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 12...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '23', '30', '31', '36', '43', '44', '55', '63', '81', '87', '97']

  ✓ Track: 662 points, 5818m
    In-lap: 852 points
    Out-lap: 909 points
    Clipped: 754 points (from 1761)
  ✓ Pit lane: 754 points, 4317m

core           INFO 	Loading data for British Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 92.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: British Grand Prix
✓ Cached weekend to race_data/2025/12_Silverstone/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: British Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R12 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '27', '44', '1', '10', '18', '23', '14', '63', '87', '55', '31', '16', '22', '12', '6', '5', '30', '43']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 44322 raw points
    ✓ GAS: 44350 raw points
    ✓ ANT: 22578 raw points
    ✓ ALO: 44391 raw points
    ✓ LEC: 44531 raw points
    ✓ STR: 44353 raw points
    ✓ TSU: 44126 raw points
    ✓ ALB: 44378 raw points
    ✓ HUL: 44146 raw points
    ✓ LAW: 804 raw points
    ✓ OCO: 44478 raw points
    ✓ NOR: 43886 raw points
    ✓ COL: 804 raw points
    ✓ HAM: 44188 raw points
    ✓ BOR: 3145 raw points
    ✓ SAI: 44471 raw points
    ✓ HAD: 16774 raw points
    ✓ RUS: 44427 raw points
    ✓ PIA: 43938 raw points
    ✓ BEA: 44438 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 89 track status, 57 messages, 155 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 24 fastest laps, 1 position snapshots
  ✓ Extracted 2 rain event(s)
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Belgian Grand Prix - Practice 1 [v3.7.0]

✓ Cached session to race_data/2025/12_Silverstone/Race.pkl

  ✓ 12. British Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 13...
  → Building circuit data...

req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 776 points, 6949m
    In-lap: 1065 points
    Out-lap: 1047 points
    Clipped: 1054 points (from 2112)
  ✓ Pit lane: 1054 points, 4090m

core           INFO 	Loading data for Belgian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 91.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Belgian Grand Prix
✓ Cached weekend to race_data/2025/13_Spa_Francorchamps/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 13...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 776 points, 6949m
    In-lap: 1065 points
    Out-lap: 1047 points
    Clipped: 1054 points (from 2112)
  ✓ Pit lane: 1054 points, 4090m

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '81'
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
core        WARNING 	Fixed incorrect tyre stint information for driver '1'
core        WARNING 	Fixed incorrect tyre stint information for driver '63'
core        WARNING 	Fixed incorrect tyre stint information for driver '23'
core        WARNING 	Fixed incorrect tyre stint information for driver '44'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
core        WARNING 	Fixed incorrect tyre stint information for driver '10'
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '27'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '55'
core        WARNING 	Fixed incorrect tyre stint information for driver '43'
core        WARNING 	Fixed incorrect tyre stint information for driver '6'

  ✓ Extracted rotation: 91.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Belgian Grand Prix
✓ Cached weekend to race_data/2025/13_Spa_Francorchamps/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Belgian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R13 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '16', '1', '63', '23', '44', '30', '5', '10', '87', '27', '22', '18', '31', '12', '14', '55', '43', '6']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ PIA: 38611 raw points
    ✓ NOR: 38638 raw points
    ✓ LEC: 38761 raw points
    ✓ VER: 38769 raw points
    ✓ RUS: 38867 raw points
    ✓ ALB: 38905 raw points
    ✓ HAM: 38912 raw points
    ✓ LAW: 38993 raw points
    ✓ BOR: 39025 raw points
    ✓ GAS: 39152 raw points
    ✓ BEA: 39154 raw points
    ✓ HUL: 39157 raw points
    ✓ TSU: 39171 raw points
    ✓ STR: 39200 raw points
    ✓ OCO: 39242 raw points
    ✓ ANT: 39247 raw points
    ✓ ALO: 39255 raw points
    ✓ SAI: 39290 raw points
    ✓ COL: 39313 raw points
    ✓ HAD: 38709 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 76 track status, 38 messages, 223 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 24 fastest laps, 1 position snapshots
  ✓ Extracted 6 rain event(s)
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Hungarian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2025/13_Spa_Francorchamps/Race.pkl

  ✓ 13. Belgian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 14...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '16', '18', '22', '23', '30', '31', '34', '43', '44', '55', '63', '81', '87', '97']

  ✓ Track: 575 points, 4339m
    In-lap: 1134 points
    Out-lap: 979 points
    Clipped: 1051 points (from 2113)
  ✓ Pit lane: 1051 points, 3655m

core           INFO 	Loading data for Hungarian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 40.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Hungarian Grand Prix
✓ Cached weekend to race_data/2025/14_Budapest/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 14...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '16', '18', '22', '23', '30', '31', '34', '43', '44', '55', '63', '81', '87', '97']

  ✓ Track: 575 points, 4339m
    In-lap: 1134 points
    Out-lap: 979 points
    Clipped: 1051 points (from 2113)
  ✓ Pit lane: 1051 points, 3655m

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 40.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Hungarian Grand Prix
✓ Cached weekend to race_data/2025/14_Budapest/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Hungarian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R14 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '63', '16', '14', '5', '18', '30', '1', '12', '6', '44', '27', '55', '23', '31', '22', '43', '10', '87']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ NOR: 43223 raw points
    ✓ PIA: 43229 raw points
    ✓ RUS: 43376 raw points
    ✓ LEC: 43494 raw points
    ✓ ALO: 43655 raw points
    ✓ BOR: 43708 raw points
    ✓ STR: 43722 raw points
    ✓ LAW: 43730 raw points
    ✓ VER: 43753 raw points
    ✓ ANT: 43276 raw points
    ✓ HAD: 43283 raw points
    ✓ HAM: 43292 raw points
    ✓ HUL: 43447 raw points
    ✓ SAI: 43462 raw points
    ✓ ALB: 43496 raw points
    ✓ OCO: 43548 raw points
    ✓ TSU: 43562 raw points
    ✓ COL: 43566 raw points
    ✓ GAS: 43558 raw points
    ✓ BEA: 30521 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 48 track status, 46 messages, 157 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 23 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/14_Budapest/Race.pkl

  ✓ 14. Hungarian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 15...
  → Building circuit data...

core           INFO 	Loading data for Dutch Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 535 points, 4230m
    In-lap: 4611 points
    Out-lap: 688 points
    Clipped: 865 points (from 5299)
  ✓ Pit lane: 865 points, 1435m

core           INFO 	Loading data for Dutch Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Dutch Grand Prix
✓ Cached weekend to race_data/2025/15_Zandvoort/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 15...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 535 points, 4230m
    In-lap: 4611 points
    Out-lap: 688 points
    Clipped: 865 points (from 5299)
  ✓ Pit lane: 865 points, 1435m

core           INFO 	Loading data for Dutch Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 19 sectors
  ✓ Weekend complete: Dutch Grand Prix
✓ Cached weekend to race_data/2025/15_Zandvoort/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Dutch Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R15 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '1', '6', '63', '23', '87', '18', '14', '22', '31', '43', '30', '55', '27', '5', '12', '10', '4', '16', '44']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 44305 raw points
    ✓ GAS: 44463 raw points
    ✓ ANT: 44348 raw points
    ✓ ALO: 44379 raw points
    ✓ LEC: 30685 raw points
    ✓ STR: 44365 raw points
    ✓ TSU: 44392 raw points
    ✓ ALB: 44341 raw points
    ✓ HUL: 44434 raw points
    ✓ LAW: 44417 raw points
    ✓ OCO: 44396 raw points
    ✓ NOR: 39086 raw points
    ✓ COL: 44399 raw points
    ✓ HAM: 12838 raw points
    ✓ BOR: 44449 raw points
    ✓ SAI: 44419 raw points
    ✓ HAD: 44319 raw points
    ✓ RUS: 44337 raw points
    ✓ PIA: 44293 raw points
    ✓ BEA: 44360 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 51 track status, 43 messages, 159 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 22 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Italian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2025/15_Zandvoort/Race.pkl

  ✓ 15. Dutch Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 16...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 3
core        WARNING 	No lap data for driver 7
core        WARNING 	No lap data for driver 9
core        WARNING 	No lap data for driver 11
core        WARNING 	No lap data for driver 15
core        WARNING 	No lap data for driver 17
core        WARNING 	No lap data for driver 19
core        WARNING 	No lap data for driver 21
core        WARNING 	No lap data for driver 25
core        WARNING 	No lap data for driver 29
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 3)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 7)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 9)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 11)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 15)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 17)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 19)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 21)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 25)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 29)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 30 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '61', '63', '87', '89', '3', '7', '9', '11', '15', '17', '19', '21', '25', '29']

  ✓ Track: 588 points, 5758m
    In-lap: 822 points
    Out-lap: 858 points
    Clipped: 582 points (from 1680)
  ✓ Pit lane: 582 points, 3909m

core           INFO 	Loading data for Italian Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 3
core        WARNING 	No lap data for driver 7
core        WARNING 	No lap data for driver 9
core        WARNING 	No lap data for driver 11
core        WARNING 	No lap data for driver 15
core        WARNING 	No lap data for driver 17
core        WARNING 	No lap data for driver 19
core        WARNING 	No lap data for driver 21
core        WARNING 	No lap data for driver 25
core        WARNING 	No lap data for driver 29

  ✓ Extracted rotation: 95.0°
  ✓ Extracted marshal sectors: 17 sectors
  ✓ Weekend complete: Italian Grand Prix
✓ Cached weekend to race_data/2025/16_Monza/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 16...
  → Building circuit data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 3)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 7)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 9)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 11)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 15)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 17)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 19)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 21)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 25)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 29)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 30 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '61', '63', '87', '89', '3', '7', '9', '11', '15', '17', '19', '21', '25', '29']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.7.0]

  ✓ Track: 588 points, 5758m
    In-lap: 822 points
    Out-lap: 858 points
    Clipped: 582 points (from 1680)
  ✓ Pit lane: 582 points, 3909m
  ✓ Extracted rotation: 95.0°
  ✓ Extracted marshal sectors: 17 sectors
  ✓ Weekend complete: Italian Grand Prix
✓ Cached weekend to race_data/2025/16_Monza/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Italian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R16 R...

req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '44', '23', '5', '12', '6', '55', '87', '22', '30', '31', '10', '43', '18', '14', '27']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 33219 raw points
    ✓ NOR: 33360 raw points
    ✓ PIA: 33378 raw points
    ✓ LEC: 33410 raw points
    ✓ RUS: 33463 raw points
    ✓ HAM: 33500 raw points
    ✓ ALB: 33590 raw points
    ✓ BOR: 33653 raw points
    ✓ ANT: 33623 raw points
    ✓ HAD: 33690 raw points
    ✓ SAI: 33689 raw points
    ✓ BEA: 33729 raw points
    ✓ TSU: 33816 raw points
    ✓ LAW: 33827 raw points
    ✓ OCO: 33231 raw points
    ✓ GAS: 33259 raw points
    ✓ COL: 33271 raw points
    ✓ STR: 33286 raw points
    ✓ ALO: 15631 raw points
    ✓ HUL: 670 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 22 track status, 47 messages, 144 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 27 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/16_Monza/Race.pkl

  ✓ 16. Italian Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 17...

core           INFO 	Loading data for Azerbaijan Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 785 points, 5943m
    In-lap: 12553 points
    Out-lap: 905 points
    Clipped: 1360 points (from 13458)
  ✓ Pit lane: 1360 points, 2326m

core           INFO 	Loading data for Azerbaijan Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 357.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Azerbaijan Grand Prix
✓ Cached weekend to race_data/2025/17_Baku/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 17...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 785 points, 5943m
    In-lap: 12553 points
    Out-lap: 905 points
    Clipped: 1360 points (from 13458)
  ✓ Pit lane: 1360 points, 2326m

core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 357.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Azerbaijan Grand Prix
✓ Cached weekend to race_data/2025/17_Baku/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Azerbaijan Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R17 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '55', '12', '30', '22', '4', '44', '16', '6', '5', '87', '23', '31', '14', '27', '18', '10', '43', '81']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 41995 raw points
    ✓ RUS: 42104 raw points
    ✓ SAI: 42136 raw points
    ✓ ANT: 42154 raw points
    ✓ LAW: 42230 raw points
    ✓ TSU: 42235 raw points
    ✓ NOR: 42237 raw points
    ✓ HAM: 42250 raw points
    ✓ LEC: 42255 raw points
    ✓ HAD: 42271 raw points
    ✓ BOR: 42488 raw points
    ✓ BEA: 42493 raw points
    ✓ ALB: 42446 raw points
    ✓ OCO: 42569 raw points
    ✓ ALO: 42581 raw points
    ✓ HUL: 42592 raw points
    ✓ STR: 42716 raw points
    ✓ GAS: 42021 raw points
    ✓ COL: 42038 raw points
    ✓ PIA: 969 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 38 track status, 29 messages, 156 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 31 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Singapore Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2025/17_Baku/Race.pkl

  ✓ 17. Azerbaijan Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 18...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 683 points, 4884m
    In-lap: 974 points
    Out-lap: 909 points
    Clipped: 844 points (from 1883)
  ✓ Pit lane: 844 points, 3421m

core           INFO 	Loading data for Singapore Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data

  ✓ Extracted rotation: 335.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Singapore Grand Prix
✓ Cached weekend to race_data/2025/18_Marina_Bay/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 18...
  → Building circuit data...

req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 683 points, 4884m
    In-lap: 974 points
    Out-lap: 909 points
    Clipped: 844 points (from 1883)
  ✓ Pit lane: 844 points, 3421m

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 335.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Singapore Grand Prix
✓ Cached weekend to race_data/2025/18_Marina_Bay/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Singapore Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R18 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '4', '81', '12', '16', '14', '44', '87', '55', '6', '22', '18', '23', '30', '43', '5', '31', '10', '27']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ RUS: 45557 raw points
    ✓ VER: 45597 raw points
    ✓ NOR: 45602 raw points
    ✓ PIA: 45619 raw points
    ✓ ANT: 45806 raw points
    ✓ LEC: 45903 raw points
    ✓ ALO: 46171 raw points
    ✓ HAM: 46169 raw points
    ✓ BEA: 46273 raw points
    ✓ SAI: 45636 raw points
    ✓ HAD: 45687 raw points
    ✓ TSU: 45701 raw points
    ✓ STR: 45738 raw points
    ✓ ALB: 45746 raw points
    ✓ LAW: 45755 raw points
    ✓ COL: 45873 raw points
    ✓ BOR: 45907 raw points
    ✓ OCO: 45911 raw points
    ✓ GAS: 45914 raw points
    ✓ HUL: 45924 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 68 track status, 49 messages, 161 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 17 fastest laps, 1 position snapshots
  ✓ Extracted 2 rain event(s)
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/18_Marina_Bay/Race.pkl

  ✓ 18. Singapore Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 19...

core           INFO 	Loading data for United States Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 701 points, 5445m
    In-lap: 913 points
    Out-lap: 806 points
    Clipped: 718 points (from 1719)
  ✓ Pit lane: 718 points, 4528m

core           INFO 	Loading data for United States Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: United States Grand Prix
✓ Cached weekend to race_data/2025/19_Austin/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 19...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 701 points, 5445m
    In-lap: 913 points
    Out-lap: 806 points
    Clipped: 718 points (from 1719)
  ✓ Pit lane: 718 points, 4528m

core           INFO 	Loading data for United States Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 0.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: United States Grand Prix
✓ Cached weekend to race_data/2025/19_Austin/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: United States Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R19 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '44', '81', '63', '22', '27', '87', '14', '30', '18', '12', '23', '31', '6', '43', '5', '10', '55']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 42492 raw points
    ✓ GAS: 42539 raw points
    ✓ ANT: 43069 raw points
    ✓ ALO: 43023 raw points
    ✓ LEC: 42612 raw points
    ✓ STR: 43062 raw points
    ✓ TSU: 42886 raw points
    ✓ ALB: 43103 raw points
    ✓ HUL: 42925 raw points
    ✓ LAW: 43051 raw points
    ✓ OCO: 43124 raw points
    ✓ NOR: 42555 raw points
    ✓ COL: 42507 raw points
    ✓ HAM: 42705 raw points
    ✓ BOR: 42517 raw points
    ✓ SAI: 4727 raw points
    ✓ HAD: 43204 raw points
    ✓ RUS: 42746 raw points
    ✓ PIA: 42714 raw points
    ✓ BEA: 42978 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 30 track status, 44 messages, 154 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 8 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Mexico City Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2025/19_Austin/Race.pkl

  ✓ 19. United States Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 20...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['5', '6', '12', '14', '16', '22', '23', '27', '31', '35', '36', '38', '40', '43', '46', '50', '61', '72', '81', '89']

  ✓ Track: 609 points, 1096m
    In-lap: 685 points
    Out-lap: 855 points
  ✓ Pit lane: 27 points, 5034m

core           INFO 	Loading data for Mexico City Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 36.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Mexico City Grand Prix
✓ Cached weekend to race_data/2025/20_Mexico_City/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 20...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['5', '6', '12', '14', '16', '22', '23', '27', '31', '35', '36', '38', '40', '43', '46', '50', '61', '72', '81', '89']

  ✓ Track: 609 points, 1096m
    In-lap: 685 points
    Out-lap: 855 points
  ✓ Pit lane: 27 points, 5034m

core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 36.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: Mexico City Grand Prix
✓ Cached weekend to race_data/2025/20_Mexico_City/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Mexico City Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R20 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '16', '1', '87', '81', '12', '63', '44', '31', '5', '22', '23', '6', '18', '10', '43', '55', '14', '27', '30']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 44361 raw points
    ✓ GAS: 44453 raw points
    ✓ ANT: 44480 raw points
    ✓ ALO: 21670 raw points
    ✓ LEC: 44356 raw points
    ✓ STR: 44185 raw points
    ✓ TSU: 44723 raw points
    ✓ ALB: 44149 raw points
    ✓ HUL: 15981 raw points
    ✓ LAW: 3618 raw points
    ✓ OCO: 44696 raw points
    ✓ NOR: 44133 raw points
    ✓ COL: 44455 raw points
    ✓ HAM: 44553 raw points
    ✓ BOR: 44708 raw points
    ✓ SAI: 42680 raw points
    ✓ HAD: 44181 raw points
    ✓ RUS: 44503 raw points
    ✓ PIA: 44441 raw points
    ✓ BEA: 44431 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 29 track status, 45 messages, 162 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 23 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/20_Mexico_City/Race.pkl

  ✓ 20. Mexico City Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 21...

core           INFO 	Loading data for São Paulo Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 514 points, 4234m
    In-lap: 677 points
    Out-lap: 615 points
    Clipped: 287 points (from 1292)
  ✓ Pit lane: 287 points, 3576m

core           INFO 	Loading data for São Paulo Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 258.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: São Paulo Grand Prix
✓ Cached weekend to race_data/2025/21_São_Paulo/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 21...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 514 points, 4234m
    In-lap: 677 points
    Out-lap: 615 points
    Clipped: 287 points (from 1292)
  ✓ Pit lane: 287 points, 3576m

core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 258.0°
  ✓ Extracted marshal sectors: 16 sectors
  ✓ Weekend complete: São Paulo Grand Prix
✓ Cached weekend to race_data/2025/21_São_Paulo/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: São Paulo Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R21 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 4 completed the race distance 00:00.010000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '12', '1', '63', '81', '87', '30', '6', '27', '10', '23', '31', '55', '14', '43', '18', '22', '44', '16', '5']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 41841 raw points
    ✓ GAS: 42150 raw points
    ✓ ANT: 41838 raw points
    ✓ ALO: 42162 raw points
    ✓ LEC: 4278 raw points
    ✓ STR: 42182 raw points
    ✓ TSU: 42260 raw points
    ✓ ALB: 42152 raw points
    ✓ HUL: 42145 raw points
    ✓ LAW: 42139 raw points
    ✓ OCO: 42155 raw points
    ✓ NOR: 41761 raw points
    ✓ COL: 42178 raw points
    ✓ HAM: 23172 raw points
    ✓ BOR: 603 raw points
    ✓ SAI: 42161 raw points
    ✓ HAD: 42142 raw points
    ✓ RUS: 41875 raw points
    ✓ PIA: 41873 raw points
    ✓ BEA: 41973 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 20 track status, 29 messages, 152 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 15 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry

core           INFO 	Loading data for Las Vegas Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

✓ Cached session to race_data/2025/21_São_Paulo/Race.pkl

  ✓ 21. São Paulo Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 22...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver  4: Lap timing integrity check failed for 4 lap(s)
core        WARNING 	Driver  5: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver  6: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 10: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 12: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 14: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 16: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 18: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 22: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 23: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 27: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 30: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 31: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 43: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 44: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 55: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 63: Lap timing integrity check failed for 4 lap(s)
core        WARNING 	Driver 81: Lap timing integrity check failed for 4 lap(s)
core        WARNING 	Driver 87: Lap timing integrity check failed for 3 lap(s)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 720 points, 6147m
    In-lap: 885 points
    Out-lap: 844 points
    Clipped: 725 points (from 1729)
  ✓ Pit lane: 725 points, 3917m

core           INFO 	Loading data for Las Vegas Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver  4: Lap timing integrity check failed for 4 lap(s)
core        WARNING 	Driver  5: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver  6: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 10: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 12: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 14: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 16: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 18: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 22: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 23: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 27: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 30: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 31: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 43: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 44: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 55: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 63: Lap timing integrity check failed for 4 lap(s)
core        WARNING 	Driver 81: Lap timing integrity check failed for 4 lap(s)
core        WARNING 	Driver 87: Lap timing integrity check failed for 3 lap(s)

  ✓ Extracted rotation: 90.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Las Vegas Grand Prix
✓ Cached weekend to race_data/2025/22_Las_Vegas/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 22...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 720 points, 6147m
    In-lap: 885 points
    Out-lap: 844 points
    Clipped: 725 points (from 1729)
  ✓ Pit lane: 725 points, 3917m

core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '63'

  ✓ Extracted rotation: 90.0°
  ✓ Extracted marshal sectors: 21 sectors
  ✓ Weekend complete: Las Vegas Grand Prix
✓ Cached weekend to race_data/2025/22_Las_Vegas/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Las Vegas Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R22 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '63', '12', '16', '55', '6', '27', '44', '31', '87', '14', '22', '10', '30', '43', '23', '5', '18', '4', '81']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 36996 raw points
    ✓ RUS: 37173 raw points
    ✓ ANT: 37184 raw points
    ✓ LEC: 37225 raw points
    ✓ SAI: 37263 raw points
    ✓ HAD: 37339 raw points
    ✓ HUL: 37384 raw points
    ✓ HAM: 37453 raw points
    ✓ OCO: 37461 raw points
    ✓ BEA: 37532 raw points
    ✓ ALO: 37643 raw points
    ✓ TSU: 37656 raw points
    ✓ GAS: 37693 raw points
    ✓ LAW: 37019 raw points
    ✓ COL: 37073 raw points
    ✓ ALB: 27094 raw points
    ✓ BOR: 2204 raw points
    ✓ STR: 774 raw points
    ✓ NOR: 37151 raw points
    ✓ PIA: 37202 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 25 track status, 28 messages, 141 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 35 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/22_Las_Vegas/Race.pkl

  ✓ 22. Las Vegas Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 23...

core           INFO 	Loading data for Qatar Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 599 points, 5379m
    In-lap: 762 points
    Out-lap: 737 points
    Clipped: 498 points (from 1499)
  ✓ Pit lane: 498 points, 4484m

core           INFO 	Loading data for Qatar Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 61.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Qatar Grand Prix
✓ Cached weekend to race_data/2025/23_Lusail/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 23...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

  ✓ Track: 599 points, 5379m
    In-lap: 762 points
    Out-lap: 737 points
    Clipped: 498 points (from 1499)
  ✓ Pit lane: 498 points, 4484m

core           INFO 	Loading data for Qatar Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 61.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Qatar Grand Prix
✓ Cached weekend to race_data/2025/23_Lusail/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Qatar Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R23 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '55', '4', '12', '63', '14', '16', '30', '22', '23', '44', '5', '43', '31', '10', '18', '6', '87', '27']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 38015 raw points
    ✓ GAS: 38049 raw points
    ✓ ANT: 38219 raw points
    ✓ ALO: 38402 raw points
    ✓ LEC: 38422 raw points
    ✓ STR: 37557 raw points
    ✓ TSU: 38462 raw points
    ✓ ALB: 38502 raw points
    ✓ HUL: 4142 raw points
    ✓ LAW: 38449 raw points
    ✓ OCO: 38043 raw points
    ✓ NOR: 38183 raw points
    ✓ COL: 38037 raw points
    ✓ HAM: 38581 raw points
    ✓ BOR: 38631 raw points
    ✓ SAI: 38178 raw points
    ✓ HAD: 37685 raw points
    ✓ RUS: 38367 raw points
    ✓ PIA: 38072 raw points
    ✓ BEA: 28674 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...

core           INFO 	Loading data for Abu Dhabi Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 21 track status, 53 messages, 149 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 11 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/23_Lusail/Race.pkl

  ✓ 23. Qatar Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 24...
  → Building circuit data...

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '12', '16', '27', '34', '35', '36', '39', '40', '43', '46', '50', '55', '61', '63', '87', '89']

  ✓ Track: 639 points, 5224m
    In-lap: 977 points
    Out-lap: 1020 points
    Clipped: 953 points (from 1997)
  ✓ Pit lane: 953 points, 3986m

core           INFO 	Loading data for Abu Dhabi Grand Prix - Practice 1 [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 280.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Abu Dhabi Grand Prix
✓ Cached weekend to race_data/2025/24_Yas_Island/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building weekend data from FastF1...
→ Loading weekend 2025 Round 24...
  → Building circuit data...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '12', '16', '27', '34', '35', '36', '39', '40', '43', '46', '50', '55', '61', '63', '87', '89']

  ✓ Track: 639 points, 5224m
    In-lap: 977 points
    Out-lap: 1020 points
    Clipped: 953 points (from 1997)
  ✓ Pit lane: 953 points, 3986m

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

  ✓ Extracted rotation: 280.0°
  ✓ Extracted marshal sectors: 20 sectors
  ✓ Weekend complete: Abu Dhabi Grand Prix
✓ Cached weekend to race_data/2025/24_Yas_Island/Weekend.pkl

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Abu Dhabi Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

📡 Building session data from FastF1...
→ Loading session 2025 R24 R...

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '63', '14', '31', '44', '27', '18', '5', '87', '55', '22', '12', '23', '6', '30', '10', '43']

  → Building complete telemetry (time, progress, status, gaps, order)...
    ✓ VER: 38863 raw points
    ✓ PIA: 38957 raw points
    ✓ NOR: 38986 raw points
    ✓ LEC: 39028 raw points
    ✓ RUS: 39217 raw points
    ✓ ALO: 39356 raw points
    ✓ OCO: 39374 raw points
    ✓ HAM: 39395 raw points
    ✓ HUL: 39437 raw points
    ✓ STR: 39409 raw points
    ✓ BOR: 39454 raw points
    ✓ BEA: 39423 raw points
    ✓ SAI: 39463 raw points
    ✓ TSU: 39469 raw points
    ✓ ANT: 39473 raw points
    ✓ ALB: 39480 raw points
    ✓ HAD: 38870 raw points
    ✓ LAW: 38895 raw points
    ✓ GAS: 38910 raw points
    ✓ COL: 38965 raw points
  → Normalizing time to session start...
  → Adding progress column...
  → Adding status column...
  → Building order dataset...
  → Calculating TimeToDriverAhead gaps...
  ✓ Complete telemetry: 20 drivers with all derived fields
  → Events: 21 track status, 84 messages, 154 weather samples
  → Building results with telemetry: 20 drivers, session_time=✓
  → Results: 17 fastest laps, 1 position snapshots
  ✓ Session complete: 20 drivers, 20 with telemetry
✓ Cached session to race_data/2025/24_Yas_Island/Race.pkl

  ✓ 24. Abu Dhabi Grand Prix

✓ Processed 24/25 races successfully
⚠️  1 races failed to process

In [2]:
race.results.fastest_laps

[FastestLapEvent(lap=1, driver='LEC', time=2456.33, lap_time_ms=2456330, session_time=2456.6390000000006),
 FastestLapEvent(lap=2, driver='ALO', time=124.571, lap_time_ms=124571, session_time=2638.028),
 FastestLapEvent(lap=2, driver='SAR', time=121.235, lap_time_ms=121235, session_time=2638.3660000000004),
 FastestLapEvent(lap=2, driver='ZHO', time=112.131, lap_time_ms=112131, session_time=2638.6570000000006),
 FastestLapEvent(lap=3, driver='RIC', time=89.656, lap_time_ms=89656, session_time=2727.644),
 FastestLapEvent(lap=3, driver='NOR', time=85.283, lap_time_ms=85283, session_time=2721.2640000000006),
 FastestLapEvent(lap=3, driver='PIA', time=84.953, lap_time_ms=84953, session_time=2720.097),
 FastestLapEvent(lap=3, driver='LEC', time=84.624, lap_time_ms=84624, session_time=2719.0840000000003),
 FastestLapEvent(lap=4, driver='SAR', time=83.682, lap_time_ms=83682, session_time=2812.1250000000005),
 FastestLapEvent(lap=4, driver='NOR', time=82.782, lap_time_ms=82782, session_time=2804.046),
 FastestLapEvent(lap=4, driver='LEC', time=82.625, lap_time_ms=82625, session_time=2801.7090000000003),
 FastestLapEvent(lap=4, driver='SAI', time=82.358, lap_time_ms=82358, session_time=2803.028),
 FastestLapEvent(lap=4, driver='PIA', time=82.314, lap_time_ms=82314, session_time=2802.4110000000005),
 FastestLapEvent(lap=5, driver='PIA', time=82.019, lap_time_ms=82019, session_time=2884.43),
 FastestLapEvent(lap=5, driver='LEC', time=81.795, lap_time_ms=81795, session_time=2883.5040000000004),
 FastestLapEvent(lap=6, driver='LEC', time=81.145, lap_time_ms=81145, session_time=2964.649),
 FastestLapEvent(lap=7, driver='PIA', time=80.808, lap_time_ms=80808, session_time=3046.592),
 FastestLapEvent(lap=8, driver='SAI', time=80.272, lap_time_ms=80272, session_time=3127.9070000000006),
 FastestLapEvent(lap=9, driver='LEC', time=80.114, lap_time_ms=80114, session_time=3206.7730000000006),
 FastestLapEvent(lap=9, driver='PIA', time=79.906, lap_time_ms=79906, session_time=3207.556),
 FastestLapEvent(lap=13, driver='LEC', time=79.017, lap_time_ms=79017, session_time=3527.863),
 FastestLapEvent(lap=13, driver='PIA', time=78.745, lap_time_ms=78745, session_time=3528.2240000000006),
 FastestLapEvent(lap=17, driver='BOT', time=76.561, lap_time_ms=76561, session_time=3886.863),
 FastestLapEvent(lap=53, driver='HAM', time=76.458, lap_time_ms=76458, session_time=6719.6900000000005),
 FastestLapEvent(lap=54, driver='HAM', time=76.388, lap_time_ms=76388, session_time=6796.0779999999995),
 FastestLapEvent(lap=54, driver='VER', time=75.815, lap_time_ms=75815, session_time=6793.465),
 FastestLapEvent(lap=55, driver='VER', time=75.398, lap_time_ms=75398, session_time=6868.862999999999),
 FastestLapEvent(lap=56, driver='HAM', time=74.423, lap_time_ms=74423, session_time=6946.993),
 FastestLapEvent(lap=59, driver='HAM', time=74.204, lap_time_ms=74204, session_time=7175.909),
 FastestLapEvent(lap=63, driver='HAM', time=74.165, lap_time_ms=74165, session_time=7476.610000000001)]

In [2]:
import pandas as pd
pd.set_option('display.max_rows', 1000, 'display.max_columns', 500)
race.telemetry["MAG"].to_pandas().head(1000)

                       Date            SessionTime DriverAhead  \
0   2024-05-26 13:03:11.069 0 days 00:55:05.680000
1   2024-05-26 13:03:11.156 0 days 00:55:05.767000
2   2024-05-26 13:03:11.230 0 days 00:55:05.841000
3   2024-05-26 13:03:11.356 0 days 00:55:05.967000          23
4   2024-05-26 13:03:11.469 0 days 00:55:06.080000          23
5   2024-05-26 13:03:11.676 0 days 00:55:06.287000          16
6   2024-05-26 13:03:11.729 0 days 00:55:06.340000          16
7   2024-05-26 13:03:11.949 0 days 00:55:06.560000          16
8   2024-05-26 13:03:11.956 0 days 00:55:06.567000          16
9   2024-05-26 13:03:12.209 0 days 00:55:06.820000          16
10  2024-05-26 13:03:12.276 0 days 00:55:06.887000          23
11  2024-05-26 13:03:12.410 0 days 00:55:07.021000          23
12  2024-05-26 13:03:12.476 0 days 00:55:07.087000          27
13  2024-05-26 13:03:12.569 0 days 00:55:07.180000          27
14  2024-05-26 13:03:12.676 0 days 00:55:07.287000          27
15  2024-05-26 13:03:12.789 0 days 00:55:07.400000          27
16  2024-05-26 13:03:12.876 0 days 00:55:07.487000          55
17  2024-05-26 13:03:13.069 0 days 00:55:07.680000          55
18  2024-05-26 13:03:13.116 0 days 00:55:07.727000          55
19  2024-05-26 13:03:13.389        0 days 00:55:08          55
20  2024-05-26 13:03:13.476 0 days 00:55:08.087000          11
21  2024-05-26 13:03:13.716 0 days 00:55:08.327000          23
22  2024-05-26 13:03:13.730 0 days 00:55:08.341000          23
23  2024-05-26 13:03:14.116 0 days 00:55:08.727000           2
24  2024-05-26 13:03:14.150 0 days 00:55:08.761000           2
25  2024-05-26 13:03:14.276 0 days 00:55:08.887000           2
26  2024-05-26 13:03:14.490 0 days 00:55:09.101000           2
27  2024-05-26 13:03:14.597 0 days 00:55:09.208000          81
28  2024-05-26 13:03:14.630 0 days 00:55:09.241000          81
29  2024-05-26 13:03:14.837 0 days 00:55:09.448000          81
30  2024-05-26 13:03:14.850 0 days 00:55:09.461000          81
31  2024-05-26 13:03:15.157 0 days 00:55:09.768000          11
32  2024-05-26 13:03:15.170 0 days 00:55:09.781000          11
33  2024-05-26 13:03:15.357 0 days 00:55:09.968000          63
34  2024-05-26 13:03:15.490 0 days 00:55:10.101000          63
35  2024-05-26 13:03:15.557 0 days 00:55:10.168000          63
36  2024-05-26 13:03:15.709 0 days 00:55:10.320000          63
37  2024-05-26 13:03:15.890 0 days 00:55:10.501000          63
38  2024-05-26 13:03:15.997 0 days 00:55:10.608000          44
39  2024-05-26 13:03:16.157 0 days 00:55:10.768000          14
40  2024-05-26 13:03:16.170 0 days 00:55:10.781000          14
41  2024-05-26 13:03:16.436 0 days 00:55:11.047000          18
42  2024-05-26 13:03:16.450 0 days 00:55:11.061000          18
43  2024-05-26 13:03:16.876 0 days 00:55:11.487000           2
44  2024-05-26 13:03:16.889 0 days 00:55:11.500000           2
45  2024-05-26 13:03:17.036 0 days 00:55:11.647000           2
46  2024-05-26 13:03:17.210 0 days 00:55:11.821000           2
47  2024-05-26 13:03:17.316 0 days 00:55:11.927000           2
48  2024-05-26 13:03:17.449 0 days 00:55:12.060000           2
49  2024-05-26 13:03:17.476 0 days 00:55:12.087000          18
50  2024-05-26 13:03:17.629 0 days 00:55:12.240000          18
51  2024-05-26 13:03:17.929 0 days 00:55:12.540000          18
52  2024-05-26 13:03:17.956 0 days 00:55:12.567000          27
53  2024-05-26 13:03:18.090 0 days 00:55:12.701000          27
54  2024-05-26 13:03:18.116 0 days 00:55:12.727000          27
55  2024-05-26 13:03:18.390 0 days 00:55:13.001000          27
56  2024-05-26 13:03:18.516 0 days 00:55:13.127000          27
57  2024-05-26 13:03:18.789 0 days 00:55:13.400000          27
58  2024-05-26 13:03:18.796 0 days 00:55:13.407000          27
59  2024-05-26 13:03:18.890 0 days 00:55:13.501000          27
60  2024-05-26 13:03:19.076 0 days 00:55:13.687000          27
61  2024-05-26 13:03:19.109 0 days 00:55:13.720000          27
62  2024-05-26 13:03:19.236 0 days 00:55:13.847000          27
63  2024-05-26 13:03:19.290 0 days 00:55:13.901000          27
64  2024-05-26 13:03:19.510 0 days 00:55:14.121000          27
65  2024-05-26 13:03:19.596 0 days 00:55:14.207000          27
66  2024-05-26 13:03:19.710 0 days 00:55:14.321000          27
67  2024-05-26 13:03:19.916 0 days 00:55:14.527000          27
68  2024-05-26 13:03:20.050 0 days 00:55:14.661000          27
69  2024-05-26 13:03:20.076 0 days 00:55:14.687000          27
70  2024-05-26 13:03:20.370 0 days 00:55:14.981000          27
71  2024-05-26 13:03:20.476 0 days 00:55:15.087000
72  2024-05-26 13:03:20.650 0 days 00:55:15.261000
73  2024-05-26 13:03:20.676 0 days 00:55:15.287000
74  2024-05-26 13:03:20.770 0 days 00:55:15.381000
75  2024-05-26 13:03:20.836 0 days 00:55:15.447000
76  2024-05-26 13:03:21.009 0 days 00:55:15.620000
77  2024-05-26 13:03:21.237 0 days 00:55:15.848000
78  2024-05-26 13:03:21.450 0 days 00:55:16.061000
79  2024-05-26 13:03:21.597 0 days 00:55:16.208000
80  2024-05-26 13:03:21.630 0 days 00:55:16.241000
81  2024-05-26 13:03:21.790 0 days 00:55:16.401000
82  2024-05-26 13:03:21.797 0 days 00:55:16.408000
83  2024-05-26 13:03:21.950 0 days 00:55:16.561000
84  2024-05-26 13:03:21.957 0 days 00:55:16.568000
85  2024-05-26 13:03:22.190 0 days 00:55:16.801000
86  2024-05-26 13:03:22.317 0 days 00:55:16.928000
87  2024-05-26 13:03:22.517 0 days 00:55:17.128000
88  2024-05-26 13:03:22.529 0 days 00:55:17.140000
89  2024-05-26 13:03:22.717 0 days 00:55:17.328000          16
90  2024-05-26 13:03:22.809 0 days 00:55:17.420000          16
91  2024-05-26 13:03:22.917 0 days 00:55:17.528000          81
92  2024-05-26 13:03:23.076 0 days 00:55:17.687000          81
93  2024-05-26 13:03:23.169 0 days 00:55:17.780000          81
94  2024-05-26 13:03:23.329 0 days 00:55:17.940000          81
95  2024-05-26 13:03:23.356 0 days 00:55:17.967000           4
96  2024-05-26 13:03:23.556 0 days 00:55:18.167000          63
97  2024-05-26 13:03:23.629 0 days 00:55:18.240000          63
98  2024-05-26 13:03:23.756 0 days 00:55:18.367000           1
99  2024-05-26 13:03:23.969 0 days 00:55:18.580000           1
100 2024-05-26 13:03:23.996 0 days 00:55:18.607000          44
101 2024-05-26 13:03:24.169 0 days 00:55:18.780000          44
102 2024-05-26 13:03:24.236 0 days 00:55:18.847000          10
103 2024-05-26 13:03:24.436 0 days 00:55:19.047000          23
104 2024-05-26 13:03:24.590 0 days 00:55:19.201000          23
105 2024-05-26 13:03:24.756 0 days 00:55:19.367000          31
106 2024-05-26 13:03:24.989 0 days 00:55:19.600000          31
107 2024-05-26 13:03:24.996 0 days 00:55:19.607000          31
108 2024-05-26 13:03:25.150 0 days 00:55:19.761000          31
109 2024-05-26 13:03:25.276 0 days 00:55:19.887000           2
110 2024-05-26 13:03:25.349 0 days 00:55:19.960000           2
111 2024-05-26 13:03:25.556 0 days 00:55:20.167000           2
112 2024-05-26 13:03:25.569 0 days 00:55:20.180000           2
113 2024-05-26 13:03:25.756 0 days 00:55:20.367000           3
114 2024-05-26 13:03:25.770 0 days 00:55:20.381000           3
115 2024-05-26 13:03:26.050 0 days 00:55:20.661000           3
116 2024-05-26 13:03:26.076 0 days 00:55:20.687000          77
117 2024-05-26 13:03:26.230 0 days 00:55:20.841000          77
118 2024-05-26 13:03:26.436 0 days 00:55:21.047000          77
119 2024-05-26 13:03:26.570 0 days 00:55:21.181000          77
120 2024-05-26 13:03:26.596 0 days 00:55:21.207000          77
121 2024-05-26 13:03:26.890 0 days 00:55:21.501000          77
122 2024-05-26 13:03:26.916 0 days 00:55:21.527000          77
123 2024-05-26 13:03:27.076 0 days 00:55:21.687000          77
124 2024-05-26 13:03:27.269 0 days 00:55:21.880000          77
125 2024-05-26 13:03:27.276 0 days 00:55:21.887000          77
126 2024-05-26 13:03:27.437 0 days 00:55:22.048000          77
127 2024-05-26 13:03:27.597 0 days 00:55:22.208000          77
128 2024-05-26 13:03:27.670 0 days 00:55:22.281000          77
129 2024-05-26 13:03:27.837 0 days 00:55:22.448000          77
130 2024-05-26 13:03:27.910 0 days 00:55:22.521000          77
131 2024-05-26 13:03:28.197 0 days 00:55:22.808000          77
132 2024-05-26 13:03:28.270 0 days 00:55:22.881000          77
133 2024-05-26 13:03:28.397 0 days 00:55:23.008000          77
134 2024-05-26 13:03:28.530 0 days 00:55:23.141000          77
135 2024-05-26 13:03:28.710 0 days 00:55:23.321000          77
136 2024-05-26 13:03:28.757 0 days 00:55:23.368000          77
137 2024-05-26 13:03:28.917 0 days 00:55:23.528000          77
138 2024-05-26 13:03:29.069 0 days 00:55:23.680000          77
139 2024-05-26 13:03:29.230 0 days 00:55:23.841000          77
140 2024-05-26 13:03:29.277 0 days 00:55:23.888000          77
141 2024-05-26 13:03:29.409 0 days 00:55:24.020000          77
142 2024-05-26 13:03:29.597 0 days 00:55:24.208000          77
143 2024-05-26 13:03:29.790 0 days 00:55:24.401000          77
144 2024-05-26 13:03:29.849 0 days 00:55:24.460000          77
145 2024-05-26 13:03:29.916 0 days 00:55:24.527000          77
146 2024-05-26 13:03:30.030 0 days 00:55:24.641000          77
147 2024-05-26 13:03:30.156 0 days 00:55:24.767000          27
148 2024-05-26 13:03:30.269 0 days 00:55:24.880000          27
149 2024-05-26 13:03:30.436 0 days 00:55:25.047000          27
150 2024-05-26 13:03:30.630 0 days 00:55:25.241000          27
151 2024-05-26 13:03:30.716 0 days 00:55:25.327000          27
152 2024-05-26 13:03:30.870 0 days 00:55:25.481000          27
153 2024-05-26 13:03:30.876 0 days 00:55:25.487000          27
154 2024-05-26 13:03:31.116 0 days 00:55:25.727000          27
155 2024-05-26 13:03:31.229 0 days 00:55:25.840000          27
156 2024-05-26 13:03:31.316 0 days 00:55:25.927000          27
157 2024-05-26 13:03:31.510 0 days 00:55:26.121000          27
158 2024-05-26 13:03:31.636 0 days 00:55:26.247000          27
159 2024-05-26 13:03:31.730 0 days 00:55:26.341000          27
160 2024-05-26 13:03:31.836 0 days 00:55:26.447000          27
161 2024-05-26 13:03:31.950 0 days 00:55:26.561000          27
162 2024-05-26 13:03:32.190 0 days 00:55:26.801000          27
163 2024-05-26 13:03:32.236 0 days 00:55:26.847000          27
164 2024-05-26 13:03:32.369 0 days 00:55:26.980000          27
165 2024-05-26 13:03:32.610 0 days 00:55:27.221000          27
166 2024-05-26 13:03:32.636 0 days 00:55:27.247000          27
167 2024-05-26 13:03:32.790 0 days 00:55:27.401000          27
168 2024-05-26 13:03:33.030 0 days 00:55:27.641000          27
169 2024-05-26 13:03:33.076 0 days 00:55:27.687000          27
170 2024-05-26 13:03:33.236 0 days 00:55:27.847000          27
171 2024-05-26 13:03:33.249 0 days 00:55:27.860000          27
172 2024-05-26 13:03:33.410 0 days 00:55:28.021000          27
173 2024-05-26 13:03:33.516 0 days 00:55:28.127000          27
174 2024-05-26 13:03:33.750 0 days 00:55:28.361000          27
175 2024-05-26 13:03:33.796 0 days 00:55:28.407000          27
176 2024-05-26 13:03:33.910 0 days 00:55:28.521000          27
177 2024-05-26 13:03:34.050 0 days 00:55:28.661000          27
178 2024-05-26 13:03:34.117 0 days 00:55:28.728000          27
179 2024-05-26 13:03:34.270 0 days 00:55:28.881000          27
180 2024-05-26 13:03:34.357 0 days 00:55:28.968000          27
181 2024-05-26 13:03:34.530 0 days 00:55:29.141000          27
182 2024-05-26 13:03:34.757 0 days 00:55:29.368000          27
183 2024-05-26 13:03:34.970 0 days 00:55:29.581000          27
184 2024-05-26 13:03:35.070 0 days 00:55:29.681000          27
185 2024-05-26 13:03:35.197 0 days 00:55:29.808000          27
186 2024-05-26 13:03:35.250 0 days 00:55:29.861000          27
187 2024-05-26 13:03:35.477 0 days 00:55:30.088000          27
188 2024-05-26 13:03:35.549 0 days 00:55:30.160000          27
189 2024-05-26 13:03:35.717 0 days 00:55:30.328000          27
190 2024-05-26 13:03:35.789 0 days 00:55:30.400000          27
191 2024-05-26 13:03:35.957 0 days 00:55:30.568000          27
192 2024-05-26 13:03:36.169 0 days 00:55:30.780000          27
193 2024-05-26 13:03:36.197 0 days 00:55:30.808000          27
194 2024-05-26 13:03:36.397 0 days 00:55:31.008000          27
195 2024-05-26 13:03:36.449 0 days 00:55:31.060000          27
196 2024-05-26 13:03:36.596 0 days 00:55:31.207000          27
197 2024-05-26 13:03:36.629 0 days 00:55:31.240000          27
198 2024-05-26 13:03:36.810 0 days 00:55:31.421000          27
199 2024-05-26 13:03:36.836 0 days 00:55:31.447000          27
200 2024-05-26 13:03:37.756 0 days 00:55:32.367000          27
201 2024-05-26 13:03:37.849 0 days 00:55:32.460000          27
202 2024-05-26 13:03:37.930 0 days 00:55:32.541000          27
203 2024-05-26 13:03:37.956 0 days 00:55:32.567000          27
204 2024-05-26 13:03:38.190 0 days 00:55:32.801000          27
205 2024-05-26 13:03:38.196 0 days 00:55:32.807000          27
206 2024-05-26 13:03:38.436 0 days 00:55:33.047000          27
207 2024-05-26 13:03:38.450 0 days 00:55:33.061000          27
208 2024-05-26 13:03:38.669 0 days 00:55:33.280000          27
209 2024-05-26 13:03:38.716 0 days 00:55:33.327000          27
210 2024-05-26 13:03:38.996 0 days 00:55:33.607000          23
211 2024-05-26 13:03:39.010 0 days 00:55:33.621000          23
212 2024-05-26 13:03:39.156 0 days 00:55:33.767000          23
213 2024-05-26 13:03:39.209 0 days 00:55:33.820000          23
214 2024-05-26 13:03:39.390 0 days 00:55:34.001000          23
215 2024-05-26 13:03:39.476 0 days 00:55:34.087000           3
216 2024-05-26 13:03:39.676 0 days 00:55:34.287000          27
217 2024-05-26 13:03:39.749 0 days 00:55:34.360000          27
218 2024-05-26 13:03:39.956 0 days 00:55:34.567000          27
219 2024-05-26 13:03:40.170 0 days 00:55:34.781000          27
220 2024-05-26 13:03:40.236 0 days 00:55:34.847000          27
221 2024-05-26 13:03:40.350 0 days 00:55:34.961000          27
222 2024-05-26 13:03:40.510 0 days 00:55:35.121000          27
223 2024-05-26 13:03:40.556 0 days 00:55:35.167000          27
224 2024-05-26 13:03:40.877 0 days 00:55:35.488000          27
225 2024-05-26 13:03:40.910 0 days 00:55:35.521000          27
226 2024-05-26 13:03:41.090 0 days 00:55:35.701000          27
227 2024-05-26 13:03:41.197 0 days 00:55:35.808000          27
228 2024-05-26 13:03:41.250 0 days 00:55:35.861000          27
229 2024-05-26 13:03:41.397 0 days 00:55:36.008000          27
230 2024-05-26 13:03:41.597 0 days 00:55:36.208000          27
231 2024-05-26 13:03:41.630 0 days 00:55:36.241000          27
232 2024-05-26 13:03:41.830 0 days 00:55:36.441000          27
233 2024-05-26 13:03:41.837 0 days 00:55:36.448000          27
234 2024-05-26 13:03:42.010 0 days 00:55:36.621000          27
235 2024-05-26 13:03:42.117 0 days 00:55:36.728000          27
236 2024-05-26 13:03:42.277 0 days 00:55:36.888000          27
237 2024-05-26 13:03:42.329 0 days 00:55:36.940000          27
238 2024-05-26 13:03:42.477 0 days 00:55:37.088000          27
239 2024-05-26 13:03:42.609 0 days 00:55:37.220000          27
240 2024-05-26 13:03:42.810 0 days 00:55:37.421000          27
241 2024-05-26 13:03:42.837 0 days 00:55:37.448000          27
242 2024-05-26 13:03:42.969 0 days 00:55:37.580000          27
243 2024-05-26 13:03:43.077 0 days 00:55:37.688000          55
244 2024-05-26 13:03:43.130 0 days 00:55:37.741000          55
245 2024-05-26 13:03:43.356 0 days 00:55:37.967000          55
246 2024-05-26 13:03:43.489 0 days 00:55:38.100000          55
247 2024-05-26 13:03:43.516 0 days 00:55:38.127000          55
248 2024-05-26 13:03:43.756 0 days 00:55:38.367000          55
249 2024-05-26 13:03:43.829 0 days 00:55:38.440000          55
250 2024-05-26 13:03:43.956 0 days 00:55:38.567000          55
251 2024-05-26 13:03:43.990 0 days 00:55:38.601000          55
252 2024-05-26 13:03:44.129 0 days 00:55:38.740000          55
253 2024-05-26 13:03:44.156 0 days 00:55:38.767000          55
254 2024-05-26 13:03:44.396 0 days 00:55:39.007000          55
255 2024-05-26 13:03:44.470 0 days 00:55:39.081000          55
256 2024-05-26 13:03:44.676 0 days 00:55:39.287000          55
257 2024-05-26 13:03:44.790 0 days 00:55:39.401000          55
258 2024-05-26 13:03:45.070 0 days 00:55:39.681000          55
259 2024-05-26 13:03:45.076 0 days 00:55:39.687000          55
260 2024-05-26 13:03:45.270 0 days 00:55:39.881000          55
261 2024-05-26 13:03:45.276 0 days 00:55:39.887000          55
262 2024-05-26 13:03:45.476 0 days 00:55:40.087000          55
263 2024-05-26 13:03:45.489 0 days 00:55:40.100000          55
264 2024-05-26 13:03:45.876 0 days 00:55:40.487000          55
265 2024-05-26 13:03:45.910 0 days 00:55:40.521000          55
266 2024-05-26 13:03:46.076 0 days 00:55:40.687000          55
267 2024-05-26 13:03:46.090 0 days 00:55:40.701000          55
268 2024-05-26 13:03:46.190 0 days 00:55:40.801000          55
269 2024-05-26 13:03:46.236 0 days 00:55:40.847000          55
270 2024-05-26 13:03:46.490 0 days 00:55:41.101000          55
271 2024-05-26 13:03:46.516 0 days 00:55:41.127000          55
272 2024-05-26 13:03:46.670 0 days 00:55:41.281000          55
273 2024-05-26 13:03:46.716 0 days 00:55:41.327000          55
274 2024-05-26 13:03:47.076 0 days 00:55:41.687000           3
275 2024-05-26 13:03:47.110 0 days 00:55:41.721000           3
276 2024-05-26 13:03:47.250 0 days 00:55:41.861000           3
277 2024-05-26 13:03:47.317 0 days 00:55:41.928000           3
278 2024-05-26 13:03:47.477 0 days 00:55:42.088000           3
279 2024-05-26 13:03:47.590 0 days 00:55:42.201000           3
280 2024-05-26 13:03:47.757 0 days 00:55:42.368000           3
281 2024-05-26 13:03:47.910 0 days 00:55:42.521000           3
282 2024-05-26 13:03:48.037 0 days 00:55:42.648000           3
283 2024-05-26 13:03:48.110 0 days 00:55:42.721000           3
284 2024-05-26 13:03:48.251 0 days 00:55:42.862000           3
285 2024-05-26 13:03:48.277 0 days 00:55:42.888000           3
286 2024-05-26 13:03:48.437 0 days 00:55:43.048000          14
287 2024-05-26 13:03:48.590 0 days 00:55:43.201000          14
288 2024-05-26 13:03:48.637 0 days 00:55:43.248000          14
289 2024-05-26 13:03:48.957 0 days 00:55:43.568000          14
290 2024-05-26 13:03:48.969 0 days 00:55:43.580000          14
291 2024-05-26 13:03:49.157 0 days 00:55:43.768000          14
292 2024-05-26 13:03:49.317 0 days 00:55:43.928000          14
293 2024-05-26 13:03:49.330 0 days 00:55:43.941000          14
294 2024-05-26 13:03:49.517 0 days 00:55:44.128000          55
295 2024-05-26 13:03:49.529 0 days 00:55:44.140000          55
296 2024-05-26 13:03:49.749 0 days 00:55:44.360000          55
297 2024-05-26 13:03:49.797 0 days 00:55:44.408000          55
298 2024-05-26 13:03:49.996 0 days 00:55:44.607000          55
299 2024-05-26 13:03:50.009 0 days 00:55:44.620000          55
300 2024-05-26 13:03:50.276 0 days 00:55:44.887000          55
301 2024-05-26 13:03:50.409 0 days 00:55:45.020000          55
302 2024-05-26 13:03:50.596 0 days 00:55:45.207000          55
303 2024-05-26 13:03:50.629 0 days 00:55:45.240000          55
304 2024-05-26 13:03:50.756 0 days 00:55:45.367000          55
305 2024-05-26 13:03:50.810 0 days 00:55:45.421000          55
306 2024-05-26 13:03:51.030 0 days 00:55:45.641000          55
307 2024-05-26 13:03:51.036 0 days 00:55:45.647000          55
308 2024-05-26 13:03:51.209 0 days 00:55:45.820000          55
309 2024-05-26 13:03:51.236 0 days 00:55:45.847000          55
310 2024-05-26 13:03:51.396 0 days 00:55:46.007000          55
311 2024-05-26 13:03:51.409 0 days 00:55:46.020000          55
312 2024-05-26 13:03:51.556 0 days 00:55:46.167000          55
313 2024-05-26 13:03:51.650 0 days 00:55:46.261000          55
314 2024-05-26 13:03:51.890 0 days 00:55:46.501000          55
315 2024-05-26 13:03:51.916 0 days 00:55:46.527000          55
316 2024-05-26 13:03:52.070 0 days 00:55:46.681000          55
317 2024-05-26 13:03:52.076 0 days 00:55:46.687000          55
318 2024-05-26 13:03:52.236 0 days 00:55:46.847000          55
319 2024-05-26 13:03:52.470 0 days 00:55:47.081000          55

In [35]:
loader = DataLoader(cache_dir="race_data")

✓ FastF1 cache: race_data/.fastf1_cache
✓ DataLoader initialized: race_data

In [36]:
seasons = loader.load_seasons(years=[2020,2021,2022,2023,2024,2025]) # , force_update=True

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]

In [37]:
weekend = loader.load_weekend(2024, 8) # , force_update=True

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Monaco Grand Prix

In [38]:
metadata = weekend.metadata
circuit = weekend.circuit

print(f"\n   Event: {metadata.event_name}")
print(f"   Location: {metadata.location}, {metadata.country}")
print(f"   Date: {metadata.event_date}")
print(f"   Timezone: {metadata.timezone}")

print(f"\n   Circuit:")
print(f"     Track length: {circuit.circuit_length:.0f}m")
print(f"     Track points: {len(circuit.track.x)}")
print(f"     Pit lane available: {circuit.pit_lane is not None}")
if circuit.pit_lane:
    print(f"     Pit lane points: {len(circuit.pit_lane.x)}")
print(f"     Track segments: {len(circuit.track_segments)}")

for segment in circuit.track_segments:
    print(f"       - {segment.name}: {segment.start_distance:.0f}m - {segment.end_distance:.0f}m")

   Event: Monaco Grand Prix
   Location: Monaco, Monaco
   Date: 2024-05-26
   Timezone: UTC

   Circuit:
     Track length: 3286m
     Track points: 566
     Pit lane available: True
     Pit lane points: 628
     Track segments: 19
       - Sector 1: 3279m - 137m
       - Sector 2: 137m - 408m
       - Sector 3: 408m - 563m
       - Sector 4: 563m - 749m
       - Sector 5: 749m - 883m
       - Sector 6: 883m - 1061m
       - Sector 7: 1061m - 1218m
       - Sector 8: 1218m - 1296m
       - Sector 9: 1296m - 1366m
       - Sector 10: 1366m - 1480m
       - Sector 11: 1480m - 1718m
       - Sector 12: 1718m - 1967m
       - Sector 13: 1967m - 2182m
       - Sector 14: 2182m - 2429m
       - Sector 15: 2429m - 2640m
       - Sector 16: 2640m - 2797m
       - Sector 17: 2797m - 2929m
       - Sector 18: 2929m - 3117m
       - Sector 19: 3117m - 3279m

In [7]:
weekend.metadata

WeekendMetadata(year=2024, round_number=8, event_name='Monaco Grand Prix', location='Monaco', country='Monaco', circuit_name='', timezone='UTC', event_date='2024-05-26', session_schedule={}, available_sessions=['FP1', 'FP2', 'FP3', 'Q', 'R'])

In [18]:
race.results

ResultsData(fastest_laps=[FastestLapEvent(lap=71, driver='LEC', time=75.162, lap_time_ms=75162), FastestLapEvent(lap=73, driver='PIA', time=76.281, lap_time_ms=76281), FastestLapEvent(lap=62, driver='SAI', time=74.726, lap_time_ms=74726), FastestLapEvent(lap=64, driver='NOR', time=75.742, lap_time_ms=75742), FastestLapEvent(lap=73, driver='RUS', time=75.228, lap_time_ms=75228), FastestLapEvent(lap=58, driver='VER', time=74.569, lap_time_ms=74569), FastestLapEvent(lap=63, driver='HAM', time=74.165, lap_time_ms=74165), FastestLapEvent(lap=77, driver='TSU', time=74.72, lap_time_ms=74720), FastestLapEvent(lap=77, driver='ALB', time=77.06, lap_time_ms=77060), FastestLapEvent(lap=77, driver='GAS', time=75.625, lap_time_ms=75625), FastestLapEvent(lap=68, driver='ALO', time=77.939, lap_time_ms=77939), FastestLapEvent(lap=46, driver='RIC', time=77.172, lap_time_ms=77172), FastestLapEvent(lap=17, driver='BOT', time=76.561, lap_time_ms=76561), FastestLapEvent(lap=59, driver='STR', time=76.71, lap_time_ms=76710), FastestLapEvent(lap=62, driver='SAR', time=75.525, lap_time_ms=75525), FastestLapEvent(lap=75, driver='ZHO', time=74.718, lap_time_ms=74718)], position_history=[PositionSnapshot(time=8847.137, lap=None, standings=[PositionEntry(position=1, driver='LEC', gap=25.0), PositionEntry(position=2, driver='PIA', gap=18.0), PositionEntry(position=3, driver='SAI', gap=15.0), PositionEntry(position=4, driver='NOR', gap=12.0), PositionEntry(position=5, driver='RUS', gap=10.0), PositionEntry(position=6, driver='VER', gap=8.0), PositionEntry(position=7, driver='HAM', gap=7.0), PositionEntry(position=8, driver='TSU', gap=4.0), PositionEntry(position=9, driver='ALB', gap=2.0), PositionEntry(position=10, driver='GAS', gap=1.0), PositionEntry(position=11, driver='ALO', gap=0.0), PositionEntry(position=12, driver='RIC', gap=0.0), PositionEntry(position=13, driver='BOT', gap=0.0), PositionEntry(position=14, driver='STR', gap=0.0), PositionEntry(position=15, driver='SAR', gap=0.0), PositionEntry(position=16, driver='ZHO', gap=0.0), PositionEntry(position=17, driver='OCO', gap=0.0), PositionEntry(position=18, driver='PER', gap=0.0), PositionEntry(position=19, driver='HUL', gap=0.0), PositionEntry(position=20, driver='MAG', gap=0.0)])])

In [13]:
race = loader.load_session(2024, 8, "Race") # , force_update=True

✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded weekend from cache: Monaco Grand Prix
✓ Loaded seasons from cache: [2020, 2021, 2022, 2023, 2024, 2025]
✓ Loaded session from cache: Race

In [39]:
import pandas as pd
pd.set_option('display.max_rows', 1000, 'display.max_columns', 500)
race.telemetry["MAG"].to_pandas().head(500)

,Date,SessionTime,DriverAhead,DistanceToDriverAhead,Time,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Distance,RelativeDistance,Status,X,Y,Z,LapNumber,SessionSeconds,session_time,progress,TimeToDriverAhead
0,2024-05-26 13:03:11.069,0 days 00:55:05.680000,,0.159444,0 days 00:00:00,10899.543750,0.000000,1,22.000000,False,1,interpolation,0.001317,0.000002,OnTrack,-7364.008124,-8260.987637,503.000000,1.0,3305.680,0.000,0.001317,-0.290301
1,2024-05-26 13:03:11.156,0 days 00:55:05.767000,,0.159444,0 days 00:00:00.087000,10899.000000,0.000000,1,22.000000,False,1,car,0.000000,0.000000,OnTrack,-7364.012660,-8260.980698,503.000000,1.0,3305.767,0.087,0.000000,NaN
2,2024-05-26 13:03:11.230,0 days 00:55:05.841000,,0.159444,0 days 00:00:00.161000,10804.649837,0.000000,1,22.000000,False,1,pos,-0.003475,-0.000004,OnTrack,-7364.000000,-8261.000000,503.000000,1.0,3305.841,0.161,-0.003475,NaN
3,2024-05-26 13:03:11.356,0 days 00:55:05.967000,23,0.159444,0 days 00:00:00.287000,10644.000000,0.000000,1,22.000000,False,1,car,0.000000,0.000000,OnTrack,-7363.944648,-8261.084389,503.000000,1.0,3305.967,0.287,0.000000,NaN
4,2024-05-26 13:03:11.469,0 days 00:55:06.080000,23,0.103141,0 days 00:00:00.400000,10050.750336,1.059374,1,22.706250,False,1,pos,0.035843,0.000046,OnTrack,-7364.000000,-8261.000000,503.000000,1.0,3306.080,0.400,0.035843,0.023165
5,2024-05-26 13:03:11.676,0 days 00:55:06.287000,16,0.000000,0 days 00:00:00.607000,8964.000000,3.000000,1,24.000000,False,1,car,0.266667,0.000345,OnTrack,-7364.685201,-8259.788563,503.000000,1.0,3306.287,0.607,0.266667,NaN
6,2024-05-26 13:03:11.729,0 days 00:55:06.340000,16,0.000000,0 days 00:00:00.660000,8593.000448,4.703569,1,24.189285,False,1,pos,0.385624,0.000499,OnTrack,-7365.000000,-8259.000000,503.000000,1.0,3306.340,0.660,0.385624,0.001857
7,2024-05-26 13:03:11.949,0 days 00:55:06.560000,16,0.000000,0 days 00:00:00.880000,7053.000448,11.774998,1,24.975000,False,1,pos,1.166636,0.001509,OnTrack,-7367.000000,-8253.000000,503.000000,1.0,3306.560,0.880,1.166636,0.000692
8,2024-05-26 13:03:11.956,0 days 00:55:06.567000,16,0.000000,0 days 00:00:00.887000,7004.000000,12.000000,1,25.000000,False,1,car,1.200000,0.001552,OnTrack,-7367.085250,-8252.733407,503.000000,1.0,3306.567,0.887,1.200000,0.019097
9,2024-05-26 13:03:12.209,0 days 00:55:06.820000,16,0.134845,0 days 00:00:01.140000,5531.065998,19.906248,1,25.000000,False,1,pos,2.719055,0.003517,OnTrack,-7371.000000,-8240.000000,503.000000,1.0,3306.820,1.140,2.719055,0.024172
10,2024-05-26 13:03:12.276,0 days 00:55:06.887000,23,0.170556,0 days 00:00:01.207000,5141.000000,22.000000,1,25.000000,False,1,car,3.155556,0.004081,OnTrack,-7372.223668,-8235.687827,503.000019,1.0,3306.887,1.207,3.155556,0.024108
11,2024-05-26 13:03:12.410,0 days 00:55:07.021000,23,0.100950,0 days 00:00:01.341000,5353.389797,24.009998,1,29.019996,False,1,pos,4.034001,0.005217,OnTrack,-7375.000000,-8226.000000,503.000000,1.0,3307.021,1.341,4.034001,0.003181
12,2024-05-26 13:03:12.476,0 days 00:55:07.087000,27,0.066667,0 days 00:00:01.407000,5458.000000,25.000000,1,31.000000,False,1,car,4.544444,0.005878,OnTrack,-7376.627692,-8220.774275,502.999895,1.0,3307.087,1.407,4.544444,0.007952
13,2024-05-26 13:03:12.569,0 days 00:55:07.180000,27,0.040833,0 days 00:00:01.500000,5793.729769,30.114996,1,32.394999,False,1,pos,5.404591,0.006990,OnTrack,-7379.000000,-8213.000000,503.000000,1.0,3307.180,1.500,5.404591,0.006602
14,2024-05-26 13:03:12.676,0 days 00:55:07.287000,27,0.011111,0 days 00:00:01.607000,6180.000000,36.000000,1,34.000000,False,1,car,6.544444,0.008464,OnTrack,-7381.422761,-8203.637207,503.001188,1.0,3307.287,1.607,6.544444,0.001090
15,2024-05-26 13:03:12.789,0 days 00:55:07.400000,27,0.048778,0 days 00:00:01.720000,6674.374720,39.954998,1,37.389998,False,1,pos,7.851959,0.010155,OnTrack,-7385.000000,-8190.000000,503.000000,1.0,3307.400,1.720,7.851959,0.014185
16,2024-05-26 13:03:12.876,0 days 00:55:07.487000,55,0.077778,0 days 00:00:01.807000,7055.000000,43.000000,1,40.000000,False,1,car,8.933333,0.011554,OnTrack,-7389.487405,-8174.466621,502.994651,1.0,3307.487,1.807,8.933333,0.007430
17,2024-05-26 13:03:13.069,0 days 00:55:07.680000,55,0.024167,0 days 00:00:02,7819.762246,48.629165,1,40.000000,False,1,pos,11.571808,0.014966,OnTrack,-7401.000000,-8136.000000,503.000000,1.0,3307.680,2.000,11.571808,0.022849
18,2024-05-26 13:03:13.116,0 days 00:55:07.727000,55,0.011111,0 days 00:00:02.047000,8006.000000,50.000000,1,40.000000,False,1,car,12.266667,0.015865,OnTrack,-7402.858439,-8129.656436,503.015183,1.0,3307.727,2.047,12.266667,0.000729
19,2024-05-26 13:03:13.389,0 days 00:55:08,55,0.129074,0 days 00:00:02.320000,8347.249920,58.341665,1,47.583332,False,1,pos,16.739402,0.021650,OnTrack,-7410.000000,-8104.000000,503.000000,1.0,3308.000,2.320,16.739402,0.006370
20,2024-05-26 13:03:13.476,0 days 00:55:08.087000,11,0.166667,0 days 00:00:02.407000,8456.000000,61.000000,1,50.000000,False,1,car,18.366667,0.023755,OnTrack,-7414.285124,-8088.982333,502.803323,1.0,3308.087,2.407,18.366667,0.008623
21,2024-05-26 13:03:13.716,0 days 00:55:08.327000,23,0.181667,0 days 00:00:02.647000,9046.000000,76.000000,1,50.000000,False,1,car,23.433333,0.030308,OnTrack,-7430.975469,-8030.640622,502.027879,1.0,3308.327,2.647,23.433333,0.009343
22,2024-05-26 13:03:13.730,0 days 00:55:08.341000,23,0.190086,0 days 00:00:02.661000,9142.074122,76.524995,1,50.419996,False,1,pos,23.755953,0.030725,OnTrack,-7432.000000,-8027.000000,502.000000,1.0,3308.341,2.661,23.755953,0.007354
23,2024-05-26 13:03:14.116,0 days 00:55:08.727000,2,0.422222,0 days 00:00:03.047000,11791.000000,91.000000,1,62.000000,False,1,car,33.544444,0.043385,OnTrack,-7459.857693,-7925.798256,501.988750,1.0,3308.727,3.047,33.544444,0.017813
24,2024-05-26 13:03:14.150,0 days 00:55:08.761000,2,0.393889,0 days 00:00:03.081000,11582.749216,92.062504,1,62.637502,False,1,pos,34.433206,0.044534,OnTrack,-7462.000000,-7918.000000,502.000000,1.0,3308.761,3.081,34.433206,0.015559
25,2024-05-26 13:03:14.276,0 days 00:55:08.887000,2,0.288889,0 days 00:00:03.207000,10811.000000,96.000000,1,65.000000,False,1,car,37.811111,0.048903,OnTrack,-7469.298817,-7891.544222,502.016877,1.0,3308.887,3.207,37.811111,0.011121
26,2024-05-26 13:03:14.490,0 days 00:55:09.101000,2,0.369074,0 days 00:00:03.421000,10505.000122,106.666662,1,70.333331,False,1,pos,44.379712,0.057399,OnTrack,-7481.000000,-7848.000000,502.000000,1.0,3309.101,3.421,44.379712,0.022272
27,2024-05-26 13:03:14.597,0 days 00:55:09.208000,81,0.409167,0 days 00:00:03.528000,10352.000000,112.000000,2,73.000000,False,1,car,47.797778,0.061820,OnTrack,-7487.687012,-7821.780115,501.999704,1.0,3309.208,3.528,47.797778,0.013749
28,2024-05-26 13:03:14.630,0 days 00:55:09.241000,81,0.354166,0 days 00:00:03.561000,10485.238275,112.550003,2,73.137501,False,1,pos,48.845859,0.063175,OnTrack,-7490.000000,-7813.000000,502.000000,1.0,3309.241,3.561,48.845859,0.011529
29,2024-05-26 13:03:14.837,0 days 00:55:09.448000,81,0.009167,0 days 00:00:03.768000,11321.000000,116.000000,2,74.000000,False,1,car,55.531111,0.071822,OnTrack,-7507.733359,-7748.781655,502.000211,1.0,3309.448,3.768,55.531111,0.000299
30,2024-05-26 13:03:14.850,0 days 00:55:09.461000,81,0.039026,0 days 00:00:03.781000,11285.981422,116.690622,2,74.365623,False,1,pos,55.976411,0.072398,OnTrack,-7509.000000,-7744.000000,502.000000,1.0,3309.461,3.781,55.976411,0.001587
31,2024-05-26 13:03:15.157,0 days 00:55:09.768000,11,0.744167,0 days 00:00:04.088000,10459.000000,133.000000,3,83.000000,False,1,car,67.353333,0.087112,OnTrack,-7540.846758,-7614.837440,501.998566,1.0,3309.768,4.088,67.353333,0.018938
32,2024-05-26 13:03:15.170,0 days 00:55:09.781000,11,0.701321,0 days 00:00:04.101000,10481.814888,133.519997,3,83.779996,False,1,pos,67.853521,0.087759,OnTrack,-7542.000000,-7610.000000,502.000000,1.0,3309.781,4.101,67.853521,0.019978
33,2024-05-26 13:03:15.357,0 days 00:55:09.968000,63,0.085000,0 days 00:00:04.288000,10810.000000,141.000000,3,95.000000,False,1,car,75.186667,0.097243,OnTrack,-7555.673301,-7551.590816,502.037542,1.0,3309.968,4.288,75.186667,0.002121
34,2024-05-26 13:03:15.490,0 days 00:55:10.101000,63,0.195833,0 days 00:00:04.421000,10716.900045,147.649997,3,98.324998,False,1,pos,80.671788,0.104338,OnTrack,-7565.000000,-7508.000000,502.000000,1.0,3310.101,4.421,80.671788,0.005200
35,2024-05-26 13:03:15.557,0 days 00:55:10.168000,63,0.251667,0 days 00:00:04.488000,10670.000000,151.000000,3,100.000000,False,1,car,83.575556,0.108093,OnTrack,-7570.284639,-7481.797117,501.940514,1.0,3310.168,4.488,83.575556,0.005744
36,2024-05-26 13:03:15.709,0 days 00:55:10.320000,63,0.198985,0 days 00:00:04.640000,10751.872727,158.945455,3,100.000000,False,1,pos,90.588513,0.117163,OnTrack,-7583.000000,-7415.000000,502.000000,1.0,3310.320,4.640,90.588513,0.003823
37,2024-05-26 13:03:15.890,0 days 00:55:10.501000,63,0.136252,0 days 00:00:04.821000,10849.365875,168.406815,3,100.000000,False,1,pos,99.537264,0.128737,OnTrack,-7597.000000,-7333.000000,503.000000,1.0,3310.501,4.821,99.537264,0.004834
38,2024-05-26 13:03:15.997,0 days 00:55:10.608000,44,0.099167,0 days 00:00:04.928000,10907.000000,174.000000,4,100.000000,False,1,car,104.842222,0.135599,OnTrack,-7603.987895,-7286.661126,503.243499,1.0,3310.608,4.928,104.842222,0.002052
39,2024-05-26 13:03:16.157,0 days 00:55:10.768000,14,0.400833,0 days 00:00:05.088000,11279.000000,178.000000,4,100.000000,False,1,car,112.753333,0.145830,OnTrack,-7614.069019,-7207.148040,503.033494,1.0,3310.768,5.088,112.753333,0.009133
40,2024-05-26 13:03:16.170,0 days 00:55:10.781000,14,0.388279,0 days 00:00:05.101000,11220.756573,178.000000,4,100.000000,False,1,pos,113.396947,0.146663,OnTrack,-7615.000000,-7199.000000,503.000000,1.0,3310.781,5.101,113.396947,0.007412
41,2024-05-26 13:03:16.436,0 days 00:55:11.047000,18,0.131389,0 days 00:00:05.367000,10029.000000,178.000000,4,100.000000,False,1,car,126.548333,0.163672,OnTrack,-7636.044016,-6993.378364,502.035510,1.0,3311.047,5.367,126.548333,0.002545
42,2024-05-26 13:03:16.450,0 days 00:55:11.061000,18,0.140510,0 days 00:00:05.381000,10045.799846,178.000000,4,100.000000,False,1,pos,127.232176,0.164557,OnTrack,-7637.000000,-6983.000000,502.000000,1.0,3311.061,5.381,127.232176,0.003750
43,2024-05-26 13:03:16.876,0 days 00:55:11.487000,2,0.418056,0 days 00:00:05.807000,10557.000000,178.000000,5,100.000000,False,1,car,148.303889,0.191810,OnTrack,-7654.669862,-6744.236791,501.993483,1.0,3311.487,5.807,148.303889,0.007556
44,2024-05-26 13:03:16.889,0 days 00:55:11.500000,2,0.428889,0 days 00:00:05.820000,10588.606094,179.787491,5,100.000000,False,1,pos,149.003886,0.192715,OnTrack,-7655.000000,-6739.000000,502.000000,1.0,3311.500,5.820,149.003886,0.007982
45,2024-05-26 13:03:17.036,0 days 00:55:11.647000,2,0.551389,0 days 00:00:05.967000,10946.000000,200.000000,5,100.000000,False,1,car,157.192778,0.203307,OnTrack,-7658.157279,-6687.618848,502.047792,1.0,3311.647,5.967,157.192778,0.009775
46,2024-05-26 13:03:17.210,0 days 00:55:11.821000,2,0.213056,0 days 00:00:06.141000,11184.006968,206.214281,5,81.978585,False,1,pos,167.255684,0.216322,OnTrack,-7662.000000,-6624.000000,502.000000,1.0,3311.821,6.141,167.255684,0.006818
47,2024-05-26 13:03:17.316,0 days 00:55:11.927000,2,0.006944,0 days 00:00:06.247000,11329.000000,210.000000,5,71.000000,False,1,car,173.526111,0.224431,OnTrack,-7665.305111,-6570.558813,501.889015,1.0,3311.927,6.247,173.526111,0.000125
48,2024-05-26 13:03:17.449,0 days 00:55:12.060000,2,0.941638,0 days 00:00:06.380000,11259.175034,214.156248,5,46.893762,False,1,pos,181.484877,0.234725,OnTrack,-7670.000000,-6494.000000,502.000000,1.0,3312.060,6.380,181.484877,0.024948
49,2024-05-26 13:03:17.476,0 days 00:55:12.087000,18,1.131389,0 days 00:00:06.407000,11245.000000,215.000000,5,42.000000,True,1,car,183.081667,0.236790,OnTrack,-7670.946955,-6478.202842,502.111998,1.0,3312.087,6.407,183.081667,0.021849
50,2024-05-26 13:03:17.629,0 days 00:55:12.240000,18,2.944456,0 days 00:00:06.560000,10471.075324,210.218752,5,28.612506,True,1,pos,191.911378,0.248210,OnTrack,-7676.000000,-6388.000000,503.000000,1.0,3312.240,6.560,191.911378,0.010194
51,2024-05-26 13:03:17.929,0 days 00:55:12.540000,18,6.499491,0 days 00:00:06.860000,8953.575324,200.843752,5,2.362506,True,1,pos,208.312343,0.269423,OnTrack,-7680.000000,-6218.000000,503.000000,1.0,3312.540,6.860,208.312343,0.127364
52,2024-05-26 13:03:17.956,0 days 00:55:12.567000,27,6.819444,0 days 00:00:06.887000,8817.000000,200.000000,6,0.000000,True,1,car,209.748333,0.271280,OnTrack,-7679.610180,-6203.472663,502.990013,1.0,3312.567,6.887,209.748333,0.127605
53,2024-05-26 13:03:18.090,0 days 00:55:12.701000,27,6.745000,0 days 00:00:07.021000,8482.000320,189.950010,6,0.000000,True,1,pos,216.771101,0.280363,OnTrack,-7676.000000,-6130.000000,503.000000,1.0,3312.701,7.021,216.771101,0.130084
54,2024-05-26 13:03:18.116,0 days 00:55:12.727000,27,6.730556,0 days 00:00:07.047000,8417.000000,188.000000,6,0.000000,True,1,car,218.103889,0.282087,OnTrack,-7675.150991,-6114.201061,503.002441,1.0,3312.727,7.047,218.103889,0.130417
55,2024-05-26 13:03:18.390,0 days 00:55:13.001000,27,6.121666,0 days 00:00:07.321000,8830.740193,177.724995,6,0.000000,True,1,pos,231.478359,0.299385,OnTrack,-7665.000000,-5936.000000,503.000000,1.0,3313.001,7.321,231.478359,0.131577
56,2024-05-26 13:03:18.516,0 days 00:55:13.127000,27,5.841667,0 days 00:00:07.447000,9021.000000,173.000000,6,0.000000,True,1,car,237.326111,0.306948,OnTrack,-7660.798350,-5879.347621,502.998756,1.0,3313.127,7.447,237.326111,0.132220
57,2024-05-26 13:03:18.789,0 days 00:55:13.400000,27,5.310833,0 days 00:00:07.720000,9747.374830,161.300003,6,0.000000,True,1,pos,249.540331,0.322745,OnTrack,-7652.000000,-5788.000000,503.000000,1.0,3313.400,7.720,249.540331,0.124141
58,2024-05-26 13:03:18.796,0 days 00:55:13.407000,27,5.297222,0 days 00:00:07.727000,9766.000000,161.000000,6,0.000000,True,1,car,249.848333,0.323143,OnTrack,-7651.743072,-5785.109934,502.999973,1.0,3313.407,7.727,249.848333,0.123947
59,2024-05-26 13:03:18.890,0 days 00:55:13.501000,27,5.010000,0 days 00:00:07.821000,9631.714469,159.321431,6,0.000000,True,1,pos,253.965659,0.328469,OnTrack,-7648.000000,-5744.000000,503.000000,1.0,3313.501,7.821,253.965659,0.121769
60,2024-05-26 13:03:19.076,0 days 00:55:13.687000,27,4.441667,0 days 00:00:08.007000,9366.000000,156.000000,4,0.000000,True,1,car,261.981667,0.338836,OnTrack,-7637.857775,-5663.857565,503.492422,1.0,3313.687,8.007,261.981667,0.111320
61,2024-05-26 13:03:19.109,0 days 00:55:13.720000,27,4.340834,0 days 00:00:08.040000,9318.150093,154.762502,4,0.000000,True,1,pos,263.379629,0.340644,OnTrack,-7636.000000,-5650.000000,504.000000,1.0,3313.720,8.040,263.379629,0.109283
62,2024-05-26 13:03:19.236,0 days 00:55:13.847000,27,3.952778,0 days 00:00:08.167000,9134.000000,150.000000,4,0.000000,True,1,car,268.648333,0.347459,OnTrack,-7629.100531,-5597.681796,507.467564,1.0,3313.847,8.167,268.648333,0.102913
63,2024-05-26 13:03:19.290,0 days 00:55:13.901000,27,3.712778,0 days 00:00:08.221000,9113.300049,147.450006,4,0.000000,True,1,pos,270.797516,0.350238,OnTrack,-7626.000000,-5576.000000,509.000000,1.0,3313.901,8.221,270.797516,0.100958
64,2024-05-26 13:03:19.510,0 days 00:55:14.121000,27,2.734999,0 days 00:00:08.441000,9028.966618,137.061105,4,0.000000,True,1,pos,278.972551,0.360812,OnTrack,-7612.000000,-5492.000000,513.000000,1.0,3314.121,8.441,278.972551,0.083238
65,2024-05-26 13:03:19.596,0 days 00:55:14.207000,27,2.352778,0 days 00:00:08.527000,8996.000000,133.000000,4,0.000000,True,1,car,281.948333,0.364660,OnTrack,-7606.944564,-5461.818037,513.512035,1.0,3314.207,8.527,281.948333,0.076861
66,2024-05-26 13:03:19.710,0 days 00:55:14.321000,27,2.036111,0 days 00:00:08.641000,8638.680849,126.587493,4,0.000000,True,1,pos,285.713611,0.369530,OnTrack,-7600.000000,-5422.000000,514.000000,1.0,3314.321,8.641,285.713611,0.066916
67,2024-05-26 13:03:19.916,0 days 00:55:14.527000,27,1.463889,0 days 00:00:08.847000,7993.000000,115.000000,3,0.000000,True,1,car,292.170556,0.377881,OnTrack,-7583.765475,-5342.761992,516.968800,1.0,3314.527,8.847,292.170556,0.050996
68,2024-05-26 13:03:20.050,0 days 00:55:14.661000,27,0.942778,0 days 00:00:08.981000,8224.987278,110.812504,3,0.000000,True,1,pos,296.287042,0.383205,OnTrack,-7574.000000,-5298.000000,519.000000,1.0,3314.661,8.981,296.287042,0.035098
69,2024-05-26 13:03:20.076,0 days 00:55:14.687000,27,0.841667,0 days 00:00:09.007000,8270.000000,110.000000,3,0.000000,True,1,car,297.059444,0.384204,OnTrack,-7572.400963,-5290.721922,519.312964,1.0,3314.687,9.007,297.059444,0.032299
70,2024-05-26 13:03:20.370,0 days 00:55:14.981000,27,1.510554,0 days 00:00:09.301000,7279.955431,99.710004,3,0.000000,True,1,pos,305.043610,0.394531,OnTrack,-7558.000000,-5228.000000,521.000000,1.0,3314.981,9.301,305.043610,NaN
71,2024-05-26 13:03:20.476,0 days 00:55:15.087000,,1.751718,0 days 00:00:09.407000,6923.000000,96.000000,2,0.000000,True,1,car,307.726111,0.398000,OnTrack,-7551.600321,-5202.541051,520.757873,1.0,3315.087,9.407,307.726111,NaN
72,2024-05-26 13:03:20.650,0 days 00:55:15.261000,,2.147589,0 days 00:00:09.581000,7235.329770,89.040005,2,0.000000,True,1,pos,311.995250,0.403522,OnTrack,-7541.000000,-5159.000000,520.000000,1.0,3315.261,9.581,311.995250,NaN
73,2024-05-26 13:03:20.676,0 days 00:55:15.287000,,2.206743,0 days 00:00:09.607000,7282.000000,88.000000,2,0.000000,True,1,car,312.615000,0.404323,OnTrack,-7539.730328,-5153.067475,519.941366,1.0,3315.287,9.607,312.615000,NaN
74,2024-05-26 13:03:20.770,0 days 00:55:15.381000,,2.420605,0 days 00:00:09.701000,7046.412821,85.062504,2,0.587499,True,1,pos,314.811892,0.407165,OnTrack,-7535.000000,-5131.000000,520.000000,1.0,3315.381,9.701,314.811892,NaN
75,2024-05-26 13:03:20.836,0 days 00:55:15.447000,,2.570763,0 days 00:00:09.767000,6881.000000,83.000000,2,1.000000,True,1,car,316.303889,0.409094,OnTrack,-7530.018312,-5111.452291,520.543036,1.0,3315.447,9.767,316.303889,NaN
76,2024-05-26 13:03:21.009,0 days 00:55:15.620000,,2.964360,0 days 00:00:09.940000,6765.810498,79.117208,2,6.177056,True,1,pos,319.988351,0.413860,OnTrack,-7514.000000,-5055.000000,523.000000,1.0,3315.620,9.940,319.988351,NaN
77,2024-05-26 13:03:21.237,0 days 00:55:15.848000,,3.483089,0 days 00:00:10.168000,6614.000000,74.000000,2,13.000000,True,1,car,324.546667,0.419755,OnTrack,-7503.230128,-5017.682809,524.381109,1.0,3315.848,10.168,324.546667,NaN
78,2024-05-26 13:03:21.450,0 days 00:55:16.061000,,3.967691,0 days 00:00:10.381000,6511.641697,72.225001,2,9.450001,True,1,pos,328.761649,0.425207,OnTrack,-7496.000000,-4992.000000,525.000000,1.0,3316.061,10.381,328.761649,NaN
79,2024-05-26 13:03:21.597,0 days 00:55:16.208000,,4.302135,0 days 00:00:10.528000,6441.000000,71.000000,2,7.000000,True,1,car,331.646667,0.428938,OnTrack,-7487.994661,-4963.433159,525.816060,1.0,3316.208,10.528,331.646667,NaN
80,2024-05-26 13:03:21.630,0 days 00:55:16.241000,,4.377215,0 days 00:00:10.561000,6448.095041,70.834999,2,8.155007,True,1,pos,332.291521,0.429772,OnTrack,-7486.000000,-4957.000000,526.000000,1.0,3316.241,10.561,332.291521,NaN
81,2024-05-26 13:03:21.790,0 days 00:55:16.401000,,4.741235,0 days 00:00:10.721000,6482.495041,70.034999,2,13.755007,True,1,pos,335.400439,0.433793,OnTrack,-7476.000000,-4928.000000,527.000000,1.0,3316.401,10.721,335.400439,NaN
82,2024-05-26 13:03:21.797,0 days 00:55:16.408000,,4.757161,0 days 00:00:10.728000,6484.000000,70.000000,2,14.000000,True,1,car,335.535556,0.433968,OnTrack,-7475.584747,-4926.741905,527.069296,1.0,3316.408,10.728,335.535556,NaN
83,2024-05-26 13:03:21.950,0 days 00:55:16.561000,,5.105256,0 days 00:00:10.881000,6185.649626,69.043749,2,15.912502,True,1,pos,338.468914,0.437762,OnTrack,-7467.000000,-4899.000000,529.000000,1.0,3316.561,10.881,338.468914,NaN
84,2024-05-26 13:03:21.957,0 days 00:55:16.568000,,5.121181,0 days 00:00:10.888000,6172.000000,69.000000,2,16.000000,True,1,car,338.602222,0.437934,OnTrack,-7466.603453,-4897.737056,529.078794,1.0,3316.568,10.888,338.602222,NaN

In [40]:
# Check columns after loading
tel = race.telemetry["MAG"]
print("Columns:", tel.columns)
print("Shape:", tel.shape)
print(tel.select(['session_time', 'progress', 'status']).head(20))

Columns: ['Date', 'SessionTime', 'DriverAhead', 'DistanceToDriverAhead', 'Time', 'RPM', 'Speed', 'nGear', 'Throttle', 'Brake', 'DRS', 'Source', 'Distance', 'RelativeDistance', 'Status', 'X', 'Y', 'Z', 'LapNumber', 'SessionSeconds', 'session_time', 'progress', 'TimeToDriverAhead']
Shape: (18711, 23)

ColumnNotFoundError: unable to find column "status"; valid columns: ["Date", "SessionTime", "DriverAhead", "DistanceToDriverAhead", "Time", "RPM", "Speed", "nGear", "Throttle", "Brake", "DRS", "Source", "Distance", "RelativeDistance", "Status", "X", "Y", "Z", "LapNumber", "SessionSeconds", "session_time", "progress", "TimeToDriverAhead"]

In [31]:
help(race)

Help on SessionData in module f1_race.data_loader.data_models object:

class SessionData(builtins.object)
 |  SessionData(metadata: f1_race.data_loader.data_models.SessionMetadata, telemetry: Dict[str, polars.dataframe.frame.DataFrame] = <factory>, events: f1_race.data_loader.data_models.EventsData = <factory>, results: f1_race.data_loader.data_models.ResultsData = <factory>, order: polars.dataframe.frame.DataFrame = <factory>, rain_events: polars.dataframe.frame.DataFrame = <factory>) -> None
 |
 |  Complete immutable data for one session.
 |
 |  Methods defined here:
 |
 |  __delattr__(self, name)
 |      Implement delattr(self, name).
 |
 |  __eq__(self, other)
 |      Return self==value.
 |
 |  __hash__(self)
 |      Return hash(self).
 |
 |  __init__(self, metadata: f1_race.data_loader.data_models.SessionMetadata, telemetry: Dict[str, polars.dataframe.frame.DataFrame] = <factory>, events: f1_race.data_loader.data_models.EventsData = <factory>, results: f1_race.data_loader.data_models.ResultsData = <factory>, order: polars.dataframe.frame.DataFrame = <factory>, rain_events: polars.dataframe.frame.DataFrame = <factory>) -> None
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  __setattr__(self, name, value)
 |      Implement setattr(self, name, value).
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {'events': <class 'f1_race.data_loader.data_models.E...
 |
 |  __dataclass_fields__ = {'events': Field(name='events',type=<class 'f1_...
 |
 |  __dataclass_params__ = _DataclassParams(init=True,repr=True,eq=True,or...
 |
 |  __match_args__ = ('metadata', 'telemetry', 'events', 'results', 'order...

In [13]:
import polars as pl
with pl.Config(tbl_rows=100, tbl_width_chars=50, tbl_cols=-1):
    display(race.events.track_status)
# race.events.race_control
# race.events.weather

shape: (97, 4)
┌────────────┬────────────┬─────────┬────────────┐
│ status     ┆ message    ┆ time    ┆ session_ti │
│ ---        ┆ ---        ┆ ---     ┆ me         │
│ str        ┆ str        ┆ f64     ┆ ---        │
│            ┆            ┆         ┆ f64        │
╞════════════╪════════════╪═════════╪════════════╡
│ GREEN      ┆ GREEN      ┆ 44400.0 ┆ -2400.0    │
│            ┆ LIGHT -    ┆         ┆            │
│            ┆ PIT EXIT   ┆         ┆            │
│            ┆ OPEN       ┆         ┆            │
│ DOUBLE     ┆ DOUBLE     ┆ 45065.0 ┆ -1735.0    │
│ YELLOW     ┆ YELLOW IN  ┆         ┆            │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR …   ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 45094.0 ┆ -1706.0    │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 7   ┆         ┆            │
│ DOUBLE     ┆ DOUBLE     ┆ 45726.0 ┆ -1074.0    │
│ YELLOW     ┆ YELLOW IN  ┆         ┆            │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR …   ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 45781.0 ┆ -1019.0    │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 12  ┆         ┆            │
│ GREEN      ┆ GREEN      ┆ 46991.0 ┆ 191.0      │
│            ┆ LIGHT -    ┆         ┆            │
│            ┆ PIT EXIT   ┆         ┆            │
│            ┆ OPEN       ┆         ┆            │
│ DOUBLE     ┆ DOUBLE     ┆ 47016.0 ┆ 216.0      │
│ YELLOW     ┆ YELLOW IN  ┆         ┆            │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR …   ┆         ┆            │
│ YELLOW     ┆ YELLOW IN  ┆ 47018.0 ┆ 218.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 6   ┆         ┆            │
│ YELLOW     ┆ YELLOW IN  ┆ 47019.0 ┆ 219.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 4   ┆         ┆            │
│ DOUBLE     ┆ DOUBLE     ┆ 47019.0 ┆ 219.0      │
│ YELLOW     ┆ YELLOW IN  ┆         ┆            │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR …   ┆         ┆            │
│ YELLOW     ┆ YELLOW IN  ┆ 47024.0 ┆ 224.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 5   ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 47035.0 ┆ 235.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 6   ┆         ┆            │
│ YELLOW     ┆ YELLOW IN  ┆ 47037.0 ┆ 237.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 6   ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 47041.0 ┆ 241.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 5   ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 47042.0 ┆ 242.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 6   ┆         ┆            │
│ DOUBLE     ┆ DOUBLE     ┆ 47043.0 ┆ 243.0      │
│ YELLOW     ┆ YELLOW IN  ┆         ┆            │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR …   ┆         ┆            │
│ YELLOW     ┆ YELLOW IN  ┆ 47044.0 ┆ 244.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 9   ┆         ┆            │
│ YELLOW     ┆ YELLOW IN  ┆ 47045.0 ┆ 245.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 11  ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 47045.0 ┆ 245.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 10  ┆         ┆            │
│ RED        ┆ RED FLAG   ┆ 47048.0 ┆ 248.0      │
│ CLEAR      ┆ CLEAR IN   ┆ 47048.0 ┆ 248.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 3   ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 47048.0 ┆ 248.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 4   ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 47048.0 ┆ 248.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 9   ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 47048.0 ┆ 248.0      │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 11  ┆         ┆            │
│ CLEAR      ┆ TRACK      ┆ 48944.0 ┆ 2144.0     │
│            ┆ CLEAR      ┆         ┆            │
│ DOUBLE     ┆ DOUBLE     ┆ 48987.0 ┆ 2187.0     │
│ YELLOW     ┆ YELLOW IN  ┆         ┆            │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR …   ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 49012.0 ┆ 2212.0     │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 13  ┆         ┆            │
│ DOUBLE     ┆ DOUBLE     ┆ 49103.0 ┆ 2303.0     │
│ YELLOW     ┆ YELLOW IN  ┆         ┆            │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR …   ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 49167.0 ┆ 2367.0     │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 3   ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52647.0 ┆ 5847.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 77     ┆         ┆            │
│            ┆ (BO…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52658.0 ┆ 5858.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 77     ┆         ┆            │
│            ┆ (BO…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52666.0 ┆ 5866.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 77     ┆         ┆            │
│            ┆ (BO…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52703.0 ┆ 5903.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52709.0 ┆ 5909.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52716.0 ┆ 5916.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52729.0 ┆ 5929.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52735.0 ┆ 5935.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 3      ┆         ┆            │
│            ┆ (RIC…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52736.0 ┆ 5936.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52772.0 ┆ 5972.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 14     ┆         ┆            │
│            ┆ (AL…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52776.0 ┆ 5976.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 3      ┆         ┆            │
│            ┆ (RIC…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52797.0 ┆ 5997.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 14     ┆         ┆            │
│            ┆ (AL…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 52898.0 ┆ 6098.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 18     ┆         ┆            │
│            ┆ (ST…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53341.0 ┆ 6541.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53355.0 ┆ 6555.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53369.0 ┆ 6569.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53373.0 ┆ 6573.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 77     ┆         ┆            │
│            ┆ (BO…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53377.0 ┆ 6577.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53384.0 ┆ 6584.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53399.0 ┆ 6599.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53496.0 ┆ 6696.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 10     ┆         ┆            │
│            ┆ (GA…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53521.0 ┆ 6721.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 10     ┆         ┆            │
│            ┆ (GA…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53543.0 ┆ 6743.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 10     ┆         ┆            │
│            ┆ (GA…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53586.0 ┆ 6786.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 3      ┆         ┆            │
│            ┆ (RIC…      ┆         ┆            │
│ DOUBLE     ┆ DOUBLE     ┆ 53612.0 ┆ 6812.0     │
│ YELLOW     ┆ YELLOW IN  ┆         ┆            │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR …   ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53613.0 ┆ 6813.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 14     ┆         ┆            │
│            ┆ (AL…       ┆         ┆            │
│ CLEAR      ┆ CLEAR IN   ┆ 53616.0 ┆ 6816.0     │
│            ┆ TRACK      ┆         ┆            │
│            ┆ SECTOR 13  ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53733.0 ┆ 6933.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 18     ┆         ┆            │
│            ┆ (ST…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53734.0 ┆ 6934.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 23     ┆         ┆            │
│            ┆ (AL…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53755.0 ┆ 6955.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53759.0 ┆ 6959.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 23     ┆         ┆            │
│            ┆ (AL…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53761.0 ┆ 6961.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53766.0 ┆ 6966.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 18     ┆         ┆            │
│            ┆ (ST…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53783.0 ┆ 6983.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53795.0 ┆ 6995.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 22     ┆         ┆            │
│            ┆ (TS…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53795.0 ┆ 6995.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53802.0 ┆ 7002.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 22     ┆         ┆            │
│            ┆ (TS…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53811.0 ┆ 7011.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 22     ┆         ┆            │
│            ┆ (TS…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53927.0 ┆ 7127.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 77     ┆         ┆            │
│            ┆ (BO…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53943.0 ┆ 7143.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 3      ┆         ┆            │
│            ┆ (RIC…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 53955.0 ┆ 7155.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 14     ┆         ┆            │
│            ┆ (AL…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54008.0 ┆ 7208.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 3      ┆         ┆            │
│            ┆ (RIC…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54029.0 ┆ 7229.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 14     ┆         ┆            │
│            ┆ (AL…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54183.0 ┆ 7383.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 10     ┆         ┆            │
│            ┆ (GA…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54218.0 ┆ 7418.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 10     ┆         ┆            │
│            ┆ (GA…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54323.0 ┆ 7523.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 10     ┆         ┆            │
│            ┆ (GA…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54451.0 ┆ 7651.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 23     ┆         ┆            │
│            ┆ (AL…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54469.0 ┆ 7669.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 22     ┆         ┆            │
│            ┆ (TS…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54493.0 ┆ 7693.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 23     ┆         ┆            │
│            ┆ (AL…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54508.0 ┆ 7708.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 22     ┆         ┆            │
│            ┆ (TS…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54810.0 ┆ 8010.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54819.0 ┆ 8019.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54828.0 ┆ 8028.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54885.0 ┆ 8085.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54903.0 ┆ 8103.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54904.0 ┆ 8104.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54910.0 ┆ 8110.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 2      ┆         ┆            │
│            ┆ (SAR…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 54919.0 ┆ 8119.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 55103.0 ┆ 8303.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 55119.0 ┆ 8319.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 55178.0 ┆ 8378.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 55216.0 ┆ 8416.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 24     ┆         ┆            │
│            ┆ (ZH…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 55296.0 ┆ 8496.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 18     ┆         ┆            │
│            ┆ (ST…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 55328.0 ┆ 8528.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 77     ┆         ┆            │
│            ┆ (BO…       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 55363.0 ┆ 8563.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 3      ┆         ┆            │
│            ┆ (RIC…      ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 55391.0 ┆ 8591.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 14     ┆         ┆            │
│            ┆ (AL…       ┆         ┆            │
│ CHEQUERED  ┆ CHEQUERED  ┆ 55586.0 ┆ 8786.0     │
│            ┆ FLAG       ┆         ┆            │
│ BLUE       ┆ WAVED BLUE ┆ 55590.0 ┆ 8790.0     │
│            ┆ FLAG FOR   ┆         ┆            │
│            ┆ CAR 18     ┆         ┆            │
│            ┆ (ST…       ┆         ┆            │
└────────────┴────────────┴─────────┴────────────┘

In [8]:
race.telemetry["VER"]

shape: (66_066, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Date      ┆ SessionTi ┆ DriverAhe ┆ DistanceT ┆ … ┆ SessionSe ┆ session_t ┆ progress  ┆ TimeToDr │
│ ---       ┆ me        ┆ ad        ┆ oDriverAh ┆   ┆ conds     ┆ ime       ┆ ---       ┆ iverAhea │
│ datetime[ ┆ ---       ┆ ---       ┆ ead       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ d        │
│ ns]       ┆ duration[ ┆ str       ┆ ---       ┆   ┆ f64       ┆ f64       ┆           ┆ ---      │
│           ┆ ns]       ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2024-05-2 ┆ 55m 5s    ┆           ┆ 0.159444  ┆ … ┆ 3305.68   ┆ 0.0       ┆ -0.001428 ┆ NaN      │
│ 6 13:03:1 ┆ 680ms     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1.069     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 55m 5s    ┆           ┆ 0.159444  ┆ … ┆ 3305.767  ┆ 0.087     ┆ 0.0       ┆ NaN      │
│ 6 13:03:1 ┆ 767ms     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1.156     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 55m 5s    ┆           ┆ 0.159444  ┆ … ┆ 3305.841  ┆ 0.161     ┆ 0.003792  ┆ 0.157129 │
│ 6 13:03:1 ┆ 841ms     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1.230     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 55m 5s    ┆ 23        ┆ 0.159444  ┆ … ┆ 3305.967  ┆ 0.287     ┆ 0.0       ┆ NaN      │
│ 6 13:03:1 ┆ 967ms     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1.356     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 55m 6s    ┆ 23        ┆ 0.165918  ┆ … ┆ 3306.08   ┆ 0.4       ┆ -0.039118 ┆ NaN      │
│ 6 13:03:1 ┆ 80ms      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1.469     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2024-05-2 ┆ 3h 18m    ┆ 63        ┆ 52.04     ┆ … ┆ 11914.85  ┆ 8609.17   ┆ 256438.18 ┆ 5.09067  │
│ 6 15:26:4 ┆ 34s 850ms ┆           ┆           ┆   ┆           ┆           ┆ 5664      ┆          │
│ 0.239     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 3h 18m    ┆ 63        ┆ 52.04     ┆ … ┆ 11915.049 ┆ 8609.369  ┆ 256453.15 ┆ 5.084572 │
│ 6 15:26:4 ┆ 35s 49ms  ┆           ┆           ┆   ┆           ┆           ┆ 3808      ┆          │
│ 0.438     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 3h 18m    ┆           ┆ 52.04     ┆ … ┆ 11915.196 ┆ 8609.516  ┆ 256464.05 ┆ 5.081202 │
│ 6 15:26:4 ┆ 35s 196ms ┆           ┆           ┆   ┆           ┆           ┆ 1839      ┆          │
│ 0.585     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 3h 18m    ┆           ┆ 52.04     ┆ … ┆ 11915.289 ┆ 8609.609  ┆ 256470.81 ┆ 6.216512 │
│ 6 15:26:4 ┆ 35s 289ms ┆           ┆           ┆   ┆           ┆           ┆ 1757      ┆          │
│ 0.678     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 3h 18m    ┆           ┆ 52.04     ┆ … ┆ 11915.36  ┆ 8609.68   ┆ 256475.90 ┆ 13.91164 │
│ 6 15:26:4 ┆ 35s 360ms ┆           ┆           ┆   ┆           ┆           ┆ 2064      ┆ 8        │
│ 0.749     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
race.telemetry["LEC"]

shape: (65_794, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Date      ┆ SessionTi ┆ DriverAhe ┆ DistanceT ┆ … ┆ SessionSe ┆ session_t ┆ progress  ┆ TimeToDr │
│ ---       ┆ me        ┆ ad        ┆ oDriverAh ┆   ┆ conds     ┆ ime       ┆ ---       ┆ iverAhea │
│ datetime[ ┆ ---       ┆ ---       ┆ ead       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ d        │
│ ns]       ┆ duration[ ┆ str       ┆ ---       ┆   ┆ f64       ┆ f64       ┆           ┆ ---      │
│           ┆ ns]       ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2024-05-2 ┆ 55m 5s    ┆           ┆ 0.159444  ┆ … ┆ 3305.68   ┆ 0.0       ┆ 0.001252  ┆ -0.29094 │
│ 6 13:03:1 ┆ 680ms     ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ 1.069     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 55m 5s    ┆           ┆ 0.159444  ┆ … ┆ 3305.767  ┆ 0.087     ┆ 0.0       ┆ NaN      │
│ 6 13:03:1 ┆ 767ms     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1.156     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 55m 5s    ┆           ┆ 0.159444  ┆ … ┆ 3305.841  ┆ 0.161     ┆ -0.003302 ┆ NaN      │
│ 6 13:03:1 ┆ 841ms     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1.230     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 55m 5s    ┆ 23        ┆ 0.159444  ┆ … ┆ 3305.967  ┆ 0.287     ┆ 0.0       ┆ NaN      │
│ 6 13:03:1 ┆ 967ms     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1.356     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 55m 6s    ┆ 23        ┆ 0.103141  ┆ … ┆ 3306.08   ┆ 0.4       ┆ 0.034063  ┆ 0.005612 │
│ 6 13:03:1 ┆ 80ms      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1.469     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2024-05-2 ┆ 3h 18m    ┆           ┆ null      ┆ … ┆ 11900.717 ┆ 8595.037  ┆ 256433.61 ┆ NaN      │
│ 6 15:26:2 ┆ 20s 717ms ┆           ┆           ┆   ┆           ┆           ┆ 4617      ┆          │
│ 6.106     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 3h 18m    ┆           ┆ null      ┆ … ┆ 11900.869 ┆ 8595.189  ┆ 256442.71 ┆ NaN      │
│ 6 15:26:2 ┆ 20s 869ms ┆           ┆           ┆   ┆           ┆           ┆ 5158      ┆          │
│ 6.258     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 3h 18m    ┆           ┆ null      ┆ … ┆ 11901.036 ┆ 8595.356  ┆ 256452.48 ┆ NaN      │
│ 6 15:26:2 ┆ 21s 36ms  ┆           ┆           ┆   ┆           ┆           ┆ 8784      ┆          │
│ 6.425     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 3h 18m    ┆           ┆ null      ┆ … ┆ 11901.25  ┆ 8595.57   ┆ 256464.77 ┆ NaN      │
│ 6 15:26:2 ┆ 21s 250ms ┆           ┆           ┆   ┆           ┆           ┆ 8852      ┆          │
│ 6.639     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-05-2 ┆ 3h 18m    ┆           ┆ null      ┆ … ┆ 11901.507 ┆ 8595.827  ┆ 256479.19 ┆ NaN      │
│ 6 15:26:2 ┆ 21s 507ms ┆           ┆           ┆   ┆           ┆           ┆ 0957      ┆          │
│ 6.896     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
race.telemetry.keys()

dict_keys(['LEC', 'PIA', 'SAI', 'NOR', 'RUS', 'VER', 'HAM', 'TSU', 'ALB', 'GAS', 'ALO', 'RIC', 'BOT', 'STR', 'SAR', 'ZHO', 'OCO', 'PER', 'HUL', 'MAG'])

In [11]:
import polars as pl
with pl.Config(tbl_rows=20, tbl_cols=-1):
    display(race.order)  # or just: race.order

shape: (762, 41)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ses ┆ LEC ┆ PIA ┆ SAI ┆ NOR ┆ RUS ┆ VER ┆ HAM ┆ TSU ┆ ALB ┆ GAS ┆ ALO ┆ RIC ┆ BOT ┆ STR ┆ SAR ┆ ZHO ┆ OCO ┆ PER ┆ HUL ┆ MAG ┆ LEC ┆ PIA ┆ SAI ┆ NOR ┆ RUS ┆ VER ┆ HAM ┆ TSU ┆ ALB ┆ GAS ┆ ALO ┆ RIC ┆ BOT ┆ STR ┆ SAR ┆ ZHO ┆ OCO ┆ PER ┆ HUL ┆ MAG │
│ sio ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _pr ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po │
│ n_t ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ ogr ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit ┆ sit │
│ ime ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ess ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion ┆ ion │
│ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ u8  │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 16  ┆ 2   ┆ 11  ┆ 6   ┆ 10  ┆ 20  ┆ 4   ┆ 9   ┆ 13  ┆ 3   ┆ 14  ┆ 17  ┆ 8   ┆ 1   ┆ 7   ┆ 18  ┆ 5   ┆ 12  ┆ 19  ┆ 15  │
│     ┆ 012 ┆ 062 ┆ 017 ┆ 046 ┆ 027 ┆ 001 ┆ 052 ┆ 029 ┆ 017 ┆ 057 ┆ 016 ┆ 010 ┆ 032 ┆ 064 ┆ 035 ┆ 002 ┆ 049 ┆ 017 ┆ 001 ┆ 013 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 52  ┆ 05  ┆ 79  ┆ 42  ┆ 27  ┆ 428 ┆ 43  ┆ 54  ┆ 18  ┆ 4   ┆ 58  ┆ 63  ┆ 51  ┆ 44  ┆ 24  ┆ 25  ┆ 73  ┆ 77  ┆ 59  ┆ 17  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   │
│ 87  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 483 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.1 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 6   ┆ 19  ┆ 10  ┆ 15  ┆ 11  ┆ 2   ┆ 17  ┆ 12  ┆ 1   ┆ 18  ┆ 8   ┆ 5   ┆ 13  ┆ 20  ┆ 14  ┆ 4   ┆ 16  ┆ 9   ┆ 3   ┆ 7   │
│ 61  ┆ 003 ┆ 016 ┆ 004 ┆ 012 ┆ 007 ┆ 037 ┆ 013 ┆ 007 ┆ 849 ┆ 015 ┆ 004 ┆ 002 ┆ 008 ┆ 017 ┆ 009 ┆ 000 ┆ 013 ┆ 004 ┆ 000 ┆ 003 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 302 ┆ 411 ┆ 693 ┆ 282 ┆ 203 ┆ 92  ┆ 87  ┆ 807 ┆ 04  ┆ 185 ┆ 371 ┆ 801 ┆ 596 ┆ 046 ┆ 313 ┆ 581 ┆ 155 ┆ 688 ┆ 407 ┆ 475 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.2 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 1   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 2   │
│ 87  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 594 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.4 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ -0. ┆ 0.1 ┆ 0.0 ┆ 0.2 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 16  ┆ 3   ┆ 12  ┆ 7   ┆ 11  ┆ 20  ┆ 5   ┆ 10  ┆ 1   ┆ 4   ┆ 14  ┆ 17  ┆ 9   ┆ 2   ┆ 8   ┆ 18  ┆ 6   ┆ 13  ┆ 19  ┆ 15  │
│     ┆ 340 ┆ 692 ┆ 484 ┆ 266 ┆ 742 ┆ 039 ┆ 430 ┆ 805 ┆ 690 ┆ 566 ┆ 450 ┆ 288 ┆ 886 ┆ 758 ┆ 960 ┆ 059 ┆ 356 ┆ 483 ┆ 042 ┆ 358 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 63  ┆ 7   ┆ 06  ┆ 79  ┆ 99  ┆ 118 ┆ 65  ┆ 26  ┆ 59  ┆ 26  ┆ 86  ┆ 89  ┆ 64  ┆ 25  ┆ 59  ┆ 98  ┆ 86  ┆ 5   ┆     ┆ 43  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.6 ┆ 0.2 ┆ 0.8 ┆ 0.3 ┆ 0.5 ┆ 0.4 ┆ 0.0 ┆ 0.6 ┆ 0.4 ┆ 0.6 ┆ 0.7 ┆ 0.3 ┆ 0.2 ┆ 0.4 ┆ 0.8 ┆ 0.5 ┆ 0.1 ┆ 0.6 ┆ 0.3 ┆ 0.1 ┆ 0.2 ┆ 15  ┆ 1   ┆ 12  ┆ 7   ┆ 9   ┆ 20  ┆ 4   ┆ 9   ┆ 6   ┆ 3   ┆ 12  ┆ 15  ┆ 9   ┆ 1   ┆ 7   ┆ 18  ┆ 4   ┆ 12  ┆ 18  ┆ 15  │
│ 07  ┆ 666 ┆     ┆ 555 ┆ 333 ┆ 444 ┆     ┆ 222 ┆ 444 ┆ 038 ┆ 111 ┆ 555 ┆ 666 ┆ 444 ┆     ┆ 333 ┆ 777 ┆ 222 ┆ 555 ┆ 777 ┆ 666 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 67  ┆     ┆ 56  ┆ 33  ┆ 44  ┆     ┆ 22  ┆ 44  ┆ 89  ┆ 11  ┆ 56  ┆ 67  ┆ 44  ┆     ┆ 33  ┆ 78  ┆ 22  ┆ 56  ┆ 78  ┆ 67  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.6 ┆ 0.3 ┆ 1.0 ┆ 0.5 ┆ 0.6 ┆ 0.6 ┆ 0.0 ┆ 0.7 ┆ 0.5 ┆ 0.7 ┆ 0.8 ┆ 0.5 ┆ 0.4 ┆ 0.5 ┆ 0.9 ┆ 0.7 ┆ 0.3 ┆ 0.7 ┆ 0.5 ┆ 0.3 ┆ 0.3 ┆ 16  ┆ 1   ┆ 14  ┆ 8   ┆ 9   ┆ 20  ┆ 5   ┆ 10  ┆ 6   ┆ 3   ┆ 12  ┆ 15  ┆ 11  ┆ 2   ┆ 7   ┆ 19  ┆ 4   ┆ 13  ┆ 18  ┆ 17  │
│ 6   ┆ 899 ┆ 070 ┆ 126 ┆ 378 ┆ 073 ┆ 949 ┆ 555 ┆ 922 ┆ 256 ┆ 802 ┆ 207 ┆ 024 ┆ 725 ┆ 911 ┆ 121 ┆ 005 ┆ 734 ┆ 128 ┆ 048 ┆ 856 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 43  ┆ 68  ┆ 73  ┆ 15  ┆ 79  ┆ 14  ┆ 88  ┆ 69  ┆ 17  ┆ 16  ┆ 3   ┆ 98  ┆ 23  ┆ 61  ┆ 1   ┆ 09  ┆ 92  ┆ 08  ┆ 72  ┆ 24  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.8 ┆ 1.1 ┆ 2.0 ┆ 1.4 ┆ 1.2 ┆ 1.5 ┆ 0.8 ┆ 1.4 ┆ 1.4 ┆ 1.4 ┆ 1.6 ┆ 1.5 ┆ 1.2 ┆ 1.3 ┆ 2.0 ┆ 1.7 ┆ 1.0 ┆ 1.5 ┆ 1.4 ┆ 1.1 ┆ 1.1 ┆ 16  ┆ 1   ┆ 9   ┆ 14  ┆ 6   ┆ 20  ┆ 10  ┆ 8   ┆ 11  ┆ 4   ┆ 7   ┆ 15  ┆ 13  ┆ 2   ┆ 3   ┆ 19  ┆ 5   ┆ 12  ┆ 18  ┆ 17  │
│ 8   ┆ 690 ┆ 812 ┆ 844 ┆ 748 ┆ 733 ┆ 259 ┆ 470 ┆ 946 ┆ 298 ┆ 933 ┆ 592 ┆ 464 ┆ 430 ┆ 020 ┆ 381 ┆ 831 ┆ 975 ┆ 143 ┆ 558 ┆ 666 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 86  ┆ 4   ┆ 74  ┆ 62  ┆ 82  ┆ 77  ┆ 5   ┆ 17  ┆ 12  ┆ 2   ┆ 38  ┆ 02  ┆ 28  ┆ 23  ┆ 72  ┆ 68  ┆ 94  ┆ 56  ┆ 38  ┆ 36  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0.8 ┆ 1.2 ┆ 2.1 ┆ 1.5 ┆ 1.3 ┆ 1.6 ┆ 0.8 ┆ 1.4 ┆ 1.5 ┆ 1.4 ┆ 1.7 ┆ 1.6 ┆ 1.2 ┆ 1.3 ┆ 2.0 ┆ 1.7 ┆ 1.1 ┆ 1.6 ┆ 1.4 ┆ 1.1 ┆ 1.2 ┆ 16  ┆ 1   ┆ 9   ┆ 14  ┆ 6   ┆ 20  ┆ 10  ┆ 8   ┆ 11  ┆ 4   ┆ 7   ┆ 15  ┆ 13  ┆ 2   ┆ 3   ┆ 19  ┆ 5   ┆ 12  ┆ 18  ┆ 16  │
│ 87  ┆     ┆ 222 ┆ 222 ┆ 111 ┆ 111 ┆ 555 ┆ 777 ┆ 333 ┆ 594 ┆ 222 ┆     ┆ 777 ┆ 777 ┆ 444 ┆ 777 ┆ 111 ┆ 333 ┆ 444 ┆ 888 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 22  ┆ 22  ┆ 11  ┆ 11  ┆ 56  ┆ 78  ┆ 33  ┆ 44  ┆ 22  ┆     ┆ 78  ┆ 78  ┆ 44  ┆ 78  ┆ 11  ┆ 33  ┆ 44  ┆ 89  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1.1 ┆ 2.5 ┆ 3.8 ┆ 3.1 ┆ 3.2 ┆ 3.2 ┆ 2.1 ┆ 2.9 ┆ 3.3 ┆ 2.8 ┆ 2.9 ┆ 3.3 ┆ 2.5 ┆ 3.0 ┆ 4.0 ┆ 3.4 ┆ 2.2 ┆ 3.3 ┆ 2.5 ┆ 2.6 ┆ 2.7 ┆ 18  ┆ 2   ┆ 9   ┆ 7   ┆ 8   ┆ 20  ┆ 11  ┆ 6   ┆ 13  ┆ 12  ┆ 4   ┆ 16  ┆ 10  ┆ 1   ┆ 3   ┆ 19  ┆ 5   ┆ 17  ┆ 15  ┆ 14  │
│ 4   ┆ 527 ┆ 874 ┆ 164 ┆ 937 ┆ 431 ┆ 456 ┆ 982 ┆ 194 ┆ 521 ┆ 495 ┆ 638 ┆ 993 ┆ 642 ┆ 134 ┆ 786 ┆ 362 ┆ 287 ┆ 774 ┆ 045 ┆ 190 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 3   ┆ 54  ┆ 32  ┆ 95  ┆ 44  ┆ 92  ┆ 22  ┆ 72  ┆ 11  ┆ 4   ┆     ┆ 27  ┆ 87  ┆ 17  ┆ 5   ┆ 6   ┆ 56  ┆ 44  ┆ 24  ┆ 55  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 860 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 251 ┆ 251 ┆ 251 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 247 ┆ 312 ┆ 592 ┆ 792 ┆ 773 ┆ 2   ┆ 1   ┆ 3   ┆ 4   ┆ 5   ┆ 6   ┆ 7   ┆ 8   ┆ 9   ┆ 10  ┆ 15  ┆ 12  ┆ 11  ┆ 13  ┆ 14  ┆ 16  ┆ 17  ┆ 20  ┆ 18  ┆ 19  │
│ 4.8 ┆ 479 ┆ 483 ┆ 472 ┆ 467 ┆ 217 ┆ 183 ┆ 156 ┆ 931 ┆ 215 ┆ 076 ┆ 888 ┆ 904 ┆ 905 ┆ 904 ┆ 891 ┆ 907 ┆ 0.4 ┆ .20 ┆ .77 ┆ .18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 36  ┆ .19 ┆ .92 ┆ .18 ┆ .08 ┆ .44 ┆ .14 ┆ .63 ┆ .29 ┆ .34 ┆ .42 ┆ .08 ┆ .32 ┆ .90 ┆ .11 ┆ .31 ┆ .55 ┆ 627 ┆ 972 ┆ 333 ┆ 083 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 095 ┆ 245 ┆ 870 ┆ 542 ┆ 183 ┆ 989 ┆ 572 ┆ 750 ┆ 222 ┆ 778 ┆ 616 ┆ 973 ┆ 842 ┆ 861 ┆ 733 ┆ 539 ┆ 78  ┆ 2   ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 7   ┆ 4   ┆ 5   ┆ 4   ┆ 9   ┆ 5   ┆ 8   ┆ 4   ┆ 7   ┆ 2   ┆ 6   ┆ 7   ┆     ┆ 5   ┆ 6   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 860 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 252 ┆ 251 ┆ 251 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 248 ┆ 312 ┆ 592 ┆ 792 ┆ 773 ┆ 2   ┆ 1   ┆ 3   ┆ 5   ┆ 4   ┆ 6   ┆ 7   ┆ 8   ┆ 9   ┆ 10  ┆ 15  ┆ 12  ┆ 11  ┆ 13  ┆ 14  ┆ 16  ┆ 17  ┆ 20  ┆ 18  ┆ 19  │
│ 8.8 ┆ 479 ┆ 483 ┆ 472 ┆ 467 ┆ 468 ┆ 416 ┆ 348 ┆ 026 ┆ 319 ┆ 154 ┆ 888 ┆ 904 ┆ 905 ┆ 904 ┆ 892 ┆ 010 ┆ 0.4 ┆ .20 ┆ .77 ┆ .18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 76  ┆ .19 ┆ .92 ┆ .18 ┆ .08 ┆ .95 ┆ .49 ┆ .31 ┆ .08 ┆ .95 ┆ .48 ┆ .08 ┆ .32 ┆ .90 ┆ .11 ┆ .46 ┆ .18 ┆ 627 ┆ 972 ┆ 333 ┆ 083 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 095 ┆ 245 ┆ 870 ┆ 542 ┆ 739 ┆ 628 ┆ 128 ┆ 861 ┆ 222 ┆ 306 ┆ 616 ┆ 973 ┆ 842 ┆ 861 ┆ 470 ┆ 733 ┆ 78  ┆ 2   ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 7   ┆ 4   ┆ 5   ┆ 4   ┆ 5   ┆ 4   ┆ 4   ┆ 5   ┆ 7   ┆     ┆ 6   ┆ 7   ┆     ┆ 5   ┆ 9   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 860 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 252 ┆ 251 ┆ 251 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 248 ┆ 312 ┆ 592 ┆ 792 ┆ 773 ┆ 2   ┆ 1   ┆ 4   ┆ 5   ┆ 3   ┆ 6   ┆ 7   ┆ 8   ┆ 9   ┆ 10  ┆ 15  ┆ 12  ┆ 11  ┆ 13  ┆ 14  ┆ 16  ┆ 17  ┆ 20  ┆ 18  ┆ 19  │
│ 9.0 ┆ 479 ┆ 483 ┆ 472 ┆ 467 ┆ 478 ┆ 426 ┆ 357 ┆ 030 ┆ 323 ┆ 156 ┆ 888 ┆ 904 ┆ 905 ┆ 904 ┆ 892 ┆ 013 ┆ 0.4 ┆ .20 ┆ .77 ┆ .18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 09  ┆ .19 ┆ .92 ┆ .18 ┆ .08 ┆ .81 ┆ .25 ┆ .37 ┆ .12 ┆ .54 ┆ .53 ┆ .08 ┆ .32 ┆ .90 ┆ .11 ┆ .46 ┆ .23 ┆ 627 ┆ 972 ┆ 333 ┆ 083 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 095 ┆ 245 ┆ 870 ┆ 542 ┆ 246 ┆ 028 ┆ 959 ┆ 747 ┆ 348 ┆ 627 ┆ 616 ┆ 973 ┆ 842 ┆ 861 ┆ 470 ┆ 963 ┆ 78  ┆ 2   ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 7   ┆ 4   ┆ 5   ┆ 4   ┆ 6   ┆ 3   ┆ 7   ┆ 1   ┆ 6   ┆ 6   ┆ 6   ┆ 7   ┆     ┆ 5   ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 860 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 252 ┆ 251 ┆ 251 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 248 ┆ 312 ┆ 592 ┆ 792 ┆ 773 ┆ 3   ┆ 2   ┆ 4   ┆ 5   ┆ 1   ┆ 6   ┆ 7   ┆ 8   ┆ 9   ┆ 10  ┆ 15  ┆ 12  ┆ 11  ┆ 13  ┆ 14  ┆ 16  ┆ 17  ┆ 20  ┆ 18  ┆ 19  │
│ 9.1 ┆ 479 ┆ 483 ┆ 472 ┆ 467 ┆ 486 ┆ 434 ┆ 364 ┆ 033 ┆ 326 ┆ 158 ┆ 888 ┆ 904 ┆ 905 ┆ 904 ┆ 892 ┆ 015 ┆ 0.4 ┆ .20 ┆ .77 ┆ .18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 16  ┆ .19 ┆ .92 ┆ .18 ┆ .08 ┆ .62 ┆ .16 ┆ .71 ┆ .55 ┆ .55 ┆ .28 ┆ .08 ┆ .32 ┆ .90 ┆ .11 ┆ .46 ┆ .72 ┆ 627 ┆ 972 ┆ 333 ┆ 083 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 095 ┆ 245 ┆ 870 ┆ 542 ┆ 406 ┆ 295 ┆ 128 ┆ 528 ┆ 222 ┆ 306 ┆ 616 ┆ 973 ┆ 842 ┆ 861 ┆ 470 ┆ 066 ┆ 78  ┆ 2   ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 7   ┆ 4   ┆ 5   ┆ 4   ┆ 1   ┆     ┆ 4   ┆ 2   ┆ 7   ┆     ┆ 6   ┆ 7   ┆     ┆ 5   ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 860 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 252 ┆ 251 ┆ 251 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 248 ┆ 312 ┆ 592 ┆ 792 ┆ 773 ┆ 3   ┆ 2   ┆ 4   ┆ 6   ┆ 1   ┆ 5   ┆ 7   ┆ 8   ┆ 9   ┆ 10  ┆ 15  ┆ 12  ┆ 11  ┆ 13  ┆ 14  ┆ 16  ┆ 17  ┆ 20  ┆ 18  ┆ 19  │
│ 9.6 ┆ 479 ┆ 483 ┆ 472 ┆ 467 ┆ 488 ┆ 470 ┆ 398 ┆ 051 ┆ 342 ┆ 168 ┆ 888 ┆ 904 ┆ 905 ┆ 904 ┆ 892 ┆ 027 ┆ 0.4 ┆ .20 ┆ .77 ┆ .18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 09  ┆ .19 ┆ .92 ┆ .18 ┆ .08 ┆ .06 ┆ .81 ┆ .98 ┆ .88 ┆ .14 ┆ .16 ┆ .08 ┆ .32 ┆ .90 ┆ .11 ┆ .46 ┆ .91 ┆ 627 ┆ 972 ┆ 333 ┆ 083 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 095 ┆ 245 ┆ 870 ┆ 542 ┆ 248 ┆ 175 ┆ 583 ┆ 245 ┆ 356 ┆ 512 ┆ 616 ┆ 973 ┆ 842 ┆ 861 ┆ 470 ┆ 351 ┆ 78  ┆ 2   ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 7   ┆ 4   ┆ 5   ┆ 4   ┆ 5   ┆ 7   ┆ 9   ┆ 7   ┆ 5   ┆ 2   ┆ 6   ┆ 7   ┆     ┆ 5   ┆ 9   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 860 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 252 ┆ 251 ┆ 251 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 248 ┆ 312 ┆ 592 ┆ 792 ┆ 773 ┆ 3   ┆ 2   ┆ 5   ┆ 6   ┆ 1   ┆ 4   ┆ 7   ┆ 8   ┆ 9   ┆ 10  ┆ 15  ┆ 12  ┆ 11  ┆ 13  ┆ 14  ┆ 16  ┆ 17  ┆ 20  ┆ 18  ┆ 19  │
│ 9.6 ┆ 479 ┆ 483 ┆ 472 ┆ 467 ┆ 488 ┆ 475 ┆ 398 ┆ 051 ┆ 342 ┆ 168 ┆ 888 ┆ 904 ┆ 905 ┆ 904 ┆ 892 ┆ 027 ┆ 0.4 ┆ .20 ┆ .77 ┆ .18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 8   ┆ .19 ┆ .92 ┆ .18 ┆ .08 ┆ .06 ┆ .90 ┆ .98 ┆ .88 ┆ .14 ┆ .16 ┆ .08 ┆ .32 ┆ .90 ┆ .11 ┆ .46 ┆ .91 ┆ 627 ┆ 972 ┆ 333 ┆ 083 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 095 ┆ 245 ┆ 870 ┆ 542 ┆ 248 ┆ 206 ┆ 583 ┆ 245 ┆ 356 ┆ 512 ┆ 616 ┆ 973 ┆ 842 ┆ 861 ┆ 470 ┆ 351 ┆ 78  ┆ 2   ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 7   ┆ 4   ┆ 5   ┆ 4   ┆ 5   ┆ 4   ┆ 9   ┆ 7   ┆ 5   ┆ 2   ┆ 6   ┆ 7   ┆     ┆ 5   ┆ 9   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 861 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 252 ┆ 251 ┆ 251 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 248 ┆ 312 ┆ 592 ┆ 792 ┆ 773 ┆ 3   ┆ 2   ┆ 6   ┆ 7   ┆ 1   ┆ 4   ┆ 5   ┆ 8   ┆ 9   ┆ 10  ┆ 15  ┆ 12  ┆ 11  ┆ 13  ┆ 14  ┆ 16  ┆ 17  ┆ 20  ┆ 18  ┆ 19  │
│ 0.7 ┆ 479 ┆ 483 ┆ 472 ┆ 467 ┆ 488 ┆ 475 ┆ 473 ┆ 095 ┆ 379 ┆ 192 ┆ 888 ┆ 904 ┆ 905 ┆ 904 ┆ 892 ┆ 056 ┆ 0.4 ┆ .20 ┆ .77 ┆ .18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 35  ┆ .19 ┆ .92 ┆ .18 ┆ .08 ┆ .06 ┆ .90 ┆ .62 ┆ .50 ┆ .42 ┆ .80 ┆ .08 ┆ .32 ┆ .90 ┆ .11 ┆ .46 ┆ .44 ┆ 627 ┆ 972 ┆ 333 ┆ 083 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 095 ┆ 245 ┆ 870 ┆ 542 ┆ 248 ┆ 206 ┆ 597 ┆ 582 ┆ 136 ┆ 763 ┆ 616 ┆ 973 ┆ 842 ┆ 861 ┆ 470 ┆ 138 ┆ 78  ┆ 2   ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 7   ┆ 4   ┆ 5   ┆ 4   ┆ 5   ┆ 4   ┆ 1   ┆ 8   ┆ 5   ┆ 7   ┆ 6   ┆ 7   ┆     ┆ 5   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 865 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 253 ┆ 253 ┆ 252 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 312 ┆ 592 ┆ 792 ┆ 773 ┆ 3   ┆ 2   ┆ 6   ┆ 7   ┆ 1   ┆ 4   ┆ 5   ┆ 8   ┆ 9   ┆ 10  ┆ 16  ┆ 12  ┆ 11  ┆ 13  ┆ 14  ┆ 15  ┆ 17  ┆ 20  ┆ 18  ┆ 19  │
│ 0.8 ┆ 479 ┆ 483 ┆ 472 ┆ 467 ┆ 488 ┆ 475 ┆ 473 ┆ 196 ┆ 186 ┆ 891 ┆ 888 ┆ 904 ┆ 905 ┆ 904 ┆ 892 ┆ 888 ┆ 0.4 ┆ .20 ┆ .77 ┆ .18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 76  ┆ .19 ┆ .92 ┆ .18 ┆ .08 ┆ .06 ┆ .90 ┆ .62 ┆ .20 ┆ .67 ┆ .61 ┆ .08 ┆ .32 ┆ .90 ┆ .11 ┆ .46 ┆ .57 ┆ 627 ┆ 972 ┆ 333 ┆ 083 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 095 ┆ 245 ┆ 870 ┆ 542 ┆ 248 ┆ 206 ┆ 597 ┆ 785 ┆ 724 ┆ 972 ┆ 616 ┆ 973 ┆ 842 ┆ 861 ┆ 470 ┆ 983 ┆ 78  ┆ 2   ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 7   ┆ 4   ┆ 5   ┆ 4   ┆ 5   ┆ 4   ┆ 1   ┆     ┆ 9   ┆ 7   ┆ 6   ┆ 7   ┆     ┆ 5   ┆ 9   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 865 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 256 ┆ 253 ┆ 253 ┆ 252 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 249 ┆ 312 ┆ 592 ┆ 792 ┆ 773 ┆ 3   ┆ 2   ┆ 6   ┆ 7   ┆ 1   ┆ 4   ┆ 5   ┆ 8   ┆ 9   ┆ 10  ┆ 16  ┆ 12  ┆ 11  ┆ 13  ┆ 15  ┆ 14  ┆ 17  ┆ 20  ┆ 18  ┆ 19  │

In [ ]:

import plotly.graph_objects as go

fig = go.Figure()

driver_cols = [col for col in race.order.columns if col.endswith('_progress')]

for col in driver_cols:
    driver = col.replace('_progress', '')
    fig.add_trace(go.Scatter(
        x=race.order['session_time'],
        y=race.order[col],
        mode='lines',
        name=driver,
        line=dict(width=2)
    ))

fig.update_layout(
    title='Driver Progress vs Session Time (Log Scale)',
    xaxis_title='Session Time',
    yaxis_title='Progress',
    height=700,
    hovermode='x unified'
)

fig.show()
plt.show()